matrix-org/matrix-ios-sdk

- MatrixSDK/VoIP/CallStack/MXCallStackCall.h
- MatrixSDK/VoIP/CallStack/OpenWebRTC/MXOpenWebRTCCallStackCall.m
- MatrixSDK/VoIP/MXCall.m
OWR needs the offer when trickle candidates come in, else it can't process them. Start capturing before we start the call ringing because it needs capture sources to process the offer. Other way of doing this would be to buffer the trickle candidates until the user answers, but we probably want to start capturing before answering so we can show mirrored video and I think it makes for a better API if the matrix layer doesn't have to buffer candidates.
There is still a problem where calls can't be established after a call is hung up from the other end (I think).
> Separate out handling the offer and getting the answer back

- MatrixSDK/JSONModels/MXJSONModel.m
- MatrixSDK/Utils/MXHTTPClient.m
Branch to kill leaks and to optimise memory.
Thanks to these current changes, in my case, the app uses 25MB just after startup instead of 35MB before.
The usage peak during an initialSync is now 45Mb instead of 160MB.
Work still in progress
> Memory optimisation

- MatrixSDK/MXRestClient.m
Send event to room by using a transaction id with PUT method instead of POST.
> SYIOS-164: Bug Fix - Duplicated events on bad networks

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.m
Only read receipts are enabled.
Other C-S v2 implementation is commented (uncomplete).
> Server Sync V2: Increase supported Server-Client version API: v2

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.m
Reformatted all existing blocks to be conformed with the code writing.
The added autoreleasepool block reduces this memory usage spike (which happens when retrieving thousands of events on app resuming):
> MXSession: Added an @autoreleasepool on live events management.

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomState.h
- MatrixSDK/Data/MXRoomState.m
- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.m
We define a new processing queue to process server response.
This queue is used to create models from JSON dictionary without blocking the main thread.
> MXRestClient: optimize server response parsing.

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomMember.h
- MatrixSDK/Data/MXRoomMember.m
- MatrixSDK/Data/MXRoomState.m
- MatrixSDKTests/MXRoomStateDynamicTests.m
This PR contains 2 improvements on [MXRoomState copyWithZone:]:
- limit the number of calls of it
- avoid useless deep copies in its implementation
> Room state optimisation

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/Store/MXCoreDataStore/MXCoreDataStore.m
- MatrixSDK/Data/Store/MXFileStore/MXFileRoomStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.h
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
- MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
- MatrixSDK/Data/Store/MXStore.h
- MatrixSDKTests/MXStoreCoreDataStoreTests.m
- MatrixSDKTests/MXStoreFileStoreTests.m
- MatrixSDKTests/MXStoreMemoryStoreTests.m
- MatrixSDKTests/MXStoreNoStoreTests.m
- MatrixSDKTests/MXStoreTests.h
- MatrixSDKTests/MXStoreTests.m
In this PR, a dedicated method to check duplicate events has been added to MXStore : [MXStore eventExistsWithEventId].
The previously method used for that, [MXStore eventWithEventId:], can cost too much time in MXStore implementations - specially for the core data store. It is quicker to check existence in a db than retrieving all data to build the MXEvent matching the event id.
The implementation of this method has been improved in MXMemoryStore and MXFileStore so that it is 350 times quicker:
- Before: 
- After:
> MXStore: Added a new optimised eventExistsWithEventId: method 

- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/JSONModels/MXJSONModel.m
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MXRestClient.m
Improved processing of HS requests responses that contain matrix events.
The improvement mainly consists in removing the Mantle modelling which appears to be slow on arrays with thousands of items.
Even if such processing is done on a separated thread, not on the UI one, it still worths to save CPU time
Here is the result of the improvement on a /initialSync response processing:
- before: 2.4s
- after: 0.2s
> Mxevent optimisation

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Data/MXRoomState.m
- MatrixSDK/Data/MXUser.m
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
By default Matrix SDK sets an identicon url when user's avatar is undefined
(see [MXRestClient urlOfIdenticon:] use).
We define here a new property named 'disableIdenticonUseForUserAvatar' to disable identicon use at SDK level.
> MXSDKOption:  Configure identicon use at SDK level.

- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
This property is relevant only for events with 'kMXEventTypeStringReceipt' type.
Contains the event IDs for which a read receipt is defined in this event.
> MXEvent Add readReceiptEventIds property

- MatrixSDK/JSONModels/MXJSONModels.m
Skip Mantle use to convert MXPresenceEventContent in 1ms (instead of 190ms).
> MXJSONModels Improve performance

- MatrixSDK/Data/MXRoom.m
-> generate a read receipt for the sender of an incoming message
1 - Some clients don't send read receipt so it is a way to have read receipt
2 - The read receipts can be sent with delay so it avoids having a read receipt older than a message sent by an user.
> invalid_read_receipts

- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
We remove here the specific request used during catch-up sync v1 to handle separately the presence.
The presence are handled by the server sync v2 request when the event stream is resumed.
> Server sync v2 : Resume presence handling

- MatrixSDK.podspec
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/JSONModels/MXJSONModel.h
- MatrixSDK/JSONModels/MXJSONModel.m
- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/JSONModels/MXRoomPowerLevels.m
- MatrixSDK/NotificationCenter/MXNotificationCenter.m
- MatrixSDKTests/MXEventTests.m
- MatrixSDKTests/MXJSONModelTests.m
- Podfile
- Podfile.lock
In the continuation of https://matrix.org/jira/browse/SYIOS-169, Mantle has been totally removed.
The pro is that we have the best performance. 
The con is that we lost nice automatic conversion methods (dictionaryValue, NSCoding, NSCopying). These methods must be now coded by "hand" for each MXJSON derived class.
> Remove mantle

- README.rst
This pull requests corrects the spelling of **CocoaPods** 🤓
https://github.com/CocoaPods/shared_resources/tree/master/media
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">One day I’ll make a bot that looks through the READMEs of all Pods, looks to see if it uses “Cocoapods” and PRs “CocoaPods” :D</p>&mdash; Ørta (@orta) <a href="https://twitter.com/orta/status/697374357975388160">February 10, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
Created with [`cocoapods-readme`](https://github.com/dkhamsing/cocoapods-readme).
> Correct the spelling of CocoaPods in README

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.m
This PR replaces calls to v1 and v2_alpha apis by r0, which is configurable via MXRestClient.apiPathPrefix.
v1 global initialSync and related objects have been removed.
In step \#2, call of room initialSync will be removed as v2 /sync do the job. All comments relative to v1/v2 will also be removed
> Moving to r0 - Step #1

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/Store/MXCoreDataStore/MXCoreDataStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
- MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
- MatrixSDK/Data/Store/MXStore.h
- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
+ fix: MXRoom.unreadEvents and [MXStore unreadEvents::] should be removed #82
> BugFix SYIOS-202: IOS should no longer reset badge count on launch.

- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
There was a race condition. While the storing thread saves a read receipt, it may have just been replaced (and released) by a new incoming one managed by the UI thread.
It should fix this crash:
[2016-03-28 13:10:25 +0000]
-[__NSCFType encodeWithCoder:]: unrecognized selector sent to instance 0x13a75bb40
Application: Vector (im.vector.app)
Application version: 0.1.2 (r0)
Matrix SDK version: 0.6.4
Build: develop #551
iPhone 9.3
(
0   CoreFoundation                      0x0000000183db2e50 <redacted> + 148
1   libobjc.A.dylib                     0x0000000183417f80 objc_exception_throw + 56
2   CoreFoundation                      0x0000000183db9ccc <redacted> + 0
3   CoreFoundation                      0x0000000183db6c74 <redacted> + 872
4   CoreFoundation …
> Crash Fix: Fixed crash in [MXFileStore saveReceipts]

- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
https://github.com/vector-im/vector-ios/issues/247
> MXSession: Detect when the access token is no more valid

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Data/MXEventTimeline.h
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomState.h
- MatrixSDK/Data/MXRoomState.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MXEnumConstants.h
- MatrixSDK/MXEnumConstants.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXPeekingRoomTests.m
- MatrixSDKTests/MXRestClientTests.m
- MatrixSDKTests/MXRoomStateTests.m
- MatrixSDKTests/MXRoomTests.m
- MatrixSDKTests/MXSessionTests.m
- MatrixSDKTests/MXStoreTests.m
- MatrixSDKTests/MatrixSDKTestsData.m
SDK part for https://github.com/vector-im/vector-ios/issues/337
Added the ability to set and read:
- room visibility in the current VC's room directory
- room join rule
- room history visibility
- room guest access
2 API breaks:
- MXRoomVisibility has been replaced by MXRoomDirectoryVisibility
- MXRoomState.isPublic has been replaced by MXRoomState.isJoinRulePublic
> Add methods to change/read room settings to/from the hs

- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomState.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
Redacting membership events should immediately reset the displayname & avatar of room members.
> Vector 443

- MatrixSDK/Data/Store/MXFileStore/MXFileStore.h
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
https://github.com/vector-im/vector-ios/issues/376
> File store backup

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/Store/MXCoreDataStore/MXCoreDataRoom.h
- MatrixSDK/Data/Store/MXCoreDataStore/MXCoreDataStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.h
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
- MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
- MatrixSDK/Data/Store/MXStore.h
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MXSession.h
https://github.com/vector-im/vector-ios/issues/494
- Ignore members profile changes during last message handling.
> Bug Fix - Profile changes shouldn't reorder the room list

- MatrixSDK/VoIP/CallStack/Jingle/MXJingleCallStackCall.m
- MatrixSDK/VoIP/CallStack/MXCallStackCall.h
- MatrixSDK/VoIP/MXCall.h
- MatrixSDK/VoIP/MXCall.m
Let the Application handle the audio route. It is useful in case of headset use.
MXJingleCallStackCall: Run callbacks on the main thread.
> MXCallStackCall: Do not force the main speaker on video call.

- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
This prevents these "long" operations from being suspended while the app in background
> MXFileStore: Add a background task during load and commit phases

- MatrixSDK/Data/MXRoom.m
https://github.com/vector-im/vector-ios/issues/541
MXRoom: Update the oneself receipts only when it is required.
> Settings: Add 'mark all as read' option

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/Store/MXCoreDataStore/MXCoreDataStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
- MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
- MatrixSDK/Data/Store/MXStore.h
https://github.com/vector-im/vector-ios/issues/532
MXRoom Changes:
- Define 'localUnreadEventCount' property: The number of unread events wrote in the store.
- Add API [acknowledgeEvent:]: If the event was not acknowledged yet, this method acknowlegdes it by sending a receipt event. This will indicate to the homeserver that the user has read up to this event.
> Bug Fix - Chat screen: New message(s) notification

- MatrixSDK/VoIP/CallStack/Jingle/MXJingleCallStackCall.m
It fixes: When screen is locked, rotating the screen landscape makes local video preview go upside down https://github.com/vector-im/vector-ios/issues/519.
> MXJingleCallStackCall: Fix: Show the front camera self preview as a mirror

- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDK/VoIP/MXCall.m
even if the app goes in background
Make MXCall use it in order to fix "Locking phone whilst setting up a call interrupts the call setup" (https://github.com/vector-im/vector-ios/issues/552)
> MXSession: Add a mechanism to keep the event streams running

- MatrixSDK/Data/MXUser.h
- MatrixSDK/Data/MXUser.m
- MatrixSDK/MXSession.m
https://github.com/vector-im/vector-ios/issues/623
MXSession: In case of initialSync, mxsession.myUser.userId must be available before changing the state to MXSessionStateStoreDataReady.
> App crashes when we start a chat during initial sync

- MatrixSDK/Utils/MXHTTPClient.m
https://github.com/vector-im/vector-ios/issues/655
Cancel all the tasks currently run by the managed session when the background task expired (instead of invalidate the session).
> Bug Fix - App got stuck and permanently spinning.

- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDKTests/MXRestClientNoAuthAPITests.m
- MatrixSDKTests/MatrixSDKTestsData.m
which worked only with old CS auth API.
Add registerWithLoginType and loginWithLoginType which do the job with new CS auth api for dummy and password flows.
Tests have been updated.
> API break: MXRestClient: Remove registerWithUser and loginWithUser methods

- MatrixSDK/Data/MXEventTimeline.h
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDKTests/MXEventTests.m
- MatrixSDKTests/MXRestClientTests.m
> MXRestClient: Support the filter parameter during a messages request.

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
https://github.com/vector-im/vector-ios/issues/715
MXRestClient: support `m.direct` event in `account_data` at session level.
> Converting existing rooms to/from DMs

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
#149
When no direct chat is listed in account data, we synthesize them from the current heuristics of what counts as a 1:1 room.
> Feature - Support `m.direct` event in account_data

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
https://github.com/vector-im/vector-ios/issues/715
- Room creation: When the flag isDirect is turned on, only one user id is expected in the inviteArray. The room will be considered as direct only for the first mentioned user in case of several user ids.
> Feature - Converting existing rooms to/from DMs

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
Return the device information related to an encrypted event.
> MXRoom: add eventDeviceInfo API

- MatrixSDK/MXRestClient.m
The web client doesn't, and we shouldn't be making HTTP requests
to whatever server people put in messages
> Don't accept non-mxc URLs for content

- MatrixSDK/Crypto/Algorithms/MXDecryptionResult.h
- MatrixSDK/Crypto/Algorithms/MXDecryptionResult.m
- MatrixSDK/Crypto/MXOlmDevice.m
There is however an issue: it breaks permalinks or reloading events from a store.
The reason is that a permalink is opened in a separate window with its own timeline. And this timeline decodes events for a second time.
> Crypto: message-replay mitigation

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
This temporary event is automatically defined as `encrypted` when the room is encrypted and the encryption is enabled.
> MXRoom: Add API to create a temporary message event.

- MatrixSDK/Utils/MXTools.m
https://github.com/vector-im/vector-ios/issues/812
Fix user id regex according to https://matrix.org/docs/spec/intro.html#user-identifiers
> BF: Cannot invite user with dash in their user id 

- MatrixSDK/Crypto/Algorithms/MXEncrypting.h
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDKTests/MXCryptoTests.m
Instead of trying to maintain a list of devices we need to share with, just check all the devices for all the users on each send.
Port of https://github.com/matrix-org/matrix-js-sdk/pull/295
> E2E: Check devices to share keys with on each send

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
[sendMessageOfType:content:success:failure:] is replaced with [sendMessageWithContent:success:failure:] where the message type is defined in the provided content.
> API break - MXRoom:`sendMessageOfType` is deprecated.

- MatrixSDK/MXSession.m
*** -[__NSDictionaryM removeObjectForKey:]: key cannot be nil
Main thread: YES
(
0   CoreFoundation                      0x00000001849371d0 <redacted> + 148
1   libobjc.A.dylib                     0x000000018336c55c objc_exception_throw + 56
2   CoreFoundation                      0x00000001848347a4 <redacted> + 692
3   Vector                              0x00000001002dc6b8 Vector + 2377400
-> -[MXMemoryStore storeUser:] (in Vector) (MXMemoryStore.m:298)
4   Vector                              0x00000001002b34e0 Vector + 2208992
-> -[MXFileStore storeUser:] (in Vector) (MXFileStore.m:449)
5   Vector                              0x000000010030e244 Vector + 2581060
-> __61-[MXSession startWithMessagesLimit:onServerSyncDone:failure:]_block_invoke132 (in Vector) (MXSession.m:355)
6   Vector …
> Bug Fix - App crashes while the app stores user.

- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
- MatrixSDK/Crypto/Data/MXUsersDevicesMap.h
- MatrixSDK/Crypto/Data/MXUsersDevicesMap.m
- MatrixSDK/Crypto/Data/Store/MXFileCryptoStore/MXFileCryptoStore.m
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/MXCrypto.m
storeDevicesForUser is now 10 times faster.
The timing logs are supposed to be temporary.
I pause the storage optimisation. Now, there is more things to save by threading the whole crypto.
> Implement [MXCryptoRealmStore storeDevicesForUser]  correctly & add timing logs

- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDKTests/MXRestClientNoAuthAPITests.m
in order to make response blocks called from another thread than the main one.
The PR contains also these fixes:
- some apis did not do processing on the processing queue
- some apis did not do sanity checks on optional failure and success blocks
> MXRestClient: Add the completionQueue property

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/Algorithms/MXDecrypting.h
- MatrixSDK/Crypto/Algorithms/MXEncrypting.h
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
- MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
- MatrixSDK/Crypto/Algorithms/Olm/MXOlmEncryption.m
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCrypto_Private.h
- MatrixSDK/Crypto/MXOlmDevice.h
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXCryptoTests.m
Well, this modification actually makes the crypto code runs on a pool of threads because this is how dispatch_async works when running on a queue which is not the main one.
Well, the code actually uses 2 queues: a main one and another one dedicated to the decryption because we want to be able to read the room history while sending a message to the room (sending our 1st message in a room can take seconds).
I have also removed #ifdef MX_CRYPTO from code outside the crypto module. MXCrypto stubs public methods if MX_CRYPTO is not defined.
Note that message decryption still blocks UI but it is not noticeable for the end-user. Making it asynchronous requires too much refactoring. Plus this refactoring is on the same path than the event storage improvement.
> Add threading in crypto to avoid blocking UI

- MatrixSDK/Data/MXEventTimeline.m
https://github.com/vector-im/riot-ios/issues/894
Move the local echo suppression from `MXKRoomDataSource` to `MXEventTimeline` class.
> Bug Fix: Riot looks to me like I'm sending the same message twice.

- MatrixSDK/Crypto/MXOlmDevice.m
- Podfile
This should resolve #219, but it depends on a change in OLMKit that moves the `OLMKitVersionString` function to a class method. See here: 
https://github.com/aapierce0/OLMKit/tree/OLMKit-xcode-framework-compatibility
The only reason I haven't submitted this change to the olm repository is because this is *technically* a breaking change (albeit an incredibly small one). Here's the patch file, though: [olm_patch.txt](https://github.com/matrix-org/matrix-ios-sdk/files/712987/olm_patch.txt)
Signed-off-by: Avery Pierce <aapierce0@gmail.com>
> Xcode framework support

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
API break: kMXRoomLocalEventIdPrefix has been renamed to kMXEventLocalEventIdPrefix
> MXEvent: Add isLocalEvent property.

- MatrixSDK/MXSession.m
Logs:
[MXCrypto] checkCryptoWithMatrixSession for (null)
[MXCrypto] Create dispatch queue for (null)'s crypto
Crash log:
Main thread: YES
(
0   CoreFoundation                      0x000000018acfd1d0 <redacted> + 148
1   libobjc.A.dylib                     0x000000018973455c objc_exception_throw + 56
2   CoreFoundation                      0x000000018abdda0c <redacted> + 0
3   Vector                              0x00000001002a3060 Vector + 2125920
-> +[MXCrypto dispatchQueueForUser:] (in Vector) (MXCrypto.m:1225)
4   Vector                              0x000000010029c004 Vector + 2097156
-> +[MXCrypto checkCryptoWithMatrixSession:complete:] (in Vector) (MXCrypto.m:100)
5   Vector                              0x0000000100332da4 Vector + 2715044
-> __38-[MXSession …
> Bug Fix: App crash on "setObjectForKey: key cannot be nil"

- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/Utils/MXHTTPClient.m
This will just save hundreds of MB of the app usage.
> Improve disk usage: Do not use NSURLCache. The SDK does not need this cache

- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXHTTPClient.h
- MatrixSDK/Utils/MXHTTPClient.m
- MatrixSDK/Utils/MXHTTPOperation.h
- MatrixSDK/Utils/MXHTTPOperation.m
- MatrixSDKTests/MXHTTPClientTests.m
#245.
We keep a gitter as discussed here: https://matrix.to/#/!HCXfdvrfksxuYnIFiJ:matrix.org/$1487167061111kLtnV:jki.re
> Http retry policy

- MatrixSDK/Utils/MXAllowedCertificates.h
- MatrixSDK/Utils/MXAllowedCertificates.m
- MatrixSDK/Utils/MXHTTPClient.m
- MatrixSDK/Utils/Media/MXMediaLoader.m
- MatrixSDKTests/MXSelfSignedHomeserverTests.m
Plus:
- improve the SSL error handling. Previously, requests silently died. Now, they call their failure block.
- add more tests
> Self-signed homeserver: Fix regression on media hosted by server with CA certificate

- MatrixSDK/Crypto/Algorithms/MXEncrypting.h
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
- MatrixSDK/Crypto/Algorithms/Olm/MXOlmEncryption.m
- MatrixSDK/Crypto/MXCrypto.m
iOS equivalent of matrix-org/matrix-js-sdk#303 
Basically, we download the devices before checking the same outbound session can be reused.
> New session after blacklist

- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCrypto_Private.h
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXCryptoTests.m
Equivalent of https://github.com/matrix-org/matrix-js-sdk/pull/376.
With some differences / improvements due to the ios sdk behaviour:
- MXSession does a loop of /sync requests until catching up is done. This ensures that we start crypto in the right condition
- Upload OTK before sending the to-device announcement.
> Delay otk generation

- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/MXCrypto.m
Fix race conditions by doing the retry is the same threads conditions as [MXCrypto decryptEvent].
The retry is done in 2 cases:
- a late room key
- after keys import
> BF: e2e: Sometimes some events are not decrypted when importing keys #261

- MatrixSDK/Crypto/Data/MXDeviceList.m
#264
Fix the loop by ignoring failed devices like matrix-js-sdk
> BF: [e2e] Tight loop of /keys/query requests

- MatrixSDK/Crypto/Algorithms/MXEncrypting.h
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
- MatrixSDK/Crypto/Algorithms/Olm/MXOlmEncryption.m
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/VoIP/MXCall.m
Check encryption before making the call stack answering.
This ensures that ICE candidates events are correctly encrypted and sent. This is useful atm in the case of unknown devices because it requires end user interactions.
This will help to solve vector-im/riot-ios#1058
> VoIP: ensure e2e is ready in the room before answering a call

- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- MatrixSDK/Utils/Media/MXMediaManager.h
- MatrixSDK/Utils/Media/MXMediaManager.m
This value depends on the version defined at the application level (see [MXSDKOptions mediaCacheAppVersion]), and the one defined at SDK level.
> MXMediaManager: Expose the media cache version

- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDKTests/MXRestClientNoAuthAPITests.m
- MatrixSDKTests/MXSelfSignedHomeserverTests.m
This is an API break because pagination is highly advised to save homeserver resources.
> MXRestClient: Update publicRooms to support pagination and 3rd party networks

- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
The keys in the returned dict were wrong. Note that it did not affect the crypto module behavior as long as these keys were consistent.
It only fixes debug logs.
> MXRealmCryptoStore: Fix implementation of sessionsWithDevice.

- MatrixSDK/Crypto/Data/MXDeviceList.h
- MatrixSDK/Crypto/Data/MXDeviceList.m
- MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
- MatrixSDK/Crypto/Data/Store/MXFileCryptoStore/MXFileCryptoStore.m
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCrypto_Private.h
- MatrixSDKTests/MXCryptoTests.m
Equivalent to https://github.com/matrix-org/matrix-js-sdk/pull/425.
> Crypto: Rework device list tracking logic

- MatrixSDK/Crypto/Data/MXDeviceList.m
Don't consider device lists up-to-date when we have another request for the
relevant user in the queue.
Port of https://github.com/matrix-org/matrix-js-sdk/pull/431
> Crypto: Fix race in device list updates

- MatrixSDK/VoIP/CallStack/Jingle/MXJingleCallStack.h
- MatrixSDK/VoIP/CallStack/Jingle/MXJingleCallStack.m
- MatrixSDK/VoIP/CallStack/Jingle/MXJingleCallStackCall.h
- MatrixSDK/VoIP/CallStack/Jingle/MXJingleCallStackCall.m
- MatrixSDK/VoIP/CallStack/Jingle/MXJingleVideoView.h
- MatrixSDK/VoIP/CallStack/MXCallStack.h
- MatrixSDK/VoIP/CallStack/MXCallStackCall.h
- MatrixSDK/VoIP/MXCall.h
- MatrixSDK/VoIP/MXCall.m
- MatrixSDK/VoIP/MXCallManager.h
- MatrixSDK/VoIP/MXCallManager.m
In this PR i provide several improvements:
* Add nullability annotations. This makes code more self-documented and also provides a better interoperability with Swift
* Mark some initializers as designated
* Use forward declaration
* Adopt generics for Foundation collection types
* Use `NS_ENUM` macro instead of C `enum` for MXCallState. We can specify underlying type for our enumeration, it is translated into Swift's enums, compiler informs about uncovered values in `switch` statement and assigning to type different from the underlying one.
* Fix issue in `MXCallManager` with `refreshTURNServer` method
* Fix issue in `MXCall` connected with `retainPreventPause` of `MXSession`
* Fix issue in `MXCall` connected with retain cycle between `MXCall` instance and it's property `callStackCall`. I …
> Improvements in VoIP-related classes

- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/Utils/MXHTTPClient.h
- MatrixSDK/Utils/MXHTTPClient.m
AFSecurityPolicy try to retrieve certificate in the AFNetworking Bundle
However, with Cocoapods 1.0 the pod bundle is not equal to the app
Bundle. So certificates are not retrieved
> Allow App to use custom certificate

- MatrixSDK/Crypto/Data/Store/MXFileCryptoStore/MXFileCryptoStore.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXHTTPClient.m
This finalises the work done in https://github.com/matrix-org/matrix-ios-sdk/pull/296.
It makes pod validation for mac happy again on Jenkins.
> UIBackgroundTaskIdentifier: Replace it by MXBackgroundModeHandler *everywhere*

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/VoIP/CallKit/MXCallKitAdapter.h
- MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m
- MatrixSDK/VoIP/CallKit/MXCallKitConfiguration.h
- MatrixSDK/VoIP/CallKit/MXCallKitConfiguration.m
- MatrixSDK/VoIP/CallStack/Jingle/MXJingleCallAudioSessionConfigurator.h
- MatrixSDK/VoIP/CallStack/Jingle/MXJingleCallAudioSessionConfigurator.m
- MatrixSDK/VoIP/CallStack/MXCallAudioSessionConfigurator.h
- MatrixSDK/VoIP/MXCallManager.h
- MatrixSDK/VoIP/MXCallManager.m
`MXCallKitAdapter` is an entity through which we interact with CallKit API
The most interesting part is `MXJingleCallAudioSessionConfigurator`. There is no public API in WebRTC iOS SDK to configure `AVAudioSession`, it is only internal. CallKit has its own rules for where and when we need to configure and activate AVAudioSession. We need to configure AVAudioSession when `provider:performStartCallAction:` is called and in completion block of `reportNewIncomingCallWithUUID:update:completion`. So i decide to extract configuration values from WebRTC iOS SDK and put them into class called `MXJingleCallAudioSessionConfigurator`. So with it help we can configure `AVAudioSession` like it does WebRTC internally. Here is the WebRTC [sources](https://chromium.googlesource.com/external/webrtc/+/master …
> CallKit support

- MatrixSDK/MXSession.m
I encountered an issue in my client project where the `-[MXSession start:failure:]` method would not call the failure block if the token was invalid.
signed-off-by: Avery Pierce <aapierce0@gmail.com>
> MXSession unknown token failure callback

- MatrixSDK/Contrib/Swift/Data/MX3PID.swift
- MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
- MatrixSDK/Contrib/Swift/JSONModels/MXJSONModels.swift
- MatrixSDK/Contrib/Swift/MXEnumConstants.swift
I encountered a couple cases where I needed to access the raw constants of some enums (such as MXEventType). The `identifier` property on these swift enums returns the raw value (typically a String), but the access level of that property defaults to `internal`, so getting to those constants in my client project was difficult.
This PR declares those identifiers as `public`, so they're easily accessible in a client project.
signed-off-by: Avery Pierce <aapierce0@gmail.com>
> SwiftMatrixSDK: Update the access control for the identifier property on some swift enums

- MatrixSDK/Utils/Media/MXMediaLoader.m
Avatars do not display with matrix.org account after trusting a self-signed certificate.
Fix: reenable trusting anchor certificates in addition to those passed in via the SecTrustSetAnchorCertificates API.
https://github.com/vector-im/riot-ios/issues/816
> Bug Fix: Avatars do not display with account on a self-signed server

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Contrib/Swift/JSONModels/MXRoomPowerLevels.swift
- MatrixSDK/JSONModels/MXRoomPowerLevels.h
Uses the Swift enum `MXEventType` instead of the raw `MXEventTypeString` when getting the minimum level.
> SwiftMatrixSDK: Add Swift refinements to MXRoomPowerLevels.

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Contrib/Swift/Data/MXRoomState.swift
- MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
- MatrixSDK/Data/MXRoomState.h
- MatrixSDK/JSONModels/MXEvent.h
Brings swift-refined types (`MXRoomHistoryVisibility`, `MXRoomJoinRule`, `MXRoomGuestAccess`, and `MXEventType`) to `MXRoomState`
Signed-off-by: Avery Pierce <aapierce0@gmail.com>
> SwiftMatrixSDK: Add swift refinements to MXRoomState

- MatrixSDK/Contrib/Swift/Data/MXRoomState.swift
- MatrixSDK/Data/MXRoomState.h
- MatrixSDK/Data/MXRoomState.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
We can have several state events of the same type, like memberships. Note that memberships worked because they were stored in a separate dict.
The impact on performance and storage size should be limited because, compared to membership events, other state events are a small number.
> API break: Replace [MXRoomState stateEventWithType:] by [MXRoomState stateEventsWithType:]

- MatrixSDK/Data/MXRoomState.m
This improves the code in 2 ways:
- speed: the loop in the memberName method took 4ms per member in a room like MatrixHQ. As there is a lot of membership changes in this room, there was very often a reset on the cache, which made it a bit useless.
- more robust against race condition: MatrixKit calls the memberName method on one of its processing queue. The new implementation of memberName does only read operations on ivars which is less risky than the write to `membersNamesCache` it did before. It should fix https://github.com/matrix-org/riot-ios-rageshakes/issues/132 (App crashed I don't know why, suspect memory issues / Crash in [MXRoomState copyWithZone:])
> MXRoomState: Improve algorithm to manage room members displaynames disambiguation

- MatrixSDK/VoIP/MXCall.m
Route to speaker every video call by default. See [#933](https://github.com/vector-im/riot-ios/issues/933)
> Fix issue #933

- MatrixSDK/VoIP/CallStack/Jingle/MXJingleCallStackCall.m
The problem was described in [#1471](https://github.com/vector-im/riot-ios/issues/1471)
> turning on the loudspeaker before the call gets accepted enables it in the UI, but won't enable it afterwards. In fact, it's one more step to turn it on after the call gets accepted (need to turn it off first and then back on again)
> Prevent override of user selected output port by WebRTC

- MatrixSDK/MXSession.m
This should improve network and battery usage.
When resuming, if several /syncs are required to accomplish the catching up, the code was launching several parallel loops of [self serverSyncWithServerTimeout:...] calls, ie several parallel event streams :/
> MXSession: Fix parallel /sync requests streams.

- MatrixSDK/Data/MXRoomState.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MXRoomState copy: a deep copy of each state events array is necessary.
Force file store refresh.
https://github.com/vector-im/riot-ios/issues/1494
> Bug Fix - Room settings: the displayed room access settings is wrong

- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
Remove useless code. This has an impact on perf when scrolling room history
> MXMemoryStore: improve getEventReceipts implementation.

- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
The device display name is now provided by the Riot application.
Related to `Device name leaks personal information` https://github.com/vector-im/riot-ios/issues/910
> MXRestClient: Improve registration parameters handling.

- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
This flag indicating whether the initial sync has been done.
> MXSession: Add `isEventStreamInitialised` flag

- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
The GH diff is not visually helpful at first. The change only consists in the use of a new method called `decryptEventFromCryptoThread` that does not require a `dispatch_async ... dispatch_sync` nasty thing.
Retrying happens when we receive the key afterwards because of a late room key or because another user's device answers to our key share request.
In that case, as we are already in an asynchronously case, we do not need to come back to and block the main thread to decrypt the event as opposed to https://github.com/matrix-org/matrix-ios-sdk/issues/205.
> Crypto: Do not block the main thread when retrying the decryption of an event

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Data/MXGroup.h
- MatrixSDK/Data/MXGroup.m
- MatrixSDK/Data/MXRoomMember.h
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.h
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.h
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
- MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
- MatrixSDK/Data/Store/MXStore.h
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MXEnumConstants.h
- MatrixSDK/MXEnumConstants.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDK/MatrixSDK.h
- MatrixSDK/Utils/MXTools.h
- MatrixSDK/Utils/MXTools.m
- Handle the list of the groups from the server sync response.
https://github.com/vector-im/riot-meta/issues/114
> Groups: self-management of membership of groups

- MatrixSDK/Utils/MXTools.h
- MatrixSDK/Utils/MXTools.m
Check whether a string is formatted as a matrix group identifier.
> MXTools - Groups: add `isMatrixGroupIdentifier` method.

- SwiftMatrixSDK.podspec
Bumped `SwiftMatrixSDK.podspec` dependency to `GZIP 1.2.1`. 
Signed-off-by: Nick Rakochy <nick.rakochy@gmail.com>
> GZIP 1.2.1

- MatrixSDK/Utils/Media/MXMediaLoader.m
Hi,
This PR handles client certificate case performing the default handling. It also cancels the challenge if the case is not managed. Indeed, according to https://developer.apple.com/documentation/foundation/nsurlconnectiondelegate/1414078-connection?language=objc : 
> In this method, you must invoke one of the challenge-responder methods.
It was not managed before.
It is related to issue #446. It is also quoted in https://github.com/vector-im/riot-ios/issues/1634
Next step would be to support the import of certificate to answer properly to client certificate challenge (https://developer.apple.com/library/content/qa/qa1745/_index.html / https://chika-kasymov.github.io/authentication_with_client_private_certificate_using_afnetworking).
Thanks
> MXMediaLoader: handles client certificate case

- MatrixSDK.podspec
- MatrixSDK/MXSDKOptions.h
- README.rst
- SwiftMatrixSDK.podspec
There is no more the `pod 'OLMKit'` technique for the app to enable it because it does not work with frameworks
> Crypto: The crypto is now built by default in matrix-ios-sdk.

- MatrixSDK/Crypto/MXCrypto.m
(https://github.com/matrix-org/riot-ios-rageshakes/issues/866)
Add sanity checks on [MXCrypto ensureOlmSessionsForDevices:]
> Crypto: Fix crash when sharing keys on broken network

- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
MXRestClient: Add the method to get the publicised groups for a list of users.
MXSession: Cache the publicised groups of the matrix users in order to limit the server requests.
https://github.com/vector-im/riot-meta/issues/118
> Groups: Display flair for users in room history.

- MatrixSDK/Utils/MXTools.m
as described at https://matrix.org/speculator/spec/HEAD/appendices.html#historical-user-ids.
This is the iOS equivalent change to https://github.com/matrix-org/matrix-android-sdk/commit/cbc449c2f87ef3d1be8aa3adee0695a06d3c2831.
> MXTools: Make isMatrixUserIdentifier support historical user ids

- MatrixSDK/MXSession.m
https://github.com/vector-im/riot-ios/issues/1757
Make sure MXSession go in MXSessionStatePaused when [MXSesssion releasePreventPause] is called.
Thus, the background sync can be relaunched to manage next push notifications.
> Push: Missing push notifications after answering a call

- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
because they return local values that may be out of sync.
The downloadKeys method is preferred for better accuracy.
Using downloadKeys will fix https://github.com/vector-im/riot-ios/issues/1782.
> API break: MXCrypto: Remove deviceWithDeviceId and devicesForUser methods

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
https://github.com/vector-im/riot-ios/issues/1731
Use the local event id as the transaction id so that we will reuse the same transaction id if the user hits resend.
>  BF: we should retry messages with same txn id when hitting 'resend'

- MatrixSDK/Contrib/Swift/MXResponse.swift
This is required because of this change in Swift 4:
https://github.com/apple/swift-evolution/blob/master/proposals/0029-remove-implicit-tuple-splat.md
> Fix issue #393

- MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
- MatrixSDK/Contrib/Swift/JSONModels/MXJSONModels.swift
There were a couple of enums in the Swift SDK that either had the wrong access control on their "identifier" properties and/or were missing an init(identifier: T) function.
I attempted to match the existing style in the other enums as best possible.
Signed-off-by: John Flanagan <john.flanagan@spok.com>
> SwiftMatrixSDK: Enum cleanup

- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/MXRoomSummaryTests.m
- MatrixSDKTests/MXSessionTests.m
- MatrixSDKTests/MXStoreTests.m
- MatrixSDKTests/MatrixSDKTestsE2EData.m
so that an observer will not continue to listen if its test is finished (passed or failed).
> Tests: Make sure we remove all NotificationCenter observers

- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
in case there is no `backgroundModeHandler` which happens in tests and on MacOS.
Regression made by #436.
Revealed by the `testDoNotStoreDecryptedData` test.
> MXFileStore: commits can stay pending after [MXFileStore close]

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Utils/MXHTTPOperation.m
if there is only one in the message sending queue
Regression made by #378.
Revealed by the `testFailedOutgoingMessageEcho` test.
> MXRoom: Canceled message can be sent

- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXToolsTests.m
This will fix SDK tests that fail since #453 because user ids have a port ("@bob:localhost:8480").
> MXTools: Fix the regex part for the HS domain part in all isMatrixXxxxIdentifier methods

- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDKTests/MXNotificationCenterTests.m
- MatrixSDKTests/MXStoreTests.m
Part of the https://github.com/vector-im/riot-ios/issues/1797 epic.
When there is no eventStremToken in this MXFileStore metadata, the MXFileStore is reset on the next start, requiring a full initial sync :/
This happened when there are more 2 pending commits. the dispatch saving the copy of the MXFileStoreMetaData data was skipped and the copied data was lost.
As other component in MXFileStore, do not do copy but reuse the same instance.
Found with the checkRoomAccountDataTags test.
> MXFileStore: BF: The MXFileStore metadata can be not stored in files.

- MatrixSDK/Data/MXRoomSummary.m
https://github.com/vector-im/riot-ios/issues/1822
> BF: Room summary is not updated after redaction of the room display name

- MatrixSDK.podspec
because the WebRTC framework requires it.
https://github.com/vector-im/riot-ios/issues/1821
> MatrixSDK/JingleCallStack: Upgrade the minimal iOS version to 9.0

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
https://github.com/vector-im/riot-ios/issues/1860
> Send Stickers: Manage local echo for sticker

- MatrixSDK/MXSession.m
in case the HS returns an empty response for `/publicised_groups`
Fixes https://github.com/vector-im/riot-ios/issues/1869: RoomVC: messages with link blink forever
> BF: Avoid flair to make requests in loop

- MatrixSDK/Utils/MXHTTPClient.m
Create NSError from MXError when catching M_CONSENT_NOT_GIVEN error in MXHTTPClient
> MXHTTPClient: Improve M_CONSENT_NOT_GIVEN error catching

- MatrixSDK/Crypto/MXCrypto.m
This is the reason why some tests of MXCryptoTests randomly fail.
> MXCrypto: Fix code that went into a dead-end

- MatrixSDK/MXRestClient.m
vector-im/riot-ios#1898
and kill all "Block implicitly retains self" warnings.
> MXRestClient: Factorise processing and completion blocks handling

- CHANGES.rst
- MatrixSDK/Crypto/KeySharing/Data/MXOutgoingRoomKeyRequest.h
- MatrixSDK/Crypto/KeySharing/MXOutgoingRoomKeyRequestManager.h
- MatrixSDK/Crypto/KeySharing/MXOutgoingRoomKeyRequestManager.m
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
for the megolm session used to encrypt an event
https://github.com/vector-im/riot-ios/issues/1879
> MXCrypto: Add reRequestRoomKeyForEvent to rerequest encryption keys

- MatrixSDK/Utils/MXHTTPClient.m
- MatrixSDKTests/MXAccountDataTests.m
- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/MXEventTests.m
- MatrixSDKTests/MXEventTimelineTests.m
- MatrixSDKTests/MXJSONModelTests.m
- MatrixSDKTests/MXMyUserTests.m
- MatrixSDKTests/MXNotificationCenterTests.m
- MatrixSDKTests/MXPeekingRoomTests.m
- MatrixSDKTests/MXRestClientNoAuthAPITests.m
- MatrixSDKTests/MXRestClientTests.m
- MatrixSDKTests/MXRoomMemberTests.m
- MatrixSDKTests/MXRoomStateDynamicTests.m
- MatrixSDKTests/MXRoomStateTests.m
- MatrixSDKTests/MXRoomSummaryTests.m
- MatrixSDKTests/MXRoomTests.m
- MatrixSDKTests/MXSelfSignedHomeserverTests.m
- MatrixSDKTests/MXSessionTests.m
- MatrixSDKTests/MXStoreTests.m
- MatrixSDKTests/MXUserTests.m
- MatrixSDKTests/MXVoIPTests.m
- MatrixSDKTests/MatrixSDKTestsData.h
- MatrixSDKTests/MatrixSDKTestsData.m
To make them run again since last changes with MXWeakify/MXStrongify.
I removed `[MatrixSDKTestsData closeMXSession]` that was used years ago to clean synapse db from the client side  This is no more required since Synapse performance is much better today.
> Tests: Keep refs in tests

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXSession.m
when the current direct chat dictionary is empty on server sync
This mechanism (named "background compatibility heuristic") may introduce wrong direct chats, and it is not relevant anymore
> Remove the automatic direct chats definition

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomMembers.h
- MatrixSDK/Data/MXRoomMembers.m
- MatrixSDK/Data/MXRoomState.h
- MatrixSDK/Data/MXRoomState.m
- MatrixSDK/NotificationCenter/Checker/MXPushRuleRoomMemberCountConditionChecker.m
- MatrixSDK/VoIP/MXCall.m
- MatrixSDK/VoIP/MXCallManager.m
- MatrixSDKTests/MXPeekingRoomTests.m
- MatrixSDKTests/MXRoomStateDynamicTests.m
- MatrixSDKTests/MXRoomStateTests.m
- MatrixSDKTests/MXRoomTests.m
- MatrixSDKTests/MXSessionTests.m
- MatrixSDKTests/MXUserTests.m
Part 1: Move methods into a dedicated class, MXRoomMembers.
https://github.com/vector-im/riot-ios/issues/1931
>  MXRoomState: Decouple room members from room state

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Contrib/Swift/Data/MXRoom.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXSendReplyEventDefaultStringLocalizations.h
- MatrixSDK/Data/MXSendReplyEventDefaultStringLocalizations.m
- MatrixSDK/Data/MXSendReplyEventStringsLocalizable.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/Utils/MXTools.h
- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/MXRoomTests.m
Implement reply to an event with text message.
https://github.com/vector-im/riot-ios/issues/1911
> Replies: Implement sending

- CHANGES.rst
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDKTests/MXLazyLoadingTests.m
- MatrixSDKTests/MXRestClientTests.m
That does not work yet as expected on server side but the client is ready
I have also added one test on search.
Still part of https://github.com/vector-im/riot-ios/issues/1931.
> Enable lazy-loading for timelines on permalinks

- CHANGES.rst
- MatrixSDK/Data/MXEventTimeline.m
vector-im/riot-ios/issues/1918
Remove a line introduced in #430 which is the root of this regression.
> Fix: Sends read receipts on login

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDKTests/MXRestClientTests.m
- MatrixSDKTests/MXRoomStateTests.m
- MatrixSDKTests/MXRoomSummaryTests.m
- MatrixSDKTests/MXSessionTests.m
- MatrixSDKTests/MXStoreTests.m
- MatrixSDKTests/MXUserTests.m
There was some regressions, some old, some because of LL. Some tests implementation needed to be reworked.
> Make all SDK tests pass again

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Contrib/Swift/MXSession.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDKTests/DirectRoomTests.m
- MatrixSDKTests/MXAccountDataTests.m
- MatrixSDKTests/MXFilterTests.m
- MatrixSDKTests/MXLazyLoadingTests.m
The main target was to fix https://github.com/vector-im/riot-ios/issues/1983, where the rooms sync data was parsed before parsing the direct rooms data contained in the user account data. This has been fixed in this [commit](https://github.com/matrix-org/matrix-ios-sdk/commit/2496e23d8ca9b88f6b1322f7b176eee4bbd08f30).
Other commits are preparations to:
-  have a single point of storage for direct rooms (MXSession.directRooms) to avoid inconsistent data. 
- make a single update of direct rooms at a time to avoid race conditions.
> Direct rooms: Fix possible race conditions

- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
Use this method to run or queue any other actions on the direct rooms to avoid race conditions.
Run only one HTTP request in a block. If there is a pending action, the change will be applied on the updated direct rooms data.
> MXSession: expose `[runOrQueueDirectRoomOperation:]`

- MatrixSDK/MXError.m
Fix Giom's remark in https://github.com/matrix-org/matrix-ios-sdk/pull/548
> BF: MXError lost NSError.userInfo information.

- CHANGES.rst
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
to manage homeserver resource quota on /sync requests
Point 3 of of vector-im/riot-ios#1937
> MXSession: Add MXSessionStateSyncError state and MXSession.syncError 

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/JSONModels/MXMatrixVersions.h
- MatrixSDK/JSONModels/MXMatrixVersions.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXRestClientNoAuthAPITests.m
to get versions of the specification supported by the homeserver.
Needed for https://github.com/vector-im/riot-ios/issues/1931.
> MXSession: Add the supportedMatrixVersions method

- MatrixSDK.podspec
- fastlane/Fastfile
To make MatrixSDK pod lint works with Swift code we have to remove dependency to static libraries. So remove GoogleAnalytics subspec.
For the moment, to use Google Analytics, a developper have to add "MatrixSDKExtensions/MXAnalyticsDelegate/GoogleAnalytics/**/*.{h,m}" files directly to his project and add 'GoogleAnalytics' pod to his podfile.
> Add SwiftSupport subspec (again) to MatrixSDK in order to expose Swift refinements to a Swift/ObjC project

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXHTTPClient.m
- MatrixSDK/Utils/MXHTTPClient_Private.h
- MatrixSDKTests/MXLazyLoadingTests.m
- MatrixSDKTests/MXRestClientNoAuthAPITests.m
https://github.com/vector-im/riot-ios/issues/1931
This PR contains also some changes in MXHTTPClient that allow to add delays in http requests response for testing. I am not happy about how it is intrusive but there is no quick solution for that.
> Lazy-loading: MXRoom: Avoid race condition with the /members request

- MatrixSDK/Data/MXRoomSummary.m
Fix a regression introduced by https://github.com/matrix-org/matrix-ios-sdk/pull/563
MXRoomSummary unfortunately still needs a reference to the store to read other data.
> BF: Rooms notifications counts and rooms order was wrong after restart

- CHANGES.rst
- MatrixSDK/Data/MXRoomSummaryUpdater.m
Part of https://github.com/vector-im/riot-ios/issues/1931
Commits can be reviewed one by one.
> MXRoomSummary: Compute avatars for rooms that do not have one

- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDK/Data/MXRoomSummaryUpdater.m
With this PR, computations of name, avatar and members count use the same code if matrix room summary is available or not, which depends on LL activation.
Even invitations share now the same code too.
Along development, there was some update in the spec. The goal is to have same room names in Riot as before. You can see spec updates in comments updates along commits.
Commits can be reviewed one by one.
Should fix unexpected empty rooms (https://github.com/vector-im/riot-ios/issues/2020).
> Room summary computation: Use the matrix room summaries algo even if LL is off

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDKTests/MXRoomSummaryTests.m
- Podfile
- Podfile.lock
- SwiftMatrixSDK.podspec
Fixes vector-im/riot-ios/issues/2010
This PR comes with some maintenance on the SDK. Check commit one by one.
I was not able to make synapse send such event but at least the code now matches the matrix CS API described in the issue.
Here is what I got when invited by email from a user from another HS that did not know me:
> MXEvent: Move `invite_room_state` to the correct place in the client-server API

- CHANGES.rst
- MatrixSDK/Data/MXRoomSummaryUpdater.m
The only consequence was that we updated the avatar too often
> MXRoomSummaryUpdater: Fix minor issue in updateSummaryAvatar method

- CHANGES.rst
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXLazyLoadingTests.m
closes vector-im/riot-ios/issues/2082
> BF: Left room is still displayed as "Empty room" in rooms list

- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
The antivirus url is null by default.
Set a non null url to configure the antivirus scanner.
This url is applied to the current rest client to enable the antivirus server API use.
> MXSession: configure antivirus scanner use.

- MatrixSDK/Contrib/Swift/Data/MX3PID.swift
... because automatically generated ones will stay package internal and therefore render `MXRestClient.swift#lookup3PIDs` unusable.
> Add explicit public initializer to MX3PID struct

- CHANGES.rst
- MatrixSDK/MXEnumConstants.m
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/Media/MXMediaLoader.h
- MatrixSDK/Utils/Media/MXMediaLoader.m
- MatrixSDK/Utils/Media/MXMediaManager.h
- MatrixSDK/Utils/Media/MXMediaManager.m
This option is enabled by setting the new `antivirusServerURL` property
> MXMediaManager: Support the media download from a Matrix Content Scanner

- MatrixSDK/Data/MXRoomSummaryUpdater.m
- MatrixSDKTests/MXLazyLoadingTests.m
https://github.com/vector-im/riot-ios/issues/2020
This will not work every time but, at least, we now log the issue when it happens.
> Lazy loading: Try to mitigate unexpected "Empty room"

- CHANGES.rst
- MatrixSDK/Data/MXRoomSummary.m
Hi there,
After having upgraded our Matrix client app to use matrix-ios-sdk v0.11.5, we noticed that some rooms happen to lose their display name and avatar on a seemingly random basis.
I can see from PR #599 that you are also facing similar issues.
From user feedbacks, it appears that Direct chats are the most affected.
I could reproduce this problem with the latest Riot iOS client, so I guess v0.11.6 does not fix that.
Steps to reproduce :
- with Riot iOS client, create a Direct Chat with some user **Foo**
- kill Riot iOS app
- from another client (e.g the webclient), go to the **Foo** chat, and send ~25 messages (enough to trigger a `limited` sync)
- now open Riot iOS : "sometimes" (about half the time from my tests) you'll find that the **Foo** chat has been renamed **Empty room**, …
> Fix an occurence of null displayname issue

- CHANGES.rst
- MatrixSDK/Data/MXRoom.m
Indeed the list of the pending members requester(s) was not removed in case of failure. No new request could be triggered.
> Bug Fix - MXRoom: members methods don't respond after a failure

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/Data/MXOlmSession.h
- MatrixSDK/Crypto/Data/MXOlmSession.m
- MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/MXOlmDevice.m
fixes vector-im/riot-ios#2128.
> MXCrypto: Use the last olm session that got a message

- MatrixSDK/Utils/Media/MXMediaManager.m
Note: This change has been forgotten during https://github.com/matrix-org/matrix-ios-sdk/pull/598
> MXMediaManager - Thumbnail url: take into account the potential content scanner

- MatrixSDK/Contrib/Swift/Data/MXRoom.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- changelog.d/616.feature
As far as I could tell, there was no (easy) way to send an audio file (using msgType "m.audio").
Signed-off-by: N-Pex <npexdev@gmail.com>
> Add sendAudioFile to send files using msgType m.audio

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/Data/MXCryptoConstants.h
- MatrixSDK/Crypto/KeyBackup/Data/MXMegolmBackupAuthData.h
- MatrixSDK/Crypto/KeyBackup/Data/MXMegolmBackupAuthData.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackupPassword.h
- MatrixSDK/Crypto/KeyBackup/MXKeyBackupPassword.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDKTests/MXCryptoBackupTests.m
Fixes https://github.com/vector-im/riot-ios/issues/2127.
There is also an update in `restoreKeyBackup` so that it fails in case of bad recovery key (or password now) instead of succeeding with 0 keys imported.
> Key Backup: add passphrase support

- CHANGES.rst
- MatrixSDK/Crypto/KeyBackup/MXRecoveryKey.m
- MatrixSDKTests/MXCryptoBackupTests.m
> MXCrypto: Key backup: Ignore all whitespaces in recovery key

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/MXRestClient.m
- MatrixSDK/Utils/Categories/NSString+MatrixSDK.h
- MatrixSDK/Utils/Categories/NSString+MatrixSDK.m
> MXRestClient: Update CS API call to support event ids in room version 3

- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDKTests/MXCryptoBackupTests.m
This improves the previous behavior where we needed to have a **non empty** backup to determine if the recovery key was valid.
This PR comes with some factorisation and a small API break.
> Key backup: restoreKeyBackup methods now check if the recovery key is valid

- CHANGES.rst
- MatrixSDK/Crypto/Algorithms/MXDecrypting.h
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
- MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/KeySharing/MXOutgoingRoomKeyRequestManager.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXOlmDevice.h
- MatrixSDK/Crypto/MXOlmDevice.m
- MatrixSDKTests/MXCryptoBackupTests.m
Fixes https://github.com/vector-im/riot-ios/issues/2248
Before:
`[MXCrypto] importMegolmSessionDatas: Imported 5925 keys from 5925 provided keys in 698677ms`
After: 
`[MXCrypto] importMegolmSessionDatas: Imported 5954 keys from 5955 provided keys in 28534ms`
There is still room for improvement, specifically for the key backup recovery. 
`[alg didImportRoomKey:session];` triggers a load of key share request cancellation requests that takes 30s on my account. This delays the trust request made by that screen because the request is put at the end of the queue :/
> Crypto: Improve key import performance

- CHANGES.rst
- MatrixSDK/Crypto/Data/MXDeviceList.m
- MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup_Private.h
- MatrixSDK/Crypto/KeySharing/MXIncomingRoomKeyRequestManager.m
- MatrixSDK/Crypto/MXCrypto.m
Fixes https://github.com/vector-im/riot-ios/issues/2281.
Fixed by removing the dependency on MXCrypto.cryptoQueue that can become nil in some conditions.
>  Crypto: Fix crash in MXKeyBackup

- CHANGES.rst
- MatrixSDK/Utils/MXTools.m
Fixes vector-im/riot-ios/issues/2277
> BF: Escape room v3 event ids in permalinks

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
- MatrixSDK/Data/MXCredentials.h
- MatrixSDK/Data/MXCredentials.m
- MatrixSDK/Data/Store/MXStore.h
- MatrixSDK/JSONModels/AutoDiscovery/MXWellKnown.h
- MatrixSDK/JSONModels/AutoDiscovery/MXWellKnown.m
- MatrixSDK/JSONModels/AutoDiscovery/MXWellKnownBaseConfig.h
- MatrixSDK/JSONModels/AutoDiscovery/MXWellKnownBaseConfig.m
- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
MXCredentials is a new separate data model that allows to manage well-known data in one place.
The PR has these 2 main changes
* MXCredentials: Create a new data model for it, separated from the CS API response data model (new MXLoginResponse class).
* Login: Handle well-known data in the login response - MSC1730 (vector-im/riot-ios/issues/2298).
Other changes is about factorisation to use a central MXCredentials object.
> Login: Handle well-known data in the login response

- MatrixSDK/JSONModels/MXJSONModels.m
to track https://github.com/vector-im/riot-ios/issues/2264 and have better logs than:
```
2019-03-04 10:17:05.344 Riot[12486:3586757] [AppDelegate][Push] handleLocalNotificationsForAccount: eventsToNotify: (
{
"event_id" = "$xxxxxx:matrix.org";
"push_rule" = "<MXPushRule: 0x283439240>";
"room_id" = "!Iyuoiosad:matrix.org";
}
)
```
This PR gives:
```
(lldb) po rule
<MXPushRule: 0x6000036b0100> ruleId: .m.rule.contains_display_name - isDefault: 1 - enabled: 1 - actions: (
"<MXPushRuleAction: 0x600002e6d720> action: notify - parameters: (null)",
"<MXPushRuleAction: 0x600002e6d7c0> action: set_tweak - parameters: {\n    \"set_tweak\" = sound;\n    value = default;\n}",
"<MXPushRuleAction: 0x600002e6d900> action: set_tweak - parameters: {\n    \"set_tweak\" = highlight;\n}"
)
```
> Push notifications: Add description methods to MXPushRule & MXPushRuleAction

- CHANGES.rst
- MatrixSDK/MXRestClient.m
Fix file upload with filename containing whitespace
> [MXRestClient] URI encode filename when uploading a file

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackupPassword.h
- MatrixSDK/Crypto/MXOlmDevice.m
- MatrixSDKTests/MXCryptoBackupTests.m
- MatrixSDKTests/MXCryptoShareTests.m
- MatrixSDKTests/MatrixSDKTestsE2EData.h
- MatrixSDKTests/MatrixSDKTestsE2EData.m
Fixes vector-im/riot-ios/issues/2320
- don't cancel key requests if we can't decrypt everything in the session
- overwrite the session key if we get a better version
>  Crypto: Handle partially-shared sessions bette

- CHANGES.rst
- MatrixSDK/Data/MXRoomSummaryUpdater.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
Fix vector-im/riot-ios/issues/2148
> BF Riot: Room Upgrades: Room appears twice in the rooms list

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m
- MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStack.h
- MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.h
- MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m
- MatrixSDKExtensions/VoIP/Jingle/MXJingleCameraCaptureController.h
- MatrixSDKExtensions/VoIP/Jingle/MXJingleCameraCaptureController.m
- MatrixSDKExtensions/VoIP/Jingle/MXJingleVideoView.h
vector-im/riot-ios/issues/1483
> [JingleCallStack] Use WebRTC framework included in Jitsi Meet SDK

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Aggregations/Data/MXReactionCount.h
- MatrixSDK/Aggregations/Data/MXReactionCount.m
- MatrixSDK/Aggregations/Data/MXReactionCountChange.h
- MatrixSDK/Aggregations/Data/MXReactionCountChange.m
- MatrixSDK/Aggregations/Data/MXReactionCountChangeListener.h
- MatrixSDK/Aggregations/Data/MXReactionCountChangeListener.m
- MatrixSDK/Aggregations/Data/Store/MXAggregationsStore.h
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsMapper.h
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsMapper.m
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsStore.h
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsStore.m
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmReactionCount.h
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmReactionCount.m
- MatrixSDK/Aggregations/MXAggregations.h
- MatrixSDK/Aggregations/MXAggregations.m
- MatrixSDK/Aggregations/MXAggregations_Private.h
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/JSONModels/Event/MXEventUnsignedData.m
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXReactionTests.m
Part of https://github.com/vector-im/riot-ios/issues/2392
Add a store implemented in realm and a data update mechanism.
All tests now pass.
> Aggregations store

- MatrixSDK/Aggregations/MXAggregations.m
testAggregationsFromInitialSync happily fails now, which is a good sign.
This is a proof of the double counting issue at the spec level
> Aggregations: Fix reactionCountsFromMatrixStoreOnEvent

- MatrixSDK/Aggregations/Data/MXReactionCount.m
- MatrixSDK/Aggregations/Data/Store/MXAggregationsStore.h
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsStore.m
- MatrixSDK/Aggregations/MXAggregations.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
closes https://github.com/vector-im/riot-ios/issues/2456.
This is a hack similar to riot-web and riot-android but it comes as a fallback. So if the homeserver has aggregation API, we will not use it.
We can have plenty of reactions now:
> Reactions: Use a hack to compute count reactions based on relations ww know

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsStore.m
- MatrixSDK/Aggregations/MXAggregatedEditsUpdater.h
- MatrixSDK/Aggregations/MXAggregatedEditsUpdater.m
- MatrixSDK/Aggregations/MXAggregatedReactionsUpdater.h
- MatrixSDK/Aggregations/MXAggregatedReactionsUpdater.m
- MatrixSDK/Aggregations/MXAggregations.h
- MatrixSDK/Aggregations/MXAggregations.m
- MatrixSDK/Aggregations/MXAggregations_Private.h
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDKTests/MXAggregatedEditsTests.m
- MatrixSDKTests/MXAggregatedReactionTests.m
- MatrixSDKTests/MatrixSDKTestsData.h
- MatrixSDKTests/MatrixSDKTestsData.m
I started this branch to implement edits. I first made a refactor to let room for the edits part in MXAggregation but I got stucked in edits spec so I came back to reactions and fix some (maybe all) things.
This PR contains
- a new class `MXAggregatedReactionsUpdater` to handle storage and updates (and hack) for reaction
- the beginning of `MXAggregatedEditsUpdater`
- you can edit a message using `send_relation`
- fix for "Unreact can have no visual effect" (https://github.com/vector-im/riot-ios#2470)
- a patch while https://github.com/matrix-org/synapse/pull/5220 is not merged
- reactions on permalink (which fixes vector-im/riot-ios#2451)
- more tests on reactions (they all pass but see below)
- draft for tests for edits. I stopped writing them as I do not receive what I expect -> Need …
> Edits start -  reaction end

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Aggregations/Data/MXAggregatedReactions.h
- MatrixSDK/Aggregations/Data/MXAggregatedReactions.m
- MatrixSDK/Aggregations/Data/MXReactionCount.h
- MatrixSDK/Aggregations/Data/MXReactionCount.m
- MatrixSDK/Aggregations/Data/MXReactionCountChange.h
- MatrixSDK/Aggregations/Data/MXReactionOperation.h
- MatrixSDK/Aggregations/Data/MXReactionOperation.m
- MatrixSDK/Aggregations/MXAggregatedReactionsUpdater.h
- MatrixSDK/Aggregations/MXAggregatedReactionsUpdater.m
- MatrixSDK/Aggregations/MXAggregations.h
- MatrixSDK/Aggregations/MXAggregations.m
- MatrixSDKTests/MXAggregatedReactionTests.m
Fixes https://github.com/vector-im/riot-ios/issues/2453.
Local echoes and debouncing are managed internally in the reaction module to avoid "noise" in the timeline messages.
> Aggregation API: Local echo for reactions

- MatrixSDK/Aggregations/MXAggregatedEditsUpdater.h
- MatrixSDK/Aggregations/MXAggregatedEditsUpdater.m
- MatrixSDK/Aggregations/MXAggregations.h
- MatrixSDK/Aggregations/MXAggregations.m
- MatrixSDKTests/MXAggregatedEditsTests.m
Main use cases for https://github.com/vector-im/riot-ios/issues/2489.
> Edits: support local echo

- MatrixSDK/Aggregations/MXAggregatedEditsUpdater.m
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDKTests/MXAggregatedEditsTests.m
https://github.com/vector-im/riot-ios/issues/2449
This is compatible with the current implementation in Riot-Web but this code may change with the update of MSC1849.
Note that synapse does not support aggregation in e2e rooms yet. That means the app may not display edited content when opening a permalink.
> Edits: Support edits in e2e rooms

- MatrixSDK/MXSession.m
closes https://github.com/vector-im/riot-ios/issues/2516.
We must allow storing read receipts for reactions events too.
Else, the app cannot know where the last read receipt is. In this situation, it resets the receipt receipt on the last displayed message, which corrupts the unread count.
> BF: Reactions appear as "New messages"

- MatrixSDK/Aggregations/Data/MXReactionCount.h
- MatrixSDK/Aggregations/Data/MXReactionOperation.h
- MatrixSDK/Aggregations/Data/MXReactionRelation.h
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsMapper.m
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsStore.m
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmReactionCount.h
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmReactionRelation.h
- MatrixSDK/Aggregations/MXAggregatedReactionsUpdater.m
- MatrixSDK/Aggregations/MXAggregations.m
Fix vector-im/riot-ios/issues/2525
> BF Riot: Ordering of reactions is unpredictable

- CHANGES.rst
- MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsStore.m
- MatrixSDK/ContentScan/Data/Store/Realm/RealmProvider/MXScanRealmFileProvider.m
- MatrixSDK/ContentScan/Data/Store/Realm/RealmProvider/MXScanRealmInMemoryProvider.m
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
This avoids the trap described at https://medium.com/@chron.vas/handling-multiple-realm-databases-f50f1100cae1
> Storage: Isolate our realm DBs to avoid migration due to change in another realm

- MatrixSDK/Data/MXRoom.m
Closes https://github.com/vector-im/riot-ios/issues/2448
> Reactions: Send them in clear in e2e rooms for the moment

- CHANGES.rst
- MatrixSDK/Contrib/Swift/Data/MXRoom.swift
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/Contrib/Swift/MXSession.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXTools.h
- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXAggregatedReactionTests.m
- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/MXLazyLoadingTests.m
- MatrixSDKTests/MXRestClientTests.m
- MatrixSDKTests/MXRoomStateDynamicTests.m
- MatrixSDKTests/MXRoomStateTests.m
- MatrixSDKTests/MXRoomTests.m
- MatrixSDKTests/MXSessionTests.m
- MatrixSDKTests/MXStoreTests.m
- MatrixSDKTests/MatrixSDKTestsData.m
- MatrixSDKTests/MatrixSDKTestsE2EData.m
Part of vector-im/riot-ios/issues/2547 and https://github.com/vector-im/riot-ios/issues/2550
> Join Room: Support via parameters to better handle federation

- MatrixSDK/JSONModels/Aggregations/MXAggregationPaginatedResponse.h
- MatrixSDK/JSONModels/Aggregations/MXAggregationPaginatedResponse.m
- MatrixSDKTests/MXAggregatedEditsTests.m
https://github.com/vector-im/riot-ios/issues/2559
Tested against https://github.com/matrix-org/synapse/pull/5654.
> Edits history: Expose the new original event field

- CHANGES.rst
- MatrixSDK/Data/MXRoom.m
This PR fixes usage of random file names in the timeline:
> MXRoom: sendFile: Use the original file name by default

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/MXError.h
- MatrixSDK/MXError.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MatrixSDK.h
- MatrixSDK/NotificationCenter/ServiceTerms/MXServiceTerms.h
- MatrixSDK/NotificationCenter/ServiceTerms/MXServiceTerms.m
- MatrixSDK/NotificationCenter/ServiceTerms/MXServiceTermsRestClient.h
- MatrixSDK/NotificationCenter/ServiceTerms/MXServiceTermsRestClient.m
Part of vector-im/riot-ios#2600.
> MXServiceTerms: A class to support MSC2140 (Terms of Service API)

- CHANGES.rst
- MatrixSDK/Data/Filters/MXRoomEventFilter.h
- MatrixSDK/Data/Filters/MXRoomEventFilter.m
- MatrixSDK/Data/MXEventTimeline.h
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDKTests/MXEventTimelineTests.m
> MXEventTimeline: The roomEventFilter property is now writable

- CHANGES.rst
- MatrixSDK/JSONModels/MXMatrixVersions.h
- MatrixSDK/JSONModels/MXMatrixVersions.m
The 1st commit is an update for `supportLazyLoadMembers` implementation.
The 2nd commit will be useful for most of remaining policy features.
>  MXMatrixVersions: Add doesServerRequireIdentityServerParam and doesServerAcceptIdentityAccessToken

- CHANGES.rst
- MatrixSDK/Utils/MXHTTPClient.m
Useful on the auth screen of Riot.
You now instantly know when the entered custom HS is wrong.
> MXHTTPClient: Do not retry requests if the host is not valid.

- MatrixSDK/Contrib/Swift/MXIdentityServerRestClient.swift
- MatrixSDK/Contrib/Swift/MXIdentityService.swift
- MatrixSDK/Data/AutoDiscovery/MXAutoDiscovery.m
- MatrixSDK/IdentityServer/MXIdentityServerRestClient.h
- MatrixSDK/IdentityServer/MXIdentityServerRestClient.m
- MatrixSDK/IdentityServer/MXIdentityService.h
- MatrixSDK/IdentityServer/MXIdentityService.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDK/VoIP/CallStack/MXCallStackCall.h
MXIdentityService: Remove its dependency to MXCredentials
MXRestClient: Make it a bit less dependent on MXCredentials. Ideally, we should remove it
The contract is that services start on data initially passed in MXCredentials. Then, we can update their configs independently form MXCredentials. We just notify the MXCredentials original owner that configs as changed like identityServerAccessToken, and, very soon  identityServer.
> Less dependencies on MXCredentials

- CHANGES.rst
- MatrixSDK/IdentityServer/MXIdentityServerRestClient.m
closes vector-im/riot-ios#2696
> Privacy: Lowercase emails during IS lookup calls

- CHANGES.rst
- MatrixSDK/Contrib/Swift/MXIdentityService.swift
- MatrixSDK/IdentityServer/MXIdentityService.h
- MatrixSDK/IdentityServer/MXIdentityService.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.m
Fixes https://github.com/vector-im/riot-ios/issues/2704
> Privacy: MXRestClient: Use `id_access_token` in CS API when required

- CHANGES.rst
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
This notification triggers a modal in the app but not called from the main thread. iOS13 does not like that and Riot crashes in loop.
> BF: Send kMXSessionCryptoDidCorruptDataNotification from the main thread

- MatrixSDK/Crypto/Data/MXOlmSessionResult.m
Closes https://github.com/vector-im/riot-ios/issues/2733.
Logs now look like:
```
2019-09-24 11:47:28.191237+0200 xctest[87704:1312132] [MXMegolmEncryption] shareKey: ensureOlmSessionsForDevices result (users: 1 - devices: 1): {
"@mxbob-dffb007d-daa4-4dc4-b918-8122d740742b:localhost:8480" =     {
NAUURJAVCD = "<MXOlmSessionResult> NAUURJAVCD: kV3ssl2JYw4JtmMFQ7Op/S8spGXB3JFURHv3PFF+TFI";
};
}
```
> Crypto: MXOlmSessionResult: Implement description

- CHANGES.rst
- MatrixSDK/JSONModels/MXMatrixVersions.h
- MatrixSDK/JSONModels/MXMatrixVersions.m
- MatrixSDK/MXRestClient.m
Several fixes in one PR
-  Fixes vector-im/riot-ios#2718 (MXMatrixVersions: Support r0.6.0. Add doesServerSupportSeparateAddAndBind)
New r0.6.0 matches the current unstable flags of the HS:
```
{
"versions": ["r0.0.1", "r0.1.0", "r0.2.0", "r0.3.0", "r0.4.0", "r0.5.0"],
"unstable_features": {
"m.lazy_load_members": true,
"m.id_access_token": true,
"m.require_identity_server": false,
"m.separate_add_and_bind": true
}
}
```
- Fixes vector-im/riot-ios#2732 (Privacy: Do not include ID server or access token in /requestToken requests when HS supports MSC2290)
> Updates for privacy

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/Contrib/Swift/ThreePidAdd/MX3PidAddManager.swift
- MatrixSDK/IdentityServer/MXIdentityService.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDK/NotificationCenter/ServiceTerms/MXServiceTerms.m
- MatrixSDK/ThreePidAdd/MX3PidAddManager.h
- MatrixSDK/ThreePidAdd/MX3PidAddManager.m
- MatrixSDK/ThreePidAdd/MX3PidAddSession.h
- MatrixSDK/ThreePidAdd/MX3PidAddSession.m
This manager handles all HS flags. It adds, binds, unbinds 3pids, accordingly.
Apps should use it instead of MXK3Pid.
Note: All possible IS configurations are already managed by the `MXIdentityService` this manager uses.
Part of https://github.com/vector-im/riot-ios/issues/2713:
> [WIP] MX3PidAddManager: New class to handle add 3pids to HS and to bind to IS

- CHANGES.rst
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/ThreePidAdd/MX3PidAddManager.m
- MatrixSDK/ThreePidAdd/MX3PidAddSession.h
This PR implements ([MSC2078](https://github.com/matrix-org/matrix-doc/pull/2078)).
Fixes https://github.com/vector-im/riot-ios/issues/2731
> Privacy: Sending Third-Party Request Tokens via the Homeserver

- CHANGES.rst
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/Contrib/Swift/ThreePidAdd/MX3PidAddManager.swift
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/ThreePidAdd/MX3PidAddManager.h
- MatrixSDK/ThreePidAdd/MX3PidAddManager.m
- MatrixSDK/Utils/MXHTTPClient.m
- MatrixSDK/Utils/MXHTTPOperation.m
> MX3PidAddManager: Add User-Interactive Auth to /account/3pid/add

- CHANGES.rst
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXHTTPClient.m
Fixes vector-im/riot-ios#2793
There is no need to wait that crypto makes all its requests when resuming the SDK because the SDK already made mandatory requests (ie, posting its device ids and one time keys) on a previous initial sync.
When resuming, those crypto requests are just updates and can be done in parallel.
Combine with https://github.com/matrix-org/matrix-ios-kit/pull/624, `/sync` is now the 3rd request the SDK makes. This is better than the previous [8th](https://github.com/vector-im/riot-ios/issues/2793#issuecomment-546292325) position.
Moreover, the SDK makes it once it has loaded data from the store. It does no more wait for other requests to complete.
New ranking:
```
13:00:30.290 [MXHTTPClient] #0 - _matrix/client/unstable/devices/BCJUGLYRTV
13:00:30.305 [MXHTTPClient] #1 …
```
> MXSession: On resume, make the first /sync request trigger earlier

- MatrixSDK.podspec
- Podfile
- Podfile.lock
- SwiftMatrixSDK.podspec
Close vector-im/riot-ios/issues/2800.
Note: Do not update to 3.18.0 and above at the moment due to crashes occurring from 3.18.0 to 3.20.0.
> Update Realm Dependency to 3.17.3 and above

- CHANGES.rst
- MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m
Closes vector-im/riot-ios#2796.
> VoIP: Fix regression when using a TURN server

- CHANGES.rst
- MatrixSDK/IdentityServer/MXIdentityServerRestClient.m
closes vector-im/riot-ios#2824
> MXIdentityServerRestClient: Match registration endpoint to the IS r0.3.0 spec

- MatrixSDK/Data/MXRoomSummary.m
> MXRoomSummary: Fix potential crash when `_lastMessageOthers` is null

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Aggregations/MXAggregations.m
- MatrixSDK/Crypto/Verification/JSONModels/MXKeyVerificationJSONModel.m
- MatrixSDK/Crypto/Verification/JSONModels/MXKeyVerificationRequestJSONModel.h
- MatrixSDK/Crypto/Verification/JSONModels/MXKeyVerificationRequestJSONModel.m
- MatrixSDK/Crypto/Verification/MXDeviceVericationManager.m
- MatrixSDK/Crypto/Verification/MXDeviceVerificationManager.h
- MatrixSDK/Crypto/Verification/MXDeviceVerificationManager_Private.h
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationByDMRequest.h
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationByDMRequest.m
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest.h
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest.m
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest_Private.h
- MatrixSDK/Crypto/Verification/Status/MXKeyVerification.h
- MatrixSDK/Crypto/Verification/Status/MXKeyVerification.m
- MatrixSDK/Crypto/Verification/Status/MXKeyVerificationStatusResolver.h
- MatrixSDK/Crypto/Verification/Status/MXKeyVerificationStatusResolver.m
- MatrixSDKTests/MXAggregatedReferenceTests.m
- MatrixSDKTests/MXCryptoDeviceVerificationTests.m
Part of https://github.com/vector-im/riot-ios/issues/2851.
to get the `MXKeyVerification` status from any event. For the moment, it works only for verification by DM events.
> Expose [MXDeviceVerificationManager keyVerificationFromKeyVerificationEvent:]

- CHANGES.rst
- MatrixSDK/Contrib/Swift/Data/MX3PID.swift
- MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
- MatrixSDK/Contrib/Swift/JSONModels/MXJSONModels.swift
- MatrixSDK/Contrib/Swift/MXEnumConstants.swift
- MatrixSDK/Contrib/Swift/MXRestClient.swift
This mark the publicly exposed enums as both, `Equatable` and `Hashable`, which greatly helps in writing unit tests or scaffolding UI against the SDK.
Signed-off-by: Vincent Esche <138017+regexident@users.noreply.github.com>
> Mark enums as `Equatable`/`Hashable`, where applicable

- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction.m
- README.rst
Closes https://github.com/vector-im/riot-ios/issues/2919.
Riot-web can now cross-sign an iOS device.
> Cross-signing: Add MSK to m.key.verification.mac

- MatrixSDK/Crypto/Verification/MXDeviceVericationManager.m
- MatrixSDKTests/MXCryptoDeviceVerificationTests.m
Closes https://github.com/vector-im/riot-ios/issues/2907.
We mark all unknown devices as known.
> Verification by DM: Make it work in e2e room.

- CHANGES.rst
- MatrixSDK/JSONModels/MXRoomCreationParameters.h
- MatrixSDK/JSONModels/MXRoomCreationParameters.m
and allow e2e on room creation
vector-im/riot-ios/issues/2943
> MXRoomCreationParameters: Support the initial_state parameter

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction.m
- MatrixSDKTests/MXCrossSigningVerificationTests.m
This PR adds a test for the full flow of verification by DM with users with cross-signing enabled.
The goal was to find the issue Amandine has when self-signing ios from web but I have detected only minor issues.
I added logs to debug A's case.
> Verification by DM with users with cross-signing enabled

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Aggregations/MXAggregations.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.h
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
- MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
- MatrixSDK/Data/Store/MXStore.h
- MatrixSDK/JSONModels/Aggregations/MXAggregationPaginatedResponse.m
- MatrixSDK/JSONModels/Aggregations/MXAggregationPaginatedResponse_Private.h
vector-im/riot-ios/issues/2927
> MXAggregations: Optimise `referenceEventsForEvent` method, use cache when possible

- CHANGES.rst
- MatrixSDK/Crypto/Algorithms/MXEncrypting.h
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
- MatrixSDK/Crypto/Algorithms/Olm/MXOlmEncryption.m
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/KeySharing/MXIncomingRoomKeyRequestManager.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCrypto_Private.h
- MatrixSDK/Crypto/MXOlmDevice.h
- MatrixSDK/Crypto/MXOlmDevice.m
- MatrixSDKTests/MXCryptoTests.m
By implementing [MSC1719](https://github.com/matrix-org/matrix-doc/pull/1719)
Closes https://github.com/vector-im/riot-ios/issues/2129
Reading the test `testOlmSessionUnwedging` in this PR may help to understand the goal.
> MXCrypto: Restart broken Olm sessions

- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
- MatrixSDKTests/MXCryptoKeyVerificationTests.m
Closes https://github.com/vector-im/riot-ios/issues/3016
The start event is better managed than in https://github.com/matrix-org/matrix-ios-sdk/pull/773/commits/3819ad6c918895a6aabd5cdde69965dc66ce70df. The 2nd commit is to handle the ready.
> Verification: Ignore requests when we got a ready or a start event from another device

- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.h
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning_Private.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransaction.m
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction.m
- MatrixSDKTests/MXCrossSigningTests.m
The 2 first commits fix the `testBootstrapWithPassword` test.
Then, I introduced `MXCrossSigningState`.
> Cross-signing: Define a state

- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationByToDeviceRequest.m
testVerificationByToDeviceSelfVerificationFullFlow did not pass. The accept method was not sent to the other peer.
Probably a typo in the last PR.
> Cross-signing: Quick fix for self verification

- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.h
- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationByToDeviceRequest.m
- MatrixSDKTests/MXCryptoKeyVerificationTests.m
I thought it was required for https://github.com/vector-im/riot-ios/issues/3003 but it is surprisingly not the case.
Requests are now sent to other devices using their device id. Knowing all device ids makes request cancellation much more easier to implement.
I rolled back the patch made on `MXKeyVerificationByToDeviceRequest.otherDeviceId`. All tests pass now.
> Key Verification: Implement better self verification request to many

- CHANGES.rst
- MatrixSDK/Crypto/CrossSigning/Data/MXCrossSigningInfo.m
- MatrixSDK/Crypto/CrossSigning/JSONModels/MXCrossSigningKey.m
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
- MatrixSDK/Crypto/Verification/Status/MXKeyVerificationStatusResolver.m
- MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransaction.m
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomState.m
- MatrixSDK/Data/MXRoomSummaryUpdater.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDK/VoIP/MXCall.m
- MatrixSDK/VoIP/MXCallManager.m
- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/MXSessionTests.m
This fixes a race condition for cross-signing where MXSession.myUser can be nil.
In the second commit, I added logs to debug cross-signing. This gives:
```
2020-04-03 15:15:25.962714+0200 Riot[10860:124778] [MXCrossSigning] isSelfTrusted: NO (MSK not trusted). MSK: <MXCrossSigningKey: 0x600003028180> Keys: F0qYNM/wyloiDK961+3nrRjy5ZnguVKvwfpysAb7ozg. Signatures: {
"@xcalice4:matrix.org" =     {
"ed25519:AAUUEMWARH" = "yK78oLC6RImbjEOR3TnkYLIwOm3AVuf8edK5Psjikol8oYsuD+C/HdotcwApO10HPqcaJsnyvTgntdMRiIHGCQ";
};
}
2020-04-03 15:15:25.964299+0200 Riot[10860:124778] [MXCrossSigning] isSelfTrusted: My user devices: {
HCOMGMOFFM = "@xcalice4:matrix.org:HCOMGMOFFM - curve25519: iqPzoMwTCU4julRxhGTnOX82Wa3440TMTClQdszvpGc (trustLevel: MXDeviceTrustLevel: local: 1 - cross-signing: 0)";
SVRVEDEAJI = …
```
> MXSession: Add credentials, myUserId and myDeviceId shorcuts

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/Utils/MXBugReportRestClient.m
- MatrixSDK/Utils/MXHTTPClient.m
- Podfile
- Podfile.lock
- SwiftMatrixSDK.podspec
Updates AFNetworking library version to > 4.0.0.
Also removes UIWebView dependency for the SDK (#793)
> Update AFNetworking version

- CHANGES.rst
- MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup_Private.h
- MatrixSDK/Crypto/KeySharing/Data/MXOutgoingRoomKeyRequest.h
- MatrixSDK/Crypto/KeySharing/Data/MXOutgoingRoomKeyRequest.m
- MatrixSDK/Crypto/KeySharing/MXOutgoingRoomKeyRequestManager.h
- MatrixSDK/Crypto/KeySharing/MXOutgoingRoomKeyRequestManager.m
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDKTests/MXCryptoShareTests.m
Part of https://github.com/vector-im/riot-ios/issues/3089
With the option, key share requests are made only after we made a self-verification.
> MXCrypto: Add the option to disable sending key share requests

- MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.m
Kill the request as soon as we get the secret from a 1st device. Thus, we will ignore the secret coming from the 2nd device
Fixes https://github.com/vector-im/riot-ios/issues/3101.
> BF: App crashes if two devices gossip a secret

- MatrixSDK/Data/MXRoomSummary.m
Fixes https://github.com/vector-im/riot-ios/issues/3102.
Fix 2 bugs made in FOSDEM corridors. 
Make sure we download keys for users we want to compute trusts. Once their keys in the crypto store, we will be updated on our cross-signing state updates
> BF: Shields of verified users are black on a fresh new sign-in in

- CHANGES.rst
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCrypto_Private.h
- MatrixSDK/Crypto/Verification/Transactions/MXKeyVerificationTransaction.m
- MatrixSDKTests/MatrixSDKTestsE2EData.m
to make [MXCrypto decryptEvent:] less blocking when the UI calls it.
This is noticeable when keys import takes 20s. This operation blocked decryptEvent: before.
This threading model change is possible because we rely on the thread safety of the Realm DB.
Fixes https://github.com/vector-im/riot-ios/issues/3105.
> MXCrypto: Change the threading model

- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.m
- MatrixSDK/Crypto/Data/Trust/MXUserTrustLevel.h
- MatrixSDK/Crypto/Data/Trust/MXUserTrustLevel.m
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransaction.m
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction.m
- MatrixSDKTests/MXCrossSigningTests.m
- MatrixSDKTests/MXCrossSigningVerificationTests.m
Fixes https://github.com/vector-im/riot-ios/issues/3112.
I tested it only with SAS. This will worth to test it with QR code when it will be more stable.
This is done by trusting locally our own user. Thus, we trust their MSK.
Commits can be checked one by one.
> BF: Cross-sign is broken from the 3rd generation

- CHANGES.rst
- MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m
The peer connection requires the remote description to be setup before any remote ice candidates are added to it.
In the current implementation, ice candidates are sent before the called device has responded with an answer. Therefore there can be a case where the called device handles incoming ice candidates before it handles the initial offer from the caller.
This often happens when the called device is not having the app open **and** is not in the same network (e.g. one device using wifi, one using cellular), leaving the call to be stuck in "connecting" until the call is either ended or times out.
This potentially fixes multiple issues in vector-im/riot-ios. I think this is the initial one describing the issue best:
https://github.com/vector-im/riot-ios/issues/1784
> Fix remote ice candidates being added before remote description is setup

- CHANGES.rst
- MatrixSDKExtensions/VoIP/Jingle/MXJingleCallAudioSessionConfigurator.m
This particular commit doesn't fix any issues to my knowledge. I just noticed this workaround and saw that it is no longer needed, since the required methods in RTCAudioSession are now available.
> Remove workaround in MXJingleCallAudioSessionConfigurator

- CHANGES.rst
- MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.m
Fix vector-im/riot-ios/issues/3120
> MXDeviceListOperationsPool: Post MXDeviceListDidUpdateUsersDevicesNotification notification only for new changes never seen before

- CHANGES.rst
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/MXSession.m
This method can be called at anytime. The key will be validated (and erased if needed) once the module fetches the available backup version.
> MXKeyBackup: Do not clear the private key on resetKeyBackupData

- CHANGES.rst
- CONTRIBUTING.rst
The file was changed to markdown [in December 2019](https://github.com/matrix-org/synapse/commit/c1ae453932da8b5761cd1644b4b0bbaa039ae6ab).
I guess it wouldn't be needed but as it's part of the checklist :wink:  :
Signed-off-by: Maximilian Müller <maxm123@techie.com>
> Update the CONTRIBUTING.rst to point to correct file.

- CHANGES.rst
- MatrixSDK/Crypto/MXCrypto.m
The goal of these 2 changes is to recover better from a weird state of the cross-signing or the key backup.
We will recover by cross-signing the device again.
> Make sure we can make gossip requests again from a device already verified

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/Utils/MXBugReportRestClient.m
- MatrixSDK/Utils/MXHTTPClient.m
- MatrixSDKTests/MXAutoDiscoveryTests.m
- MatrixSDKTests/MXCryptoShareTests.m
- Podfile
- Podfile.lock
- SwiftMatrixSDK.podspec
Update all pods except jitsi to be still able to build in xcode10.3
I cherry picked commits from the xcode11 branch and fix some issues to make `pod lib lint` happy.
> Pods update

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/SecretStorage/Data/MXSecretStorageKeyCreationInfo.h
- MatrixSDK/Crypto/SecretStorage/Data/MXSecretStorageKeyCreationInfo.m
- MatrixSDK/Crypto/SecretStorage/JSONModels/MXEncryptedSecretContent.h
- MatrixSDK/Crypto/SecretStorage/JSONModels/MXEncryptedSecretContent.m
- MatrixSDK/Crypto/SecretStorage/JSONModels/MXSecretStorageKeyContent.h
- MatrixSDK/Crypto/SecretStorage/JSONModels/MXSecretStorageKeyContent.m
- MatrixSDK/Crypto/SecretStorage/JSONModels/MXSecretStoragePassphrase.h
- MatrixSDK/Crypto/SecretStorage/JSONModels/MXSecretStoragePassphrase.m
- MatrixSDK/Crypto/SecretStorage/MXSecretStorage.h
- MatrixSDK/Crypto/SecretStorage/MXSecretStorage.m
- MatrixSDK/Crypto/SecretStorage/MXSecretStorage_Private.h
- MatrixSDK/Crypto/Utils/MXAesHmacSha2.h
- MatrixSDK/Crypto/Utils/MXAesHmacSha2.m
- MatrixSDK/Crypto/Utils/MXHkdfSha256.h
- MatrixSDK/Crypto/Utils/MXHkdfSha256.m
- MatrixSDK/Data/MXAccountData.h
- MatrixSDK/Data/MXAccountData.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXBase64Tools.h
- MatrixSDK/Utils/MXBase64Tools.m
- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXCryptoSecretStorageTests.m
Fix https://github.com/vector-im/riot-ios/issues/2926
Spec: ([MSC1946(]https://github.com/matrix-org/matrix-doc/pull/1946)
This module will be used for bootstrap and account keys recovery.
> Create MXSecretStorage to support SSSS

- CHANGES.rst
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.m
- MatrixSDK/IdentityServer/MXIdentityService.m
Fixes vector-im/riot-ios/issues/3272
Fixes vector-im/riot-ios/issues/3273
> Crash fixes

- CHANGES.rst
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDKTests/MXCryptoTests.m
Fix vector-im/riot-ios/issues/2331
> MXCrypto: Only create one olm session at a time per device

- CHANGES.rst
- MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.m
Fix vector-im/riot-ios/issues/3343
> MXDeviceListOperationsPool: Fix current device verification status put in MXDeviceUnknown instead of MXDeviceVerified

- CHANGES.rst
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.h
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDKTests/MXCrossSigningTests.m
fixes vector-im/riot-ios/issues/3346
> MXCrossSigning: Gossip the master key

- CHANGES.rst
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
Part of vector-im/riot-ios#3371
> Introduce `enableKeyBackupWhenStartingMXCrypto` in MXSDKOptions

- CHANGES.rst
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/Recovery/MXRecoveryService.h
- MatrixSDK/Crypto/Recovery/MXRecoveryService.m
- MatrixSDKTests/MXCryptoRecoveryServiceTests.m
Part of vector-im/riot-ios/issues/3361
> MXRecoveryService: Add options to create and delete key backup automatically

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/MXSession.m
- MatrixSDK/MatrixSDKVersion.m
- SwiftMatrixSDK.podspec
This PR prepares the release of MatrixSDK v0.16.8.
:bulb: This PR targets `master` to respect git flow, but if you want to just review the changes made since the
`release/0.16.8` was cut from `develop`, you can [check those here](git@github.com:matrix-org/matrix-ios-sdk.git/compare/develop...release/0.16.8)
As of now, there are still some steps to do manually before going forward with the release process:
of MatrixSDK have been updated (see `Podfile.lock` changes)[^1]
then run `pod lib lint` manually to validate the podspec [^2]
Once the PR has been reviewed and merged, run the `rake release:finish` command from the element-ios-tools to finish the process.
:warning: Be sure to merge the PRs in the right order before continuing the release process (`MatrixSDK`, then `MatrixKit`, then …
> Release 0.16.8

- MatrixSDK.xcodeproj/xcshareddata/xcschemes/MatrixSDK-iOS.xcscheme
- fastlane/Fastfile
---
Adds `build_macos` and `build_ios` lanes to the `Fastfile` – as well as a `build_scheme(…)` private lane used by those – which will be the lanes triggered by CI.
(The rest of the changes is mainly re-formatting done by vscode, that I kept applied for consistency)
> Add some fastlane tasks for CI

- fastlane/Fastfile
Previously this `pod install` was done by the pipeline during the setup phase, but now that we do the switcheroo after setup and before build, better move that to the fastfile (so that it also works locally)
> [Internal] [CI] Ensure pod install before build_scheme #trivial

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK.xcodeproj/xcshareddata/xcschemes/MatrixSDK-iOS.xcscheme
- MatrixSDK/MatrixSDKVersion.m
- fastlane/Fastfile
This PR prepares the release of MatrixSDK v0.16.9.
Notes:
- This PR targets `release/0.16.9/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.16.9/master` into `master` to tag the release.
--- …
> Release 0.16.9

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK.xcodeproj/xcshareddata/xcschemes/MatrixSDK-iOS.xcscheme
- MatrixSDK.xcodeproj/xcshareddata/xcschemes/MatrixSDK-macOS.xcscheme
- MatrixSDKTests/MXAggregatedReactionTests.m
- MatrixSDKTests/MXCrossSigningTests.m
- MatrixSDKTests/MXCrossSigningVerificationTests.m
- MatrixSDKTests/MXCryptoBackupTests.m
- MatrixSDKTests/MXCryptoKeyVerificationTests.m
- MatrixSDKTests/MXCryptoRecoveryServiceTests.m
- MatrixSDKTests/MXCryptoSecretShareTests.m
- MatrixSDKTests/MXCryptoShareTests.m
- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/MXEventTimelineTests.m
- MatrixSDKTests/MXLazyLoadingTests.m
- MatrixSDKTests/MXRestClientNoAuthAPITests.m
- MatrixSDKTests/MXRestClientTests.m
- MatrixSDKTests/MXRoomSummaryTests.m
- MatrixSDKTests/MXRoomSummaryTrustTests.m
- MatrixSDKTests/MXSelfSignedHomeserverTests.m
- MatrixSDKTests/MXStoreTests.m
- MatrixSDKTests/MatrixSDKTestsData.h
- MatrixSDKTests/MatrixSDKTestsData.m
- MatrixSDKTests/MatrixSDKTestsE2EData.h
- MatrixSDKTests/MatrixSDKTestsE2EData.m
- fastlane/Fastfile
Commits can be reviewed separately.
Changes and explanation:
* Fix "fastlane ios test" and generate html report
Available at build/test/report.html. Other available artefacts: MatrixSDK-macOS.xcresult and report.junit
* Make tests fail instantly if no local synapse is running
In order to save CI time
* Do not use anymore NSAssert in tests
If there is a crash when running tests that will be for a good reason. Plus it avoids xcode to rerun crashed tests 7 times.
> Test update

- CHANGES.rst
- MatrixSDK/Data/MXRoomState.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
The bug was located in [MXRoomState copyWithZone:]. Indeed the item `membersCount` was not copied correctly whereas this is an instance of MXRoomMembersCount class.
The "back state" created thanks to the copy here: https://github.com/matrix-org/matrix-ios-sdk/blob/6027fd5b2b644f2ebeb1049cdb80a318d7db2273/MatrixSDK/Data/MXRoomState.m#L126 was using the same membersCount instance as the provided "live state". The content of this membersCount was updated in case of membership events in the back pagination. The live state was then corrupted.
According to my investigation, the corrupted state was not pushed to the store, except perhaps if new membership events were received in the live stream.
> Some room members count are wrong after clearing the cache

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
This PR prepares the release of MatrixSDK v0.16.14.
Notes:
- This PR targets `release/0.16.14/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.16.14/master` into `master` to tag the release.
--- …
> Release 0.16.14

- CHANGES.rst
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
This commit does not fix a corruption that we can have on the meta data file, probably due to a race condition. But it detects when the corruption happens and resets the store and everything.
> MXFileStore: Make loadMetaData more robust

- CHANGES.rst
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/SecretStorage/MXSecretStorage.m
- MatrixSDK/Crypto/Verification/Data/MXQRCodeDataBuilder.m
- MatrixSDK/Crypto/Verification/Data/MXQRCodeDataCoder.m
- MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransaction.m
- MatrixSDK/Utils/MXBase64Tools.h
- MatrixSDK/Utils/MXBase64Tools.m
- MatrixSDKTests/MXCryptoSecretStorageTests.m
Fix vector-im/element-ios/issues/3667
Fix vector-im/element-ios/issues/3668
We have now only one decoding method that manages padded and unpadded base64.
SDK tests are still happy.
> MXBase64Tools: Make sure the SDK decode padded and unpadded base64 like other platforms

- CHANGES.rst
- MatrixSDK/Crypto/SecretStorage/MXSecretStorage.m
Fix vector-im/riot-ios/issues/3669
This changes will not affect other clients (web, android) or existing data. It is only driven by consistency across platforms.
>  SSSS: Use unpadded base64 for secrets data

- CHANGES.rst
- MatrixSDK/MXSession.m
Fix vector-im/element-ios/issues/3653
> MXSession: Fix Well-known not read from the homeserver domain

- CHANGES.rst
- MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.m
- MatrixSDK/Crypto/MXCrypto.m
This is a mitigation for vector-im/element-ios#3721. 
But it does not fix the root issue.
This is how this PR behaves on the [steps to reproduce](https://github.com/vector-im/element-ios/issues/3721#issuecomment-705400377):
```
2020-10-08 09:16:22.890670+0200 Riot[31404:1330203] [MXHTTPClient] #12 - POST _matrix/client/r0/keys/upload/SYNBAYVHFQ completed in 196ms
2020-10-08 09:16:22.891049+0200 Riot[31404:1330203] [MXHTTPClient] Request 0x6000002a2ec0 failed for path: _matrix/client/r0/keys/upload/SYNBAYVHFQ - HTTP code: 400. Error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: bad request (400)" UserInfo={NSLocalizedDescription=Request failed: bad request (400), NSErrorFailingURLKey=https://matrix-client.matrix.org/_matrix/client/r0/keys/upload/SYNBAY …
```
> MXCrypto: Reset OTKs when some IDs are already used

- CHANGES.rst
- MatrixSDK/JSONModels/MXEvent.m
This PR aims to fix the crash loop when a `msgtype` of an `m.room.message` event is not a string as expected.
> Fix non-string `msgtype` crash

- CHANGES.rst
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDKTests/MXCrossSigningTests.m
And not because this device is verified by cross-signing, which is already true.
The new test shows the issue by resetting the cross-signing from another device
> MXCrossSigning: Trust cross-signing because we locally trust the devie that created it

- CHANGES.rst
- MatrixSDK.podspec
I tested Jitsi and 1:1 calls on Xcode 12. They work as expected.
This is a WIP because EI does not build with Xcode 11.7 with this update.
> Pod: Update Jitsi a bit more to build with Xcode 12

- CHANGES.rst
- MatrixSDK/Utils/MXThrottler.m
This will prevent unexpected loop
Closes https://github.com/vector-im/element-ios/issues/3778
> MXThrottler: Dispatch the block on the correct queue

- CHANGES.rst
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
Fixes https://github.com/vector-im/element-ios/issues/3792.
> MXRealmCryptoStore: Compact DB files before getting out of memory error

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/MXEnumConstants.h
- MatrixSDK/MXEnumConstants.m
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/Profiling/MXBaseProfiler.h
- MatrixSDK/Utils/Profiling/MXBaseProfiler.m
- MatrixSDK/Utils/Profiling/MXProfiler.h
- MatrixSDK/Utils/Profiling/MXTaskProfile.h
- MatrixSDK/Utils/Profiling/MXTaskProfile.m
- MatrixSDK/Utils/Profiling/MXTaskProfile_Private.h
The default implementation, `MXBaseProfiler`, reports duration in logs and to the `MXAnalytics` interface.
Logs look like:
```
[MXBaseProfiler] Task startup - storePreload for 578 units completed in 1682.477ms
[MXBaseProfiler] Task startup - mountData for 578 units completed in 2267.157ms
[MXBaseProfiler] Task startup - launchScreen for 1 units completed in 2282.014ms
...
[MXBaseProfiler] Task startup - incrementalSync for 53 units completed in 481.103ms
[MXBaseProfiler] Task notifications - timelineDisplay for 1 units completed in 652.003ms
```
The app can call `MXProfiler.pause()` when it goes in background. This avoids to measure and to report bad durations.
> Tools: Add MXProfiler to track performances

- CHANGES.rst
- MatrixSDK.podspec
- Podfile
- Podfile.lock
`pod lib lint` passed but not `pod trunk push`. The last one complained about the sub spec related to JitsiMeetSDK.
It seems that `pod lib lint` does not explicitly lint sub specs. 
To force the lint of guilty sub spec, I ran:
`pod lib lint --subspec=JingleCallStack --fail-fast --verbose --no-clean --allow-warnings`
> Podspec: Fix arm64 simulator issue with JitsiMeetSDK

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
- Podfile.lock
This PR prepares the release of MatrixSDK v0.17.2.
Notes:
- This PR targets `release/0.17.2/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.17.2/master` into `master` to tag the release.
--- …
> Release 0.17.2

- CHANGES.rst
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
- MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXOlmDevice.m
Closes https://github.com/vector-im/element-ios/issues/3817.
by making olm operations atomic.
Commits can be reviewed one by one. I started to make OlmAccount atomic. Then, OlmSession and OlmInboundGroupSession.
> MXOlmDevice: Make usage of libolm data process-safe

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCrypto_Private.h
- MatrixSDK/Crypto/Migration/MXCryptoMigration.h
- MatrixSDK/Crypto/Migration/MXCryptoMigration.m
- MatrixSDK/Crypto/Migration/MXCryptoVersion.h
- MatrixSDKTests/MXCryptoMigrationTests.m
Fix vector-im/element-ios/issues/3818.
> MXCrypto: Create MXCryptoMigration to purge all one time keys because some may be bad

- CHANGES.rst
- MatrixSDK/MXSession.m
The bug is not related to the bg sync service but its impact is much more visible. Having the MXSession still running in parallel of the bg sync service is definitely not great.
The rest is the commit message:
The bug exists since lazy loading implementation and the a-synchronousness it added. 
When the race appears, the session does not pause which leads to bg kills on iOS (https://github.com/vector-im/element-ios/issues/3761).
This commit fixes also the resume operation that never returned if the app was in running state (which was the case with the race condition).
> MXSession: Fix a race condition that prevented MXSession from actually being paused

- CHANGES.rst
- MatrixSDK.podspec
fix vector-im/element-ios/issues/3808
> Pods: Update JitsiMeetSDK to 2.11.0 to be able to build using Xcode 12.2

- CHANGES.rst
- MatrixSDK.podspec
- Podfile
- Podfile.lock
Another update required for vector-im/element-ios/issues/3808.
> Pods: Update Realm to 10.1.4 to be able to `pod lib lint` using Xcode 12.2

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomAccountData.h
- MatrixSDK/Data/MXRoomAccountData.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/JSONModels/MXTaggedEventInfo.h
- MatrixSDK/JSONModels/MXTaggedEventInfo.m
- MatrixSDK/JSONModels/MXTaggedEvents.h
- MatrixSDK/JSONModels/MXTaggedEvents.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXRoomTests.m
MSC: matrix-org/matrix-doc#2437
> MXTaggedEvents: Expose "m.tagged_events" according to (MSC2437)

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/JSONModels/Login/MXLoginSSOFlow.h
- MatrixSDK/JSONModels/Login/MXLoginSSOFlow.m
- MatrixSDK/JSONModels/Login/MXLoginSSOIdentityProvider.h
- MatrixSDK/JSONModels/Login/MXLoginSSOIdentityProvider.m
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MatrixSDK.h
- MatrixSDKTests/MXAuthenticationSessionTests.swift
Implement [MSC2858](https://github.com/matrix-org/matrix-doc/pull/2858)
Part of vector-im/element-ios/issues/3846
> Support multiple SSO Identity Providers (MSC2858)

- CHANGES.rst
- MatrixSDK/VoIP/CallStack/MXCallStackCall.h
- MatrixSDK/VoIP/MXCall.m
- MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m
Fix vector-im/element-ios#3862
> VoIP: Use Tracks Instead of Transceivers

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/MXBackgroundStore.swift
- MatrixSDK/Background/MXBackgroundSyncService.swift
- MatrixSDK/Background/Store/SyncResponseFileStore/MXSyncResponseFileStore.swift
- MatrixSDK/Data/MXRoomMembers.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.h
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDKTests/MXBackgroundSyncServiceTests.swift
In real life, the same `MXBackgroundSyncService` instance runs for hours.  `MXSession` can run in parallel with it.
Here, we make sure that `MXBackgroundSyncService` uses the latest data stored by `MXSession`, instead of using obsolete data we have in memory.
Else `MXSession` will consider `MXBackgroundSyncService` data obsolete on its next startup or resume, making `MXBackgroundSyncService` previous work useless.
MXBackgroundStore.event(withEventId:) was not working. It should work now.
> MXBackgroundSyncService: Keep its stores in sync with MXSession store

- CHANGES.rst
- MatrixSDK/MXRestClient.m
Fixes: https://github.com/vector-im/element-ios/issues/3539
This changes the format of the request to `POST /_matrix/client/r0/keys/query` from:
```jsonc
{
...
"device_keys": {
"@user:domain": {}
},
...
```
to
```jsonc
{
...
"device_keys": {
"@user:domain": []  // changed to array
},
...
```
which is spec compliant. Dendrite [will fail](https://github.com/matrix-org/complement/pull/20) these requests if a dictionary if provided instead of an array.
Given the above issue, I feel that there must be somewhere that Element iOS also requests `POST /_matrix/client/r0/keys/query` with user IDs *and* device IDs, but I could only find this code that requests keys for all devices. Therefore I might be missing something :slightly_smiling_face:
> Use an array instead of dictionary when querying all device keys

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/KeyProvider/MXAesKeyData.h
- MatrixSDK/Crypto/KeyProvider/MXAesKeyData.m
- MatrixSDK/Crypto/KeyProvider/MXKeyData.h
- MatrixSDK/Crypto/KeyProvider/MXKeyData.m
- MatrixSDK/Crypto/KeyProvider/MXKeyProvider.h
- MatrixSDK/Crypto/KeyProvider/MXKeyProvider.m
- MatrixSDK/Crypto/KeyProvider/MXRawDataKey.h
- MatrixSDK/Crypto/KeyProvider/MXRawDataKey.m
- MatrixSDK/MatrixSDK.h
- MatrixSDKTests/MXKeyProviderTests.m
part of the fix for https://github.com/vector-im/element-ios/issues/3866
> Added MXKeyProvider to share encryption keys between application and Kit

- CHANGES.rst
- MatrixSDK/Data/MXRoomSummary.m
Fix https://github.com/vector-im/element-ios/issues/3879
> MXRoomSummary: Fix crash when lastMessageData cannot be decrypted

- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDKTests/MXRestClientTests.m
Fix vector-im/element-ios/issues/3737
The CS API does not take a deviceId parameter.
Tests are still happy:
> MXRestClient: Fix uploadKeys method that was using the /keys/upload/ in a bad way

- CHANGES.rst
- MatrixSDK/JSONModels/Login/MXLoginSSOFlow.h
- MatrixSDK/JSONModels/Login/MXLoginSSOFlow.m
- MatrixSDKTests/MXAuthenticationSessionTests.swift
See https://github.com/matrix-org/matrix-doc/pull/2858/#discussion_r543567196 for more details.
> MXLoginSSOFlow: Use unstable identity providers field while the MSC2858 is not approved

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK.xcodeproj/xcshareddata/IDETemplateMacros.plist
- MatrixSDK/Background/MXBackgroundCryptoStore.h
- MatrixSDK/Background/MXBackgroundCryptoStore.m
- MatrixSDK/Background/MXBackgroundSyncService.swift
- MatrixSDK/Data/MXCredentials.h
- MatrixSDK/Data/MXCredentials.m
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MatrixSDK.h
- MatrixSDKTests/MXBackgroundSyncServiceTests.swift
created between the app process and the notification service extension process
Fix vector-im/element-ios/issues/3906
The fix consists in having a separated MXCryptoStore DB where the NSE writes in. Thus, each MXCryptoStore DB is written by only one process. One process cannot be blocked anymore because another process is writing to the same DB.
> MXBackgroundSyncService: Fix app deadlock 

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Utils/MXBackgroundModeHandler.h
- MatrixSDK/Utils/MXUIKitApplicationStateService.swift
- MatrixSDK/Utils/MXUIKitBackgroundModeHandler.m
- MatrixSDK/Utils/MXUIKitBackgroundTask.h
- MatrixSDK/Utils/MXUIKitBackgroundTask.m
to keep threading model as it was before
Fix vector-im/element-ios/issues/3917.
> MXUIKitBackgroundTask: Avoid thread switching when creating a background task

- CHANGES.rst
- MatrixSDK/Utils/MXUIKitBackgroundTask.m
Fix vector-im/element-ios#3935
> BackgroundTask: Avoid Calling Expiration Handlers on App Extensions

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
This PR prepares the release of MatrixSDK v0.17.8.
Notes:
- This PR targets `release/0.17.8/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.17.8/master` into `master` to tag the release.
--- …
> Release 0.17.8

- CHANGES.rst
- MatrixSDK/JSONModels/MXEvent.m
https://github.com/vector-im/element-ios/issues/3944
The regression came from this commit: https://github.com/matrix-org/matrix-ios-sdk/commit/ee85b4d2ae325d258a82a405480d293950cfe9d5#diff-7cdafc921212e01c6332371099d18fee873c8f1c1a5354520f71e6c623b7081eR857
Before:
After:
> MXEvent: Fix a regression on edits and replies in e2ee rooms

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
This PR prepares the release of MatrixSDK v0.17.9.
Notes:
- This PR targets `release/0.17.9/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.17.9/master` into `master` to tag the release.
--- …
> Release 0.17.9

- CHANGES.rst
- MatrixSDK/Background/MXBackgroundCryptoStore.h
- MatrixSDK/Background/MXBackgroundCryptoStore.m
- MatrixSDK/Background/MXBackgroundSyncService.swift
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
so that we will be able to even clear corrupted db. This should fix vector-im/element-ios#3956.
It does not prevent the corruption (even Realm does not know how it can happen) but the app and the NSE will auto fix themselves. The user will just need to open the app. 
Opening the app will clear the background sync cache. On the next push, the bg sync service will detect that the bg sync cache is empty, it will then clear the realm db. Any corrupted db issue is solved.
Some notifications will not be able to decrypt but messages will be readable within the app.
This required some changes in `MXRealmCryptoStore` to delete the db without opening it.
> MXBackgroundSyncService: Clear the bg sync crypto db if needed 

- CHANGES.rst
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
- MatrixSDK/Crypto/Data/MXCryptoConstants.h
- MatrixSDK/Crypto/KeySharing/MXIncomingRoomKeyRequestManager.m
- MatrixSDK/Data/MXRoom.m
The workaround for https://github.com/vector-im/element-ios/issues/3807 is explained in the [code](https://github.com/matrix-org/matrix-ios-sdk/compare/3807_keys_not_sent_workaround?expand=1#diff-71ce6c0d14f35842c13b559fe3fb8d8b1854546a30be98b476b5407146ec83aaR281)
I added more logs in the lazy loading of room members to check if the root issue is not there.
> Workaround for users we did not send keys to 

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/Store/SyncResponseFileStore/MXSyncResponseFileStore.swift
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Utils/MXMemory.swift
- MatrixSDK/Utils/MXTools.h
- MatrixSDK/Utils/MXTools.m
This change will make out of memory issues described at https://github.com/vector-im/element-ios/issues/3957#issuecomment-769076459 happen a bit later.
We need to have another implementation of the store for big accounts letting their app in background.
With a bg sync store of 2MB, I can get notifications and I have 4MB memory left (out of 24MB available). 
MXMemory was moved from element codebase.
> Background Sync: Use autoreleasepool to limit RAM usage

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/JSONModels/Login/MXLoginSSOIdentityProvider.h
- MatrixSDK/JSONModels/Login/MXLoginSSOIdentityProvider.m
- MatrixSDK/JSONModels/Login/MXLoginSSOIdentityProviderBrand.h
Part of vector-im/element-ios/issues/3980
> MXLoginSSOIdentityProvider: Add new `brand` field as described in MSC2858

- CHANGES.rst
- MatrixSDK/ThreePidAdd/MX3PidAddManager.m
fix vector-im/element-ios/issues/3966
We need it because Synapse now checks that it is not empty. We can use any non empty strings.
The proper fix will be to use the same client_secret  (and sid) from the beginning of the authentication. But this will be done later with https://github.com/vector-im/element-ios/issues/3970.
> MX3PidAddManager: Use a non empty client_secret to discover /account/3pid/add flows

- CHANGES.rst
- MatrixSDK/VoIP/MXCall.m
Fix vector-im/element-ios#3971
> VoIP: Fix camera indicator when video call answered elsewhere

- CHANGES.rst
- MatrixSDK/MXSession.h
Part of vector-im/element-ios#3986
> MXSession: Make `handleBackgroundSyncCacheIfRequiredWithCompletion` public

- MatrixSDK/Utils/MXTools.m
Fixes `m.key.verification.start` events to be handled as `m.key.verification.request` events.
> VoIP: Add New Event Types to Mapping

- CHANGES.rst
- MatrixSDK/MXSession.m
I observed a direct chat for which the field directUserId was null in its room summary. NOK
This field of the room summaries is updated currently in 3 cases (at the sdk level during the sync):
- initial sync
- new invites in the server sync response
- an update of the direct chats (in the account data)
I remembered join this direct chat on a web client, I realized the room summary was not correctly updated on iOS because the room was not present in the rooms list when we processed the new direct chat list. Indeed the account data (in which are the directs) are handled before the joined room list...
In conclusion: directUserId is missing (null) for a direct chat after the sync if it was joined on another device whereas the ios session was offline.
> BugFix - MXRoomSummary: directUserId may be missing (null) for a direct chat if it was joined on another device.

- CHANGES.rst
- MatrixSDK/Data/MXCredentials.h
- MatrixSDK/Data/MXCredentials.m
- MatrixSDK/JSONModels/MXJSONModels.m
fix https://github.com/vector-im/element-ios/issues/4024
> MXCredentials: Expose additional server login response data

- CHANGES.rst
- build.sh
This PR adds an optional `xcframework` argument that can be passed to `build.sh`. When used it will create `build/MatrixSDK.xcframework` with targets for iOS, macOS, Catalyst and the Simulator with all arm64 and x86_64 slices where relevant. This distributable would make matrix integration easier for Xcode projects that aren't using cocoapods.
Depends on #983 to successfully build.
Signed-off-by: Doug Earnshaw pixlwave@users.noreply.github.com
> Add xcframework argument to build.sh

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/Crypto/Data/MXCryptoConstants.h
- MatrixSDK/Crypto/Data/MXCryptoConstants.m
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/KeyProvider/MXKeyProvider.m
- MatrixSDK/Crypto/MXOlmDevice.m
- Podfile
- Podfile.lock
Fix https://github.com/vector-im/element-ios/issues/3867
Require https://gitlab.matrix.org/matrix-org/olm/-/merge_requests/17.
It embeds the realm db migration code refactoring made in https://github.com/matrix-org/matrix-ios-sdk/pull/973 even if no migration is required here.
We cannot use the built-in encryption offered by Realm because it does not support multi-process. So, let's encrypt every single thing in a clear Realm db.
> MXRealmCryptoStore: Make sure secrets in the DB are encrypted

- CHANGES.rst
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
Fix vector-im/element-ios#4099
> MXCrossSigning: Fix setupWithPassword method crash when a grace period is enabled

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
This PR prepares the release of MatrixSDK v0.18.4.
Notes:
- This PR targets `release/0.18.4/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.18.4/master` into `master` to tag the release.
--- …
> Release 0.18.4

- CHANGES.rst
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
fix https://github.com/vector-im/element-ios/issues/4104
> Crypto: Duplicate message index after using the share extension

- CHANGES.rst
- MatrixSDK/Info.plist
- build.sh
This makes two tweaks to building MatrixSDK.xcframework:
- Allow the command to be formed as `./build.sh xcframework 0.18.4 99` to include bundle versions in the archived frameworks. This fixes a rejection from App Store Connect as these values are currently missing.
- Additionally create MatrixSDK.xcframework.zip to use as binary package if required.
Passing the versions as arguments to the build command seemed the easiest change so you don't need to update a version inside of the Xcode project as part of your release process, but if you think that makes more sense I'm happy to update 🙂
Signed-off-by: Doug Earnshaw pixlwave@users.noreply.github.com
> XCFramework tweaks

- CHANGES.rst
- MatrixSDK/Data/MXRoomMembers.h
- MatrixSDK/Data/MXRoomMembers.m
- MatrixSDK/Data/MXRoomState.m
- MatrixSDKTests/MXRoomStateTests.m
`MXRoomState` and `MXRoomMembers` currently hold mutual strong references to each other via the `members` property and the `state` ivar, respectively. This leads to a memory leak preventing both objects from being deallocated. The leak is easy to reproduce in the Element iOS app. Just launch the app, use a few rooms and start the memory graph debugger. At this point you'll find orphaned objects retaining each other such as:
Additionally, the leak is masqueraded by a bug in `MXRoomState`'s `copyWithZone:` method. The latter copies the `MXRoomMembers` object but doesn't update its `state` ivar to point to the `MXRoomState` copy. As a result, copying an `MXRoomState` object does *not* introduce another leak. I've noticed this when writing a unit test for the leak. Instead of the retain …
> MXRoomState/MXRoomMembers: Fix memory leak and copying

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/Data/MXDeviceListOperation.m
- MatrixSDKTests/MXDeviceListOperationsPoolTests.swift
This breaks a strong reference cycle between `MXDeviceListOperation` and `MXDeviceListOperationsPool`. When an operation is added to a pool, both objects hold mutual strong references to each other by means of the `pool` and `_operations` ivars. This prevents them from being deallocated when the operation has finished.
The leak can easily be reproduced in the Element iOS app:
1. Start the app
2. Open settings
3. Open security settings (loads a list of sessions / devices)
4. Start memory graph debugger in Xcode
At this point you'll notice orphaned `MXDeviceListOperation` and `MXDeviceListOperationsPool` objects that retain each other (red box). Note that there is another memory leak visible in the screenshot below where `MXDeviceListOperation` retains itself. This is addressed in #1042. …
> MXDeviceListOperation: Fix memory leak

- CHANGES.rst
- MatrixSDK/Crypto/Data/MXDeviceList.m
When creating an `MXDeviceListOperation` in `MXDeviceList`, the block passed into the `success` parameter captures a strong reference to the operation. Since the `success` block is stored with a strong reference in `MXDeviceListOperation`, this creates a strong reference cycle that prevents the operation from being deallocated.
The leak is easily reproduced in the Element iOS app:
1. Start the app
2. Open settings
3. Open security settings (loads a list of sessions / devices)
4. Start memory graph debugger in Xcode
At this point you'll notice leaked `MXDeviceListOperation` objects that retain themselves (red box). Note that there is another memory leak visible in the screenshot below where `MXDeviceListOperation` and `MXDeviceListOperationsPool` retain each other. This leak is addressed …
> MXDeviceList: Fix memory leak

- CHANGES.rst
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Data/MXRoomSummary.h
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDKTests/MXRoomSummaryTrustTests.m
There are 2 separates improvements:
- Do not load room members in e2e rooms after an initial sync (1st commit)
- Add MXRoomSummary:.enableTrustTracking() to compute and maintain trust value for the given room (vector-im/element-ios/issues/4115).
> E2E improvements

- .github/workflows/cocoapods.yml
- CHANGES.rst
- Gemfile
- Gemfile.lock
- fastlane/Fastfile
Let's try GH actions for long operation like `pod lib lin``
It is done only for Release to save half the time.
This is a test. We will probably do more later.
> GitHub Actions: Run pod lib lint

- CHANGES.rst
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
Fix vector-im/element-ios/issues/4113
Avoid crashes and log what is wrong.
> MXKeyBackup: Add sanity checks to avoid crashes

- CHANGES.rst
- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXToolsTests.m
Due to a Simulator bug on the Apple M1, `UTTypeCreatePreferredIdentifierForTag` can unexpectedly return `NULL`. This causes a crash because the return value is later passed into `CFRelease` which explicitly disallows `NULL` arguments.
This commit fixes the issue by ensuring the return value is not `NULL` before proceeding.
Fixes: vector-im/element-ios#4140
Signed-off-by: Johannes Marbach <n0-0ne+github@mailbox.org>
> MXTools: Avoid releasing null pointer to fix crash on M1 simulator

- CHANGES.rst
- MatrixSDK/Crypto/Data/MXEncryptedAttachments.m
This uses the existing `MXBase64Tools` to trim the `=` padding from the base64 encoded string. The reinsertion of the padding prior to decoding was already implemented (line [224](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/MatrixSDK/Crypto/Data/MXEncryptedAttachments.m#L224) in the same file).
Closes: vector-im/element-ios#4172
Signed-off-by: Johannes Marbach <n0-0ne+github@mailbox.org>
> Remove padding from base64 encoded `iv` value

- CHANGES.rst
- MatrixSDK/Data/MXUser.m
- changelog.d/1060.bugfix
This PR addresses issue #1045 where users' displaynames and avatar URLs can be nulled out on receipt of an old m.room.member event.
> Check for nil in MXRoom.updateWithRoomMember

- CHANGES.rst
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/MXBackgroundSyncService.swift
- MatrixSDK/Background/Store/MXSyncResponseStore.swift
- MatrixSDK/Background/Store/MXSyncResponseStoreManager.swift
- MatrixSDK/Background/Store/Model/MXSyncResponseStoreMetaDataModel.swift
- MatrixSDK/Background/Store/SyncResponseFileStore/MXSyncResponseFileStore.swift
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXAsyncTaskQueue.swift
- MatrixSDKTests/MXAsyncTaskQueueTests.swift
- MatrixSDKTests/MXBackgroundSyncServiceTests.swift
Fix vector-im/element-ios#4074
So that we will not lose e2ee keys received by the push extension.
> MXBackgroundService: Keep all cached sync responses until there are processed by MXSession

- CHANGES.rst
- MatrixSDK/MXSession.m
Fix vector-im/element-ios/issues/4202.
The `start()` method locked the `asyncTaskQueue` forever preventing next call of `resume()` from resuming the sync stream.
> MXSession: Fix deadlock regression in `resume()`

- CHANGES.rst
- MatrixSDK/Data/MXRoomMembers.h
- MatrixSDK/Data/MXRoomMembers.m
- MatrixSDK/Data/MXRoomState.m
- MatrixSDKTests/MXRoomStateTests.m
Fix vector-im/element-ios/issues/4204
Fix a regression introduced by https://github.com/matrix-org/matrix-ios-sdk/pull/1040.
While paginating, the kept MXRoomState instance could be released, creating a bad view of room members. 
Remove the bad dependency to MXRoomState to avoid any retain cycle.
> MXRoomMembers: Fix wrong view of room members when paginating

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
This PR prepares the release of MatrixSDK v0.18.9.
Notes:
- This PR targets `release/0.18.9/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.18.9/master` into `master` to tag the release.
--- …
> Release 0.18.9

- CHANGES.rst
- MatrixSDK/Utils/MXHTTPClient.m
- MatrixSDK/Utils/MXHTTPOperation.h
- MatrixSDK/Utils/MXHTTPOperation.m
fix https://github.com/vector-im/element-ios/issues/4206
> SDK: Expose the HTTP response in MXHTTPOperation

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MatrixSDK.h
- MatrixSDK/Space/MXSpace.swift
- MatrixSDK/Space/MXSpaceChildContent.h
- MatrixSDK/Space/MXSpaceChildContent.m
- MatrixSDK/Space/MXSpaceChildInfo.swift
- MatrixSDK/Space/MXSpaceChildSummaryResponse.h
- MatrixSDK/Space/MXSpaceChildSummaryResponse.m
- MatrixSDK/Space/MXSpaceChildrenRequestParameters.swift
- MatrixSDK/Space/MXSpaceChildrenResponse.h
- MatrixSDK/Space/MXSpaceChildrenResponse.m
- MatrixSDK/Space/MXSpaceChildrenSummary.swift
- MatrixSDK/Space/MXSpaceService.swift
- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXSpaceChildContentTests.swift
- MatrixSDKTests/MXSpaceServiceTest.swift
Support [MSC2946](https://github.com/matrix-org/matrix-doc/pull/2946).
vector-im/element-ios/issues/4068
> Spaces: Add support for spaces Summary API

- CHANGES.rst
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/MXSession.m
Fix vector-im/element-ios/issues/3807
We know the problem is around a bad value of `hasLoadedAllRoomMembersForRoom`. The SDK can believe that it had all room members before encrypting a message and sharing the key. This is wrong in some cases.
I failed to reproduce the issue but `hasLoadedAllRoomMembersForRoom` is set to YES only in 2 places. In this PR, I removed the one made for optimisation when lazy loading of room members is not used. It is safe to remove this optimisation as we should run mostly with LL on.
The root issue is race condition on `MXSession.syncWithLazyLoadOfRoomMembers`, which value may be not the expected one. It will be managed separately in https://github.com/vector-im/element-ios/issues/4254.
A clear cache is mandatory to clean all stored …
> MXCrypto: Disable optimisation on room members list to make sure we share keys to all

- CHANGES.rst
- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXToolsTests.m
Fix vector-im/element-ios#4258
It also fixes tests in MatrixKit as reported at https://github.com/matrix-org/matrix-ios-kit/pull/804.
MatrixKit tests:
MatrixSDK tests:
> MXTools: Fix bad linkification of matrix alias and URL 

- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXToolsTests.m
Fix https://github.com/vector-im/element-ios/issues/4258
This time there is no compromise. Disabled tests pass now. There are more tests, include one for the original GH issue where `@bob:matrix.org.` must not be considered as a valid matrix id.
Visualisation of the new `MATRIX_HOMESERVER_DOMAIN_REGEX `: https://regexper.com/#%5BA-Z0-9%5D%2B%28%28%5C.%7C%5C-%29%5BA-Z0-9%5D%2B%29%7B0%2C%7D%28%3A%5B0-9%5D%7B2%2C5%7D%29%3F
> MXTools: Fix bad linkification of matrix alias and URL for real

- CHANGES.rst
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
to track vector-im/element-ios/issues/4921
Logs we get:
```
2021-05-03 11:06:50.882880+0200 Riot[33542:3706384] [MXFileStore] logFiles: Files in /private/var/mobile/Containers/Shared/AppGroup/1BA58BA0-0EE3-496C-A30A-3FAACE58A0C9/MXFileStore/@Manu:matrix.org:
2021-05-03 11:06:50.986452+0200 Riot[33542:3706384] [MXFileStore] logFiles:     - filters: 378 bytes
2021-05-03 11:06:50.986709+0200 Riot[33542:3706384] [MXFileStore] logFiles:     - MXFileStore: 48 KB
2021-05-03 11:06:50.986899+0200 Riot[33542:3706384] [MXFileStore] logFiles:     - groups: 64 bytes
2021-05-03 11:06:50.987056+0200 Riot[33542:3706384] [MXFileStore] logFiles:     - users: 160 bytes
2021-05-03 11:06:50.987207+0200 Riot[33542:3706384] [MXFileStore] logFiles:     - users/33: 569 bytes
2021-05-03 11:06:50.987356+0200 …
```
> MXFileStore: Logs all files when a data corruption is detected

- CHANGES.rst
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Data/MXEventTimeline.h
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDK/MXSession.h
- MatrixSDKTests/MXCryptoTests.m
Finish the work started in #1091.
Decryptions do not happen anymore on the main thread.
Synchronous decryption methods are marked as deprecated. 
This makes the app much more reactive.
> End of the removal of decryption on the main thread

- CHANGES.rst
- MatrixSDK/Aggregations/MXAggregatedEditsUpdater.m
- MatrixSDK/Aggregations/MXAggregatedReferencesUpdater.m
- MatrixSDK/Aggregations/MXAggregations.m
- MatrixSDK/Crypto/Algorithms/MXDecrypting.h
- MatrixSDK/Crypto/Algorithms/MXEventDecryptionResult.h
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Data/MXEventTimeline.h
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomSummary.h
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXAggregatedEditsTests.m
- MatrixSDKTests/MXBackgroundSyncServiceTests.swift
- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/MXRoomSummaryTests.m
Fix https://github.com/vector-im/element-ios/issues/4306.
Fix vector-im/element-ios/issues/4322 in https://github.com/matrix-org/matrix-ios-sdk/pull/1091/commits/6bfeee516849eeba1e60a01f1ae455f095cb3c3c
Events are now asynchronously decrypted upstream, where upstream can be:
- during the sync response parsing
- during pagination
- during SDK data loading for MXRoomSummary.lastMessageEvent
This means we can remove latter calls of [MXSession decryptEvent:] that is synchronous and called mostly on the main thread.
On my account, an initial sync took 12.4 seconds on the main thread in the call of [MXSession decryptEvent:]. Now decryption takes 11s but on the decryption thread.
This change is more noticeable on incremental syncs, specially on the app restart, where decryption does not steal …
> MXCrypto: Move decryptions out of the main thread

- CHANGES.rst
- MatrixSDK/Data/MXEventTimeline.m
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomSummary.h
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXRoomSummaryTests.m
Fix vector-im/element-ios/issues/4307.
On my account, time spent to decrypt events from an initial sync is 2.8 seconds with this PR instead of 10.7s (it was 12.4s in 1.3.9). It decrypts 467 events instead of 2083 before.
This PR also removes useless paginations made to fix last room message.
> Remove useless decryptions on /sync

- CHANGES.rst
- MatrixSDK/VoIP/MXCall.m
Fix vector-im/element-ios#4337
> VoIP: Check Remote partyId for select_answer Events

- MatrixSDK/MXEnumConstants.m
For some reason Element ios still uses /_matrix/media/v1 endpoints. These are outdated and not in the spec anymore. They have been replace by /_matrix/media/r0 ( https://matrix.org/docs/spec/client_server/r0.6.1#id67 ).
I grepped this repository and found this one occurrence and replaced it. There was one other instance "_matrix/media/v1/identicon/%40mxbob" in MatrixSDKTests/MXMyUserTests.m, but I left it at v1 because indenticon is not in the spec. Tell me if I should update this too.
I don't have an iOS device and could not even build the repository to test it, so please review carefully :).
Signed-off-by: Timo Kösters <timo@koesters.xyz>
> fix: update media/v1 to media/r0

- CHANGES.rst
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
which what element does now with recent changes on its navigation.
At
https://github.com/vector-im/element-ios/blob/v1.3.9/Riot/Modules/Common/Recents/DataSources/RecentsDataSource.m#L166, `self.mxSession.crypto` used to be nil at startup. With the new navigation, it is no more nil but the crypto and backup is not fully started. Before this commit, it reset the backup on every startup.
> MXKeyBackup: Do not reset the backup if forceRefresh() is called too early

- MatrixSDK/MXSession.m
It will fix tests that are reopening sessions in loop while new data is coming.
It will not change behavior of MatrixKit nor EI. They call it only on logout.
The issue came during this sprint with the fix of this cache in https://github.com/matrix-org/matrix-ios-sdk/pull/1101.
> MXSession: Clear initial sync cache on MXSession.close()

- CHANGES.rst
- MatrixSDK/MXSession.m
Fix vector-im/element-ios/issues/4417
The root cause of the issue is a race condition in the MXSession pause management between the sdk state machine and the kit state machine.
The SDK was blocked and dead in MXSessionStateSyncInProgress state. The kit thought it does not need to resume it on app resume.
This fix is very related on how the kit and the sdk work together. But it could make sense in a more general manner.
I was able to reproduce the issue ("[MXSession] The connection has been cancelled.") by adding a delay of 25s in /sync response. Then, if you background the app just after starting it, you will hit this case.
> MXSession: Fix app that can fail to resume

- CHANGES.rst
- build.sh
Note: The `-debug-symbols` arg requires an absolute path. BCSymbolMap files have a UUID filename, hence the wildcard. There should only ever be one per XCArchive.
Fixes #1122.
> Include debug symbols in XCFramework output

- MatrixSDK/Crypto/Dehydration/MXDehydrationManager.m
- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/MatrixSDKTestsData.h
- MatrixSDKTests/MatrixSDKTestsData.m
More smaller tests showed that the dehydration was not working as expected. There were 2 issues: the signature computation reported [here](https://github.com/matrix-org/matrix-ios-sdk/pull/1117#discussion_r649641475) and the signature format sent with OTK.
Some tests did not work because the session was started before the rehydration. I added a new helper `loginUserOnANewDevice` with several parameters to match the needs here.
> Fix dehydration

- CHANGES.rst
- MatrixSDK/Crypto/Recovery/MXRecoveryService.h
- MatrixSDK/Crypto/Recovery/MXRecoveryService.m
Useful for vector-im/element-ios/issues/4430.
> MXRecoveryService: Expose checkPrivateKey to validate a private key

- CHANGES.rst
- MatrixSDK/MXSession.m
It affects all new logged in users since 0.19.0 and https://github.com/matrix-org/matrix-ios-sdk/commit/38df17fe6a6013b91f493a8c2d9c6db9fcb4a1da.
> MXSession.homeserverWellknown was no more computed

- CHANGES.rst
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXSessionTests.m
fix https://github.com/vector-im/element-ios/issues/#4489.
I also added a commit to refresh the wellknown on every start to get latest services available on the server.
> MXSDKOptions: Add wellknownDomainUrl to customise the domain for wellknown

- CHANGES.rst
- MatrixSDK/Contrib/Swift/Data/MXRoom.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
Added support for BlurHash (https://github.com/woltapp/blurhash) to MXRoom.sendImage() for MSC2448
> Initial support for MSC 2448 (BlurHash)

- CHANGES.rst
- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
This method expects the other device ID as a param, not the other
user ID
Fixes https://github.com/vector-im/element-ios/issues/4463
> Fix self verification with QR code

- CHANGES.rst
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStoreMetaData.h
- MatrixSDK/Data/Store/MXFileStore/MXFileStoreMetaData.m
- MatrixSDK/Data/Store/MXStore.h
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXTools.h
- MatrixSDK/Utils/MXTools.m
Draft for now as I have a couple of questions.
Add `maxUploadSize:failure:` to `MXRestClient` and stores the size in `MXSession`.
Pass a target file size to `MXTools` and use `AVAssetExportPreset3840x2160` when transcoding.
> Improve video transcoding quality

- CHANGES.rst
- MatrixSDK/Contrib/Swift/Data/MXRoom.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Utils/MXTools.h
- MatrixSDK/Utils/MXTools.m
Slow motion videos are returned from the photos picker as `AVComposition` objects.
- Add `sendVideoAsset:withThumbnail:localEcho:success:failure:` to support `AVComposition`.
- Call this new method from `sendVideo:withThumbnail:localEcho:success:failure:`.
- Use the `AVAsset` when transcoding in `MXTools`.
Part of https://github.com/vector-im/element-ios/pull/4541 along with https://github.com/matrix-org/matrix-ios-kit/pull/848
> Add support for sending slow motion videos

- CHANGES.rst
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Utils/MXUIKitBackgroundTask.m
Fixes vector-im/element-ios/issues/4579
to avoid to keep the realm internal lock until the app resumes. Thus, other components (Notification Extension Service, Share Extension, ...) will not be blocked by this lock.
Logging is changed a bit. We now rely on logs made by `MXBackgroundTask`
Now:
```
2021-07-21 10:29:44.019804+0200 Riot[4534:558069]  [MXBackgroundTask] Start background task #3892 - [MXRealmCryptoStore] performSessionOperationWithGroupSessionWithId
2021-07-21 10:29:44.021086+0200 Riot[4534:558069]  [MXBackgroundTask] Background task [MXRealmCryptoStore] performSessionOperationWithGroupSessionWithId started with app state: active and estimated background time remaining: undetermined
2021-07-21 10:29:44.036865+0200 Riot[4534:558069]  [MXBackgroundTask] Stop background task #3892 …
```
> MXCryptoStore: Use UI background task to make sure that write operations complete

- CHANGES.rst
- MatrixSDK.podspec
- MatrixSDK/Contrib/Swift/Data/MXRoom.swift
- MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXSendReplyEventDefaultStringLocalizations.h
- MatrixSDK/Data/MXSendReplyEventDefaultStringLocalizations.m
- MatrixSDK/Data/MXSendReplyEventStringsLocalizable.h
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MatrixSDKVersion.m
This PR prepares the release of MatrixSDK v0.19.5.
Notes:
- This PR targets `release/0.19.5/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.19.5/master` into `master` to tag the release.
--- …
> Release 0.19.5

- MatrixSDK/Crypto/Data/MXEncryptedAttachments.h
- MatrixSDK/Crypto/Data/MXEncryptedAttachments.m
Fixes vector-im/element-ios/issues/4577 - Decrypt attachments on a background thread.
> Decrypt attachments on a background thread.

- .github/workflows/ci-lint.yml
- .github/workflows/ci-unit-tests.yml
- CHANGES.rst
Matches vector-im/element-ios#4581 to allow us to re-run only failed jobs, instead of having to run them all again.
> Separate CI jobs into individual actions

- CHANGES.rst
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
Fix vector-im/element-ios/issues/4594
to avoid dead state on an initial sync.
There is a db version update to fix possible wrong value for MXRealmOlmAccount.cryptoVersion.
> MXCryptoStore: Keep current store version after resetting data

- CHANGES.rst
- MatrixSDK/MXSession.m
The `kMXSessionAccountDataDidChangeIdentityServerNotification` notification was being posted every time the app launched (provided the identity server ToS had been accepted), which in turn meant `MXKContactManager` would refresh its local contacts on every launch too.
In some circumstances this could be a small contributor to https://github.com/vector-im/element-ios/issues/4484.
> Stop unnecessary contact refeshes in Element

- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MXSession.m
- MatrixSDK/Space/MXSpace.swift
- MatrixSDK/Space/MXSpaceService.swift
Handle https://github.com/vector-im/element-ios/issues/4509, https://github.com/vector-im/element-ios/issues/4495
Part of https://github.com/vector-im/element-ios/issues/4503
> [Spaces] Show spaces in left panel #4509

- CHANGES.rst
- MatrixSDK/JSONModels/Login/MXLoginSSOFlow.h
- MatrixSDK/JSONModels/Login/MXLoginSSOFlow.m
- MatrixSDK/JSONModels/Login/MXLoginSSOIdentityProviderBrand.h
- MatrixSDKTests/MXAuthenticationSessionUnitTests.swift
- changelog.d/4362.api
Part of vector-im/element-ios#4362
> Stable ids for MSC 2858

- MatrixSDK/Data/MXRoomState.m
- changelog.d/4678.bugfix
Fix vector-im/element-ios#4678
> MXRoomState: Fix a crash in `aliases` getter

- MatrixSDK/Crypto/MXOlmDevice.m
- changelog.d/4679.bugfix
Fix vector-im/element-ios#4679
> MXOlmDevice: Fix a crash in `sessionIdsForDevice` method

- CHANGES.rst
- MatrixSDK/Data/MXRoomSummaryUpdater.h
- MatrixSDK/Data/MXRoomSummaryUpdater.m
- MatrixSDKTests/MXRoomSummaryTests.m
- changelog.d/4609.change
Allows specified users to be excluded when computing the room's name and avatar. The new functions contain the implementation, with the older ones now calling into these.
Includes tests for the functions.
> Add excludingUserIDs parameter to displayname and avatar updater methods.

- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/NotificationCenter/MXNotificationCenter.h
- MatrixSDK/NotificationCenter/MXNotificationCenter.m
- changelog.d/4467.feature
These update to `MxNotificationCenter` are for new account notification settings and keywords support.
(https://github.com/vector-im/element-ios/issues/4467, https://github.com/vector-im/element-ios/issues/4468 and https://github.com/vector-im/element-ios/issues/4469 )
- Added `updatePushRuleActions` for updating rule actions.
- Added `addContentRuleWithMatchingRuleIdAndPattern` for creating content rules for keywords. An existing function existed but with a different behaviour. I added clarifying comment to each.
- RuleId is included in a number of requests as a path parameter. Keywords allows input from the user so can contain special characters(like whitespace) that needed to be encoded. So added the encoding for each of those apis.
> Account Notification Settings and Keywords.

- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
- changelog.d/4472.bugfix
Check the expiry of incoming verification requests and discard them
straight away if they're no longer valid.
Fixes https://github.com/vector-im/element-ios/issues/4472
> Don't show expired verification requests

- MatrixSDK/Utils/MXTools.h
- MatrixSDK/Utils/MXTools.m
- changelog.d/4479.change
As part of https://github.com/vector-im/element-ios/pull/4721, this adds a second version of `fileSizeToString` to `MXTools` that formats the file size using `NSByteCountFormatter` with the default settings. This gives a nicer string to read as it automatically chooses the appropriate number of significant figures to show, will localise better and will use multiples of 1000 rather than 1024 to match the system size calculation.
I would have updated `fileSizeToString:round:` to use `NSByteCountFormatter` however the `round` parameter wouldn't have a defined behaviour in this instance.
> Add a fileSizeToString method using NSByteCountFormatter.

- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- changelog.d/4804.bugfix
Fix https://github.com/vector-im/element-ios/issues/4804.
> MXCrossSigning.setupWithPassword failure block not called from the main thread

- MatrixSDK/Data/MXRoomSummary.h
- MatrixSDK/Data/MXRoomSummary.m
- changelog.d/4822.change
Adds `markAllAsReadLocally` method to `MXRoomSummary` class. Part of vector-im/element-ios#4822
> MXRoomSummary: `markAllAsReadLocally` method

- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- changelog.d/4834.bugfix
Part of vector-im/element-ios#4834
> MXSession: Introduce `pauseable` property

- MatrixSDK.podspec
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/Crypto/Dehydration/MXDehydrationService.m
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXOlmDevice.h
- MatrixSDK/Crypto/MXOlmDevice.m
- MatrixSDK/JSONModels/Sync/MXSyncResponse.h
- MatrixSDK/JSONModels/Sync/MXSyncResponse.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXRestClientTests.m
- MatrixSDKTests/MXSessionTests.m
- MatrixSDKTests/MatrixSDKTestsData.h
- MatrixSDKTests/MatrixSDKTestsData.m
- Podfile
- Podfile.lock
- changelog.d/4406.feature
Implements vector-im/element-ios/issues/4406 - Olm fallback key support. NB this PR requires the current development version of Olm (future 3.2.5 release presumably)
> Olm fallback key support

- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- changelog.d/4911.bugfix
Fix vector-im/element-ios#4911
> MXSession: Make `directRooms` atomic and copying

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
- changelog.d/4919.bugfix
This PR prepares the release of MatrixSDK v0.20.4.
Notes:
- This PR targets `release/0.20.4/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.20.4/master` into `master` to tag the release.
--- …
> Release 0.20.4

- MatrixSDK.podspec
- changelog.d/4939.change
Part of https://github.com/vector-im/element-ios/issues/4939.
There isn't anything in way of a changelog, so tested the following calls:
- **1:1 for WebRTC:** iOS / Web / Android
- **Jitsi:** iOS & Web & Desktop
> Update JitsiMeetSDK pod.

- MatrixSDK.podspec
- Podfile
- Podfile.lock
- changelog.d/4939.change
This updates Realm from 10.7.6 to 10.16.0. One note to make is that [v10.8.0](https://github.com/realm/realm-cocoa/releases/tag/v10.8.0) introduces a file format change which isn't backwards compatible. Otherwise I've checked:
- Integration tests for Crypto/Cross-signing/Dehydration and no additional tests fail (1 more seems to pass now).
- Sending messages from a new account
- Verifying that new account from an existing one (both sides)
- Creating a secure backup.
- Logging into an existing account.
Nothing to report from any of the above.
> Update Realm pod.

- MatrixSDK/Data/RoomList/MXRoomListDataFilterOptions.swift
- MatrixSDK/MXSession.h
- changelog.d/5083.bugfix
Required by https://github.com/vector-im/element-ios/pull/5087, fixes https://github.com/vector-im/element-ios/issues/5083.
> Fix room previews

- MatrixSDK/Utils/Media/MXMediaManager.m
- changelog.d/1281.bugfix
Caching operations would fail silently because cache was not initialized.
Signed-off-by: Frantisek Hetes f.hetes@gmail.com
> Initialize imagesCacheLruCache before caching

- MatrixSDK/Data/MXRoomSummaryUpdater.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- changelog.d/5080.bugfix
Fixes https://github.com/vector-im/element-ios/issues/5080
When a room has been upgraded with the device in the background, if a limited sync response comes in for that room a call to `MXRoomSummary`'s `resetRoomStateData` method is made. This recomputes the room state including the room's `create` event which was unhiding the room immediately after it had been hidden.
The PR fixes that and bumps the file store version to force all room state to be recomputed.
> Don't allow upgraded rooms that are hidden to become unhidden again.

- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDK/Data/MXRoomSummaryProtocol.h
- MatrixSDK/Data/RoomList/MXRoomListDataSortOptions.swift
- MatrixSDKTests/Mocks/MockRoomSummary.swift
- changelog.d/5105.bugfix
Part of vector-im/element-ios#5105
Ignores number of highlights, notifications and unreadCounts. Sorts according to only existence of them.
> Ignore number of highlights, notifications and unreads when sorting rooms

- MatrixSDK/Data/MXRoom.m
- changelog.d/5007.bugfix
Improves vector-im/element-ios#5007
> Fix Reply Event Content for just Thread-Aware Clients

- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- changelog.d/5127.bugfix
Fixes vector-im/element-ios#5127
This PR does two things:
- Allows a session to resume also from `paused` state. Actually this should fix the issue.
- Avoids a catchup request (sync request with a `serverTimeout` value `0`) being made after the session `paused` or `pauseRequested`. This is for the sake of the application state. As we cannot guarantee that a catchup request will get a response shortly, we don't want to make this request in a backgrounded app.
> Fix not resuming session

- MatrixSDK/Crypto/Data/MXKey.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDKTests/MXCryptoTests.m
- changelog.d/5120.bugfix
Storing full MXKey dictionary so we can use all fields when checking the signature.
Added integration test to exercise currently failing paths.
> Fixes vector-im/element-ios/issues/5120 - Fixed fallback key signature validation.

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
- changelog.d/1281.bugfix
- changelog.d/4893.feature
- changelog.d/4981.feature
- changelog.d/5007.bugfix
- changelog.d/5114.feature
- changelog.d/5155.bugfix
- changelog.d/5181.bugfix
- changelog.d/5194.bugfix
- changelog.d/5195.build
- changelog.d/5223.bugfix
This PR prepares the release of MatrixSDK v0.20.11.
Notes:
- This PR targets `release/0.20.11/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.20.11/master` into `master` to tag the release.
--- …
> Release 0.20.11

- MatrixSDK/ContentScan/Data/MXAntivirusScanStatusFormatter.h
- MatrixSDK/ContentScan/Data/MXEventScan.h
- MatrixSDK/ContentScan/Data/MXMediaScan.h
- MatrixSDK/ContentScan/Data/Store/MXEventScanStore.h
- MatrixSDK/ContentScan/Data/Store/MXMediaScanStore.h
- MatrixSDK/ContentScan/Data/Store/MXMediaScanStoreDelegate.h
- MatrixSDK/ContentScan/Data/Store/Realm/Event/MXRealmEventScanMapper.h
- MatrixSDK/ContentScan/Data/Store/Realm/Event/MXRealmEventScanStore.h
- MatrixSDK/ContentScan/Data/Store/Realm/Media/MXRealmMediaScanStore.h
- MatrixSDK/ContentScan/MXScanManager.h
- MatrixSDK/Crypto/Dehydration/MXDehydrationService.h
- MatrixSDK/Data/MXRoomNameDefaultStringLocalizer.h
- MatrixSDK/Data/MXRoomNameStringLocalizerProtocol.h
- MatrixSDK/Data/MXSendReplyEventDefaultStringLocalizer.h
- MatrixSDK/Data/MXSendReplyEventStringLocalizerProtocol.h
- MatrixSDK/Utils/Realm/MXRealmHelper.h
- MatrixSDK/VoIP/CallKit/MXCallKitAdapter.h
- MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m
- MatrixSDK/VoIP/CallKit/MXCallKitConfiguration.h
- changelog.d/5046.misc
This replaces all semantic import statements with classic ones. Semantic imports are currently not supported in Kotlin Multiplatform Mobile projects which makes the SDK unusable in these cases.
Fixes: vector-im/element-ios#5046
> Use classic instead of semantic imports

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Utils/MXTools.h
- MatrixSDK/Utils/MXTools.m
- changelog.d/4749.api
Part of https://github.com/vector-im/element-ios/issues/4749, this adds the ability to distinguish whether a video failed to encode or failed to send.
> Add an error parameter to the failure of convertVideoAssetToMP4:

- MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/JSONModels/Event/Content/MXEventContentPollStart.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/Room/Polls/PollAggregator.swift
- MatrixSDK/Room/Polls/PollBuilder.swift
- MatrixSDK/Room/Polls/PollModels.swift
- MatrixSDK/Utils/MXTools.m
- MatrixSDKTests/MXPollBuilderTests.swift
- MatrixSDKTests/MXPollRelationTests.m
* added poll start even type enum value, fixed poll question key path, made aggregator and models public
*  Made user identifier mandatory, defaulting maxSelections to 1 as per msc.
* Only listen to events relating to the original poll in the poll aggregator event listener.
* Better unstable prefix event type handling.
> Various poll tweaks.

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Data/MXRoomState.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/MatrixSDKVersion.m
- MatrixSDKTests/MXCryptoTests.m
This PR prepares the release of MatrixSDK v0.20.14.
Notes:
- This PR targets `release/0.20.14/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.20.14/master` into `master` to tag the release.
--- …
> Release 0.20.14

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/MXEnumConstants.h
- MatrixSDK/MXEnumConstants.m
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXAnalyticsDelegate.h
- MatrixSDK/Utils/Profiling/MXBaseProfiler.m
- MatrixSDK/Utils/Profiling/MXProfiler.h
- MatrixSDK/Utils/Profiling/MXTaskProfile.h
- MatrixSDK/Utils/Profiling/MXTaskProfile.m
- MatrixSDK/Utils/Profiling/MXTaskProfileName.h
- MatrixSDK/Utils/Profiling/MXTaskProfile_Private.h
- MatrixSDK/VoIP/MXCall.m
- changelog.d/5035.api
- changelog.d/5035.change
As part of https://github.com/vector-im/element-ios/issues/5035, this PR makes 2 changes.
- `MXAnalyticsDelegate` now provides specific methods per event reported as the new [matrix-analytics-events](https://github.com/matrix-org/matrix-analytics-events) schema should be followed more strictly.
- `MXTaskProfile` has been updated to use a single `MXTaskProfileName` enum instead of separate `name` and `category` strings in order to switch on the task name.
> Update MXAnalyticsDelegate and MXTaskProfile

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/JSONModels/Event/Content/MXEventContentLocation.h
- MatrixSDK/JSONModels/Event/Content/MXEventContentLocation.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- changelog.d/5298.feature
Added support for 
- old "m.location" events
- `m.asset` `type`
- both stable and undstable keys
> Static location sharing - part 2

- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.m
- changelog.d/5429.change
> Only count joined rooms when profiling sync performance.

- changelog.d/4883.build
- fastlane/Fastfile
As part of https://github.com/vector-im/element-ios/issues/4883, this PR updates to use Xcode 13.2 on CI.
> Update Fastfile to use Xcode 13.2 on CI.

- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Data/MXRoom.m
- changelog.d/5184.bugfix
Add some defensive coding when deciding to send encrypted or not in the room.
The decision is based only in the crypto store state (existence of a valid algorithm), instead of the room state.
The crypto store is more stable, only updated with supported alg and never reverted.
> Defense against encryption state issues

- MatrixSDK/MXSession.m
- changelog.d/5509.bugfix
Fixes https://github.com/vector-im/element-ios/issues/5509
A sync request could be cancelled whilst the app is in foreground (e.g. a screen that triggers the sync is deallocated), but this cancellation should not be pausing `MXSession`. Other types of failure correctly re-trigger the sync after some timeout.
> Do not pause MXSession if a sync request is cancelled

- MatrixSDK/Background/Store/MXSyncResponseStore.swift
- MatrixSDK/Background/Store/SyncResponseFileStore/MXSyncResponseFileStore.swift
- MatrixSDK/Data/EventTimeline/Room/MXRoomEventTimeline.m
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXServerNotices.m
- changelog.d/5426.change
Makes a couple of things:
- Avoids `event/(null)` requests and immediately fails them.
- Adds some error logs around `event/(null)` requests.
- Avoids session state back and forth when there is no cached sync responses.
- Adds another bg sync cache processing round in the session if new data received when processing an old one.
Part of vector-im/element-ios#5426
> Fixes for Background Sync Cache Processing

- MatrixSDK/Space/MXSpaceService.swift
- changelog.d/1350.bugfix
Fixes Thread 1: EXC_BAD_ACCESS crash that would occur whenever multiple concurrent threads would attempt to mutate `spacesPerId` at the same time.
Signed-off-by: Frantisek Hetes f.hetes@gmail.com
> 🐛 Protect the `spacesPerId` variable by a barrier

- MatrixSDK/Data/RoomList/CoreData/MXCoreDataRoomListDataFetcher.swift
- MatrixSDK/Data/RoomSummaryStore/CoreData/MXCoreDataRoomSummaryStore.swift
- MatrixSDK/Data/RoomSummaryStore/CoreData/Models/MXRoomSummaryMO.swift
- changelog.d/5519.bugfix
Fix vector-im/element-ios#5519
> This property can be set with [managedObjectResultType](https://developer.apple.com/documentation/coredata/nsfetchrequestresulttype/1506452-managedobjectresulttype) and thereby implement a partial faulting (whereby only some of the properties are populated) of the returned objects, as well as the [dictionaryResultType](https://developer.apple.com/documentation/coredata/nsfetchrequestresulttype/1506237-dictionaryresulttype) to define what properties are included in the resulting [NSDictionary](https://developer.apple.com/documentation/foundation/nsdictionary).
Documentation for `NSFetchRequest.propertiesToFetch` says above, but `managedObjectResultType` it doesn't work properly on some devices, seems mostly on iOS 12.
Will also fix …
> Core Data Fix Parameterized Fetch Requests

- MatrixSDK/ThreePidAdd/MX3PidAddManager.m
- changelog.d/3562.bugfix
Fixes issue https://github.com/vector-im/element-ios/issues/3562
HttpClient was immediately released at the end of the block resulting in request cancelation.
> Fix add phone number validation through custom URL

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/Store/SyncResponseFileStore/MXSyncResponseFileStore.swift
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Data/RoomSummaryStore/CoreData/MXCoreDataRoomSummaryStore.swift
- MatrixSDK/Data/RoomSummaryStore/File/MXFileRoomSummaryStore.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/Space/MXSpaceFileStore.swift
- MatrixSDK/Utils/Categories/FileManager+AppGroupContainer.swift
- MatrixSDK/Utils/Categories/FileManager+Backup.swift
- MatrixSDK/Utils/MXLogger.m
- changelog.d/5498.change
Fixes https://github.com/vector-im/element-ios/issues/5498
As listed in [documentation](https://developer.apple.com/documentation/foundation/optimizing_app_data_for_icloud_backup), the iOS is automatically backing up a number of folders to iCloud / iTunes, including `<AppHome>/Documents/` and `<AppHome>/Library/Application Support/`. Additionally the Matrix SDK stores files in `AppGroup` containers (potentially shared between app and an extension), which are also automatically backed up to iCloud. These folders include data for rooms, spaces etc.
To opt-out of backups completely, each url needs to be explicitely marked with `isExcludedFromBackupKey` (this is applied recursively). I converted all `createDirectory` calls with a custom method, which automatically does this when creating a …
> Exclude all files and directories from iCloud backup

- .github/workflows/nightly.yml
- changelog.d/1352.build
Since nightly script ran into rate limit and doesn't get far. Progress on https://github.com/matrix-org/matrix-ios-sdk/issues/1352
> 🐛Pass `--no-rate-limit` flag to start script during nightly build script

- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDKTests/MXCryptoTests.m
- changelog.d/5564.bugfix
Closes https://github.com/vector-im/element-ios/issues/5564.
The source of truth for the encryption of a room is back to `MXRoomSummary.isEncrypted`, which is a rollback of #1358.
The additional change of this PR is that on every send, there is a check if this value is aligned with the one in the crypto store.
There is also some error logs if something tries to reset `MXRoomSummary.isEncrypted`.
> Fix e2ee regression introduced by #1358

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDK/MatrixSDKVersion.m
- MatrixSDKTests/MXCryptoTests.m
- changelog.d/5564.bugfix
This PR prepares the release of MatrixSDK v0.22.1.
Notes:
- This PR targets `release/0.22.1/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.22.1/master` into `master` to tag the release.
--- …
> Release 0.22.1

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/Data/EventTimeline/Thread/MXThreadEventTimeline.swift
- MatrixSDK/MatrixSDKVersion.m
- MatrixSDK/Threads/MXThreadingService.swift
- MatrixSDK/Utils/MXMulticastDelegate.swift
- changelog.d/5675.bugfix
This PR prepares the release of MatrixSDK v0.22.3.
Notes:
- This PR targets `release/0.22.3/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.22.3/master` into `master` to tag the release.
--- …
> Release 0.22.3

- MatrixSDK/Data/EventTimeline/Room/MXRoomEventTimeline.m
- MatrixSDK/Data/EventTimeline/Thread/MXThreadEventTimeline.swift
- MatrixSDK/Threads/MXThreadingService.swift
- MatrixSDKTests/MXThreadingServiceTests.swift
- changelog.d/5694.change
Improve `MXThreadingServiceDelegate` by adding a new method for thread creation, with a `direction` property.
> MXThreadingService: Add thread creation delegate method

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/Data/EventTimeline/Room/MXRoomEventTimeline.m
- MatrixSDK/Data/EventTimeline/Thread/MXThreadEventTimeline.swift
- MatrixSDK/MatrixSDKVersion.m
- MatrixSDK/Threads/MXThreadingService.swift
- MatrixSDKTests/MXThreadingServiceTests.swift
- changelog.d/5694.change
This PR prepares the release of MatrixSDK v0.22.4.
Notes:
- This PR targets `release/0.22.4/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.22.4/master` into `master` to tag the release.
--- …
> Release 0.22.4

- MatrixSDK/Data/MXRoomState.m
- changelog.d/4949.bugfix
Should fix https://github.com/vector-im/element-ios/issues/4949
I'm not 100% sure it's okay to init the object this way (or at this moment rather), but this [new] call seems to be the only way to have a memberCounts object with non-initialized properties
> Fix room state membersCount not being set in time

- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/Space/MXRoomAliasAvailabilityChecker.swift
- MatrixSDKTests/MXRoomAliasAvailabilityCheckerResultTests.swift
- MatrixSDKTests/MXSpaceChildContentTests.swift
- MatrixSDKTests/MXSpaceServiceTest.swift
- changelog.d/5233.feature
needed for https://github.com/vector-im/element-ios/issues/5233
> SP4: Space Settings

- MatrixSDK/Data/EventTimeline/Thread/MXThreadEventTimeline.swift
- changelog.d/5749.bugfix
Part of vector-im/element-ios#5749.
Decrypts events fetched from server before adding to the timeline.
> Thread Notifications Fixes

- MatrixSDK/Data/EventTimeline/Thread/MXThreadEventTimeline.swift
- MatrixSDK/Data/Filters/MXRoomEventFilter.h
- MatrixSDK/Data/Filters/MXRoomEventFilter.m
- MatrixSDK/Threads/MXThreadingService.swift
- changelog.d/5705.change
Fix vector-im/element-ios#5705
This is just updating some property names right now, to be more aligned with stable values, which i'll update later in another PR.
> `MXRoomEventFilter`: New property names for relation types and senders

- MatrixSDK/Data/Filters/MXRoomEventFilter.m
- MatrixSDK/JSONModels/Event/Content/MXEventContentRelatesTo.m
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/JSONModels/MXMatrixVersions.m
- changelog.d/5791.change
Fixes vector-im/element-ios#5791.
This will cause all thread events to move to the main timeline of a room. Will be based on `develop` after the PR merged.
> Threads: Stable Values

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDKTests/MXRoomTests.m
- changelog.d/5807.change
Relates to https://github.com/vector-im/element-ios/issues/5807
> API to ignore the sender of a room invite before the room is joined

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MatrixSDKVersion.m
- MatrixSDKTests/MXRoomTests.m
- changelog.d/5807.change
This PR prepares the release of MatrixSDK v0.22.6.
Notes:
- This PR targets `release/0.22.6/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.22.6/master` into `master` to tag the release.
--- …
> Release 0.22.6

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/MXBackgroundSyncService.swift
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/MXOlmDevice.h
- MatrixSDK/Crypto/MXOlmDevice.m
- MatrixSDKTests/MXCryptoTests.m
- changelog.d/5835.bugfix
Fixes https://github.com/vector-im/element-ios/issues/5835
This solution is not perfect and bloats the `decrypt` API even further, but is the most straightforward way to fix the issue where an edit event is first decrypted and then the original event with the same content (because it has been aggregated) is being decrypted and fails, resulting in the message being dropped from the timeline.
In this solution we use the `isEditEvent` flag as yet another component of `messageIndexKey` to determine whether this is likely a replay attack or not.
> Distinguish between original and edit message when preventing replay attacks

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/MXBackgroundStore.swift
- MatrixSDK/Data/EventsEnumerator/MXEventsByTypesEnumeratorOnArray.h
- MatrixSDK/Data/EventsEnumerator/MXEventsByTypesEnumeratorOnArray.m
- MatrixSDK/Data/EventsEnumerator/MXEventsEnumerator.h
- MatrixSDK/Data/EventsEnumerator/MXEventsEnumeratorOnArray.h
- MatrixSDK/Data/EventsEnumerator/MXEventsEnumeratorOnArray.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.m
- MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
- MatrixSDKTests/Data/EventsEnumerator/EventsEnumeratorDataSourceStub.swift
- MatrixSDKTests/Data/EventsEnumerator/MXEventsByTypesEnumeratorOnArrayTests.swift
- MatrixSDKTests/Data/EventsEnumerator/MXEventsEnumeratorOnArrayTests.swift
- MatrixSDKTests/Data/Store/MXMemoryStore/MXMemoryRoomStoreTests.swift
- changelog.d/5848.bugfix
Fixes https://github.com/vector-im/element-ios/issues/5848
The previous implementation of event enumerator used in the timeline would copy the messages from a store (memory or file) and itterate through this list. If however an event got edited, it would only update the version in store and not its equivalent in the enumerator, meaning that once the pagination fetched the edited event, it would grab the original unedited event.
As the root cause of this issue is multiple sources of truth, the solution is to move closer to a single source of truth: the enumerator is only given an initial list of event identifiers and a data source. When the time comes to grab a list of events, the enumerator will request the most recent versions of the events from the data source, ensuring that any changes …
> Paginated events always show the most recent edit

- MatrixSDK/Data/EventTimeline/Thread/MXThreadEventTimeline.swift
- changelog.d/5840.bugfix
Fixes vector-im/element-ios#5840
Fixes vector-im/element-ios#5832 (only empty screen case).
> Fix thread events ordering

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXRoomAccountDataUpdater.m
- MatrixSDK/Data/MXRoomSummaryUpdater.m
- MatrixSDK/MXSession.h
- changelog.d/5805.bugfix
As part of https://github.com/vector-im/element-ios/issues/5805 this fixes some memory issues discovered.
In particular `MXRoomOperation`'s block would often have a strong reference to the operation that owned it, causing them to hang around even after being removed from the `orderedOperations` array.
Additionally, `MXRoomAccountDataUpdater` and `MXRoomSummaryUpdater` now use weak map tables to avoid strong references that hold on to `MXRoom` instances forever.
> Fix MXRoom retain cycles.

- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
- MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
- MatrixSDK/Data/Store/MXStore.h
- MatrixSDKTests/MXFilterTests.m
- changelog.d/5873.bugfix
Partially resolves https://github.com/vector-im/element-ios/issues/5873, client-side change https://github.com/vector-im/element-ios/pull/5882
When investigating why the app triggers an initial sync twice I found that at the point of the second sync the app does not have any filters stored on local disk. Technically this qualifies as "filter ID is different from last sync" because it cannot be matched to anything in store, which triggers a complete cache wipe and trigger of another sync.
I could not determine from the rageshakes why the filters were missing, the options are really a failure to save or a failure to load. We do not currently log errors with either. To improve this I swaped `NSKeyUnarchiver/Archiver` APIs to the newer ones (iOS11+) which report back an error. Using this API …
> Log when filters cannot be saved or loaded

- MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m
- changelog.d/5189.bugfix
Resolves https://github.com/vector-im/element-ios/issues/5189
As mentioned in the ticket, this issue can be reproduced more directly by:
1. Recieve a call anywhere in the app
2. Accept the call from the in-app overlay header (no need to interact with the timeline)
3. Hang up the call
=> The app hungup the call, but the system still shows it as ongoing.
I must have repeated this over 200x, experiencing this issue about 10% of the times, without doing anything obviously different.
It does not help that the Matrix SDK ignores all errors when requesting CallKit transactions. In fact once they are logged, two errors in particular happen at different times when hanging up the call: `CXErrorCodeRequestTransactionErrorUnknownCallProvider` and `CXErrorCodeRequestTransactionErrorUnknownCallUUID`. …
> Recreate CXProvider if a call cannot be hung up

- MatrixSDK/Data/MXRoom.m
- changelog.d/5906.bugfix
Relates to https://github.com/vector-im/element-ios/issues/5906
For some reason we are writing to disk on every character typed when composing a message, i.e. we are writing multiple types per second for something that is quite ephemeral. For instance if the app crashed whilst a message was being typed, at most a few sentences would be lost. It does not seem necessary to commit on every single character typed and it will improve the typing performance a bit if we dont.
> Do not commit to file store after typing a single character

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/JSONModels/MXRoomAliasResolution.h
- MatrixSDK/JSONModels/MXRoomAliasResolution.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/Space/MXRoomAliasAvailabilityChecker.swift
- MatrixSDKTests/MXRestClientTests.m
- changelog.d/4858.change
Relates to https://github.com/vector-im/element-ios/issues/4858
The [directory/room/<room_alias>](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3directoryroomroomalias) endpoint used to convert room alias to a room identifier returns a list of servers that are aware of the room. In the existing SDK implementation this list of servers is never stored (we only grab the identifier), meaning that if we later want to join this room from another home server, it is no longer possible without the knowledge of the servers.
To solve this on the SDK side, store both `room_id` as well as list of `servers` in a new `MXRoomAliasResolution` object which can be fetched via `resolveRoomAlias` endpoint, replacing the simpler `roomIdForAlias`
> Return room identifier and known servers when resolving alias

- MatrixSDK/Data/MXEventListener.h
- MatrixSDK/Data/MXRoomSummary.m
- changelog.d/5058.bugfix
This is the second part of a fix for a triple-leak involving `MXKRoomDataSource`, `MXRoomEventTimeline` and `MXEventListener`. The first part can be found in vector-im/element-ios#5923.
There are two issues here:
1. When listening for events on `timeline`, `MXRoomSummary` strongly captures the latter in its own event handler block.
2. The `sender` property on `MXEventListener` is strong and, in all cases I was able to locate, the listener is stored in an array on the object that is passed in as `sender`, creating a retain cycle.
I haven't found concrete steps to reproduce the leak (and the memory graph debugger is also not 100% reliable) but the cycle frequently shows after having entered, left and posted in rooms a few times.
Relates to: vector-im/element-ios#5058
> Fix retain cycles in MXEventListener & MXRoomSummary

- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/EventStream/MXEventStreamService.swift
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/MXRoomSummaryTests.m
- changelog.d/5938.bugfix
Accompanies https://github.com/vector-im/element-ios/pull/5945
> Move  `handleRoomKeyEvent` logic back to `MXSession`.

- MatrixSDK/Data/RoomList/CoreData/MXCoreDataRoomListDataFetcher.swift
- MatrixSDK/Data/RoomList/CoreData/MXCoreDataRoomListDataManager.swift
- MatrixSDK/Utils/MXLog.h
- MatrixSDK/Utils/MXLog.swift
- MatrixSDK/Utils/MXLogObjcWrapper.h
- MatrixSDK/Utils/MXLogObjcWrapper.m
- MatrixSDKTests/MXCoreDataRoomListDataManagerUnitTests.swift
Add macros and `MXLog` methods to log assertions that "crash" the app in DEBUG mode. This is a useful tool during development: wherease merely logging to console is easy to miss, an assertion forces the developer to debug a given issue whilst the context is still in place.
> Add assertion failure macros

- MatrixSDK/Crypto/Verification/Data/MXTransactionCancelCode.h
- MatrixSDK/Crypto/Verification/Data/MXTransactionCancelCode.m
- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.h
- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest.m
Fixes https://github.com/vector-im/element-ios/issues/4470
When a client receives a verification request acceptance it needs to notify other devices that it was accepted so they can dismiss their requests.
> Notify other devices of verification acceptance

- MatrixSDK.podspec
- changelog.d/6018.change
Remove arm64 simulator exclusion.
Part of https://github.com/vector-im/element-ios/issues/6018
> Update JitsiMeetSDK to 5.0.2.

- MatrixSDK/Data/EventsEnumerator/MXEventsByTypesEnumeratorOnArray.h
- MatrixSDK/MXRestClient.h
- changelog.d/pr-1440.misc
Related to https://github.com/vector-im/element-ios/pull/6032
> Fix some warnings.

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.h
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/KeySharing/Data/MXSharedHistoryKeyRequest.swift
- MatrixSDK/Crypto/KeySharing/MXSharedHistoryKeyManager.swift
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- MatrixSDKTests/Crypto/KeySharing/MXSharedHistoryKeyManagerUnitTests.swift
- MatrixSDKTests/TestPlans/UnitTests.xctestplan
- changelog.d/4947.change
Relates to https://github.com/vector-im/element-ios/issues/4947 which is an implementation of https://github.com/matrix-org/matrix-doc/pull/3061
After [previously](https://github.com/matrix-org/matrix-ios-sdk/pull/1444) storing `sharedHistory` flag for inbound Megolm sessions, add new mechanism that will share these inbound keys with a user invited to the current room.
Because the current Rest API allows sharing of only one key at a time and because sharing keys always increases the amount of potential issues (e.g. how far in the past?, shared with which devices?, do we retry if sharing fails?), the scope of this feature is currently limited to only share the "immediate context", which is arbitrarily interpreted as keys for the last 20 messages in this room. This should achieve the …
> Share Megolm session keys when inviting a new user

- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
I have [merged](https://github.com/matrix-org/matrix-ios-sdk/pull/1444/files) a change 2 days ago which adds two new fields to a Realm entity, namely `sharedHistory` and `roomId`. These were meant as fields to enable querying sessions for all shared keys per room.
Since then we have decided to share keys based on last X messages, meaning that we can query directy by sessionId and senderKey, and previously added `roomId` and `sharedHistory` are not necessary on the Realm entity (they are still stored in the nested serialized data in the realm entity). This PR removes them before the next release of the iOS app.
> Revert Realm schema

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/MXBackgroundSyncService.swift
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.h
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
- MatrixSDK/Crypto/Data/MXMegolmSessionData.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/KeySharing/MXSharedHistoryKeyManager.swift
- MatrixSDK/Crypto/KeySharing/MXSharedHistoryKeyService.h
- MatrixSDK/Crypto/KeySharing/MXSharedHistoryKeyService.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MatrixSDK.h
- MatrixSDKTests/Crypto/Data/MXMegolmSessionDataUnitTests.swift
- MatrixSDKTests/Crypto/KeySharing/MXSharedHistoryKeyManagerUnitTests.swift
- MatrixSDKTests/MXCryptoShareTests.m
- MatrixSDKTests/MatrixSDKTestsE2EData.h
- MatrixSDKTests/MatrixSDKTestsE2EData.m
Resolves https://github.com/vector-im/element-ios/issues/4947 which is an implementation of https://github.com/matrix-org/matrix-doc/pull/3061
Handle several edge cases when key sharing:
- use unstable parameter name of `shared_history` when exporting and importing keys. This makes it compatible with the existing web implementation (e.g. backup keys on the web and restore on iOS => preserve `sharedHistory` flag)
- add integration tests for key sharing across several devices
- ensure that keys are only shared if the roomId of the session matches the room a user is invited into
> Change `sharedHistory` flag to unstable variant

- MatrixSDK/MXSDKOptions.m
- MatrixSDKTests/MXCryptoShareTests.m
The feature is not quite ready to be released yet, so disabling it by default for the upcoming release
> Disable default key sharing for history

- MatrixSDK/Aggregations/LocationSharing/MXBeaconAggregations.swift
- MatrixSDK/Aggregations/MXAggregations.h
- MatrixSDK/Aggregations/MXAggregations.m
- MatrixSDK/LocationSharing/MXBeaconInfoSummary.swift
- MatrixSDK/LocationSharing/MXBeaconInfoSummaryProtocol.swift
- MatrixSDK/LocationSharing/MXLocationService.swift
- MatrixSDKTests/MXBeaconAggregationsTests.swift
- changelog.d/6113.wip
https://github.com/vector-im/element-ios/issues/6113
> Location sharing: MXBeaconInfoSummary add isActive property

- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDKTests/Crypto/Algorithms/Megolm/MXMegolmEncryptionTests.swift
- MatrixSDKTests/MXCryptoTests.m
Crypto module should internally respect build flag when deciding if a room has shared history or not.
> Shared history flag in crypto module

- MatrixSDK/Utils/MXTools.h
- MatrixSDK/Utils/MXTools.m
- changelog.d/pr-1477.api
Small tweak to `MXTools` so it no longer returns an optional when calling `generateTransactionId`
> Mark MXTools.generateTransactionId as non-null.

- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDKTests/MXStoreFileStoreTests.m
- changelog.d/pr-1478.misc
Relates to repeatedly reported issues:
- https://github.com/matrix-org/element-ios-rageshakes/issues/18751
- https://github.com/matrix-org/element-ios-rageshakes/issues/18740
This does not fix the state corruption issue but uses newer KeyedUnarchiver/Archiver API which provides errors when something fails. Additionally add logs when we arent able to load state or the number of state events we are persisting.
> Add extra logs when saving and loading room state

- MatrixSDK/Data/MXRoom.m
- MatrixSDKTests/MXCryptoTests.m
- changelog.d/pr-1476.misc
Relates to https://github.com/matrix-org/element-ios-rageshakes/issues/18461
There are rare reports of rooms forgetting that they are encrypted, and it is plausable that this is caused by some state corruption. Given some existing measures that restore summary encryption if crypto store contains an algorithm, this state loss would need to be more comprehensive. Either way there isn't currently enough logs to pinpoint more precisely why encryption is not possible. This PR merely adds a few more logs to the encryption flow.
> Add more logs when encrypting messages

- MatrixSDK/Background/MXBackgroundStore.swift
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.h
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDKTests/MXBackgroundSyncServiceTests.swift
- changelog.d/5924.bugfix
Fixes another case for vector-im/element-ios#5924
> BackgroundStore: Avoid clearing file store when event stream token is missing

- MatrixSDK/Aggregations/MXAggregatedEditsUpdater.m
- changelog.d/3517.bugfix
This fixes an issue mentioned in https://github.com/vector-im/element-ios/issues/3517 
It removes body parts that shouldn't be added to the **new_content** body/formatted_body but only to the compatibility body/formatted_body. 
It also enables the ability to edit replies that have lost their mx-reply fallback (preserving the same behaviour as it already has: clients that handle rich replies will display everything properly, clients that don't will only be able to display the reply body)
Here's a screenshot of EleWeb displaying edited reply from an iOS client before and after this update.
> Remove unwanted parts from replies new_content body/formatted_body

- MatrixSDK/Contrib/Swift/MXRestClient.swift
- changelog.d/6179.api
In order to add a protocol that includes the client's `init`, this PR marks it as `required`. Part of 
https://github.com/vector-im/element-ios/issues/6179
> Mark MXRestClient init as required for mocking.

- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- changelog.d/6175.api
Part of vector-im/element-ios#6175
> Add `logoutDevices` parameter to `MXRestClient.changePassword` api

- MatrixSDK/JSONModels/Call/Events/MXCallHangupEventContent.h
- MatrixSDK/JSONModels/Call/Events/MXCallHangupEventContent.m
- MatrixSDK/Utils/MXTools.m
- changelog.d/1342.feature
Missing `MXCallHangupEvent` in iOS MatrixSDK but available in:
- js sdk - [source](https://github.com/matrix-org/matrix-js-sdk/blob/16ca09eed8114d4ef213e3396215e3bef140bc66/src/webrtc/call.ts#L210)
- android sdk - [source](https://github.com/matrix-org/matrix-android-sdk2/blob/c6a636397c51c8be712a08353e54af07cbe2759e/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/call/EndCallReason.kt#L45)
Signed-off-by: Frantisek Hetes f.hetes@gmail.com
> ✨ Add missing "user_busy" MXCallHangupEvent

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- MatrixSDKTests/TestPlans/CryptoTests.xctestplan
- changelog.d/pr-1496.misc
To avoid long-running feature branch when implementing [Matrix Rust SDK](https://github.com/matrix-org/matrix-rust-sdk/tree/main/crates/matrix-sdk-crypto) aka Element-R, I'd like to start merging small changes into `develop` that are well isolated and cannot be shipped to production by accident. In particular all newly added code is hidden both behind a build flag as well as behind `DEBUG` compiler macro, so the new code cannot be accidentally used and shipped to production builds.
This particular PR sets up the skeleton for new rust-based implementation by overriding `MXCrypto` and all of its methods. This has both benefits and risks:
- no need to do any risky refactor across the rest of the application (for example by definining shared protocol)
- existing integration tests can still …
> Subclass MXCrypto to enable work-in-progress Rust sdk

- .github/workflows/ci-unit-tests.yml
- Gemfile
- Gemfile.lock
- README.rst
- changelog.d/6306.build
- codecov.yml
- fastlane/Fastfile
Part of vector-im/element-ios#6306
Used the same config file with https://github.com/vector-im/element-x-ios/blob/develop/codecov.yml, as i've no shining ideas to append atm.
If i'm correct Codecov will be able to comment on subsequent PRs after the base coverage is detected when this is merged. We should be able to see the difference also at https://app.codecov.io/gh/matrix-org/matrix-ios-sdk/pulls
> DevX: Add Codecov

- MatrixSDK/Data/EventTimeline/Room/MXRoomEventTimeline.m
- changelog.d/6347.bugfix
Fixes https://github.com/vector-im/element-ios/issues/6347
Required since this change: https://github.com/matrix-org/synapse/pull/12903
> Handle empty pagination end token on timeline end reached

- MatrixSDK/VoIP/MXiOSAudioOutputRouter.swift
- changelog.d/5368.bugfix
Resolves https://github.com/vector-im/element-ios/issues/5368
- MXiOSAudioOutputRouter: fixed issue that prevents the system to properly switch from built-in to bluetooth output.
> taking a video call does not always default to loudspeaker

- MatrixSDK/Crypto/Recovery/MXRecoveryService.m
- MatrixSDK/Crypto/SecretStorage/MXSecretStorage.h
- MatrixSDK/Crypto/SecretStorage/MXSecretStorage.m
- MatrixSDK/Data/MXAccountData.h
- MatrixSDK/Data/MXAccountData.m
- MatrixSDK/MXSession.m
- MatrixSDKTests/MXCryptoSecretStorageTests.m
- MatrixSDKTests/TestPlans/CryptoTests.xctestplan
- changelog.d/4569.misc
Resolves https://github.com/vector-im/element-ios/issues/4569
An issue has been reported aprox a year ago with multiple valid SSSS keys and the iOS picking up the wrong one when authenticating (i.e. asking only for passkey, not passphrase). The issue has not been reported since then and could not be reproduced, so it isn't obvious whether it still occurs.
Based on the [initial report](https://github.com/vector-im/element-ios/issues/4569) the iOS did have a valid SSSS key and `m.secret_storage.default_key` was correctly pointing to it (otherwise the authentication would not ask for passphrase instead of passkey), but the client had reportedly more than one valid key. This means that the client has either failed to re-point `m.secret_storage.default_key` to the more recent key, or failed to …
> Detect multiple valid SSSS keys

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
- changelog.d/6415.bugfix
This PR prepares the release of MatrixSDK v0.23.12.
Notes:
- This PR targets `release/0.23.12/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.23.12/master` into `master` to tag the release.
--- …
> Release 0.23.12

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXSendReplyEventDefaultStringLocalizer.m
- MatrixSDK/Data/MXSendReplyEventStringLocalizerProtocol.h
- changelog.d/6423.change
Part of https://github.com/vector-im/element-ios/issues/6423
> MXRoom: Support reply to beacon info event (PSG-4)

- MatrixSDK/Aggregations/MXAggregatedEditsUpdater.m
- changelog.d/6446.bugfix
Fixes https://github.com/vector-im/element-ios/issues/6446
The formatted_body content is now properly omitted if there is no actual formatting within the message (same behaviour as Web).
> Fix formatted_body content for unformatted events

- MatrixSDK/MXRestClient.m
- changelog.d/6481.bugfix
The SDK isn't sending spec-complaint joins, and Synapse is about to stop handling these: https://github.com/matrix-org/synapse/issues/13388.
Fixes https://github.com/vector-im/element-ios/issues/6481.
> Send an empty dictionary when calling /join to be spec compliant.

- MatrixSDK/Space/MXSpaceService.swift
- changelog.d/6547.bugfix
This property was removed in Synapse 1.65 as it was going against the spec.
For more info see https://github.com/matrix-org/synapse/pull/13365 and https://github.com/vector-im/element-ios/issues/6547.
> Stop using the room ID from the space child state events.

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
- changelog.d/6547.bugfix
This PR prepares the release of MatrixSDK v0.23.15.
Notes:
- This PR targets `release/0.23.15/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.23.15/master` into `master` to tag the release.
--- …
> Release 0.23.15

- MatrixSDK/MXRestClient.m
There is no such thing as a `"kick"` membership in the spec. The fact that Synapse aliases `"kick"` to `"leave"` is unspecced behaviour.
> Fix `kickUser` to set `"leave"` membership

- MatrixSDKTests/MXCrossSigningVerificationTests.m
- MatrixSDKTests/MXCryptoKeyVerificationTests.m
Change existing key verification tests in a way that each side awaits incoming key request rather than assuming the incoming order (and hacking a delay time)
> Wait for all verification requests in integration tests

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/CrossSigning/Data/MXCrossSigningInfo.h
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
- MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest.h
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest.m
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequestV2.swift
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest_Private.h
- MatrixSDK/Crypto/Verification/Transactions/MXKeyVerificationTransaction.h
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction.h
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction.m
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransactionV2.swift
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction_Private.h
- MatrixSDKTests/Crypto/Verification/Requests/MXKeyVerificationRequestV2UnitTests.swift
- MatrixSDKTests/Crypto/Verification/Requests/VerificationRequest+Stub.swift
- MatrixSDKTests/Crypto/Verification/Transactions/SAS/MXSASTransactionV2UnitTests.swift
- MatrixSDKTests/Crypto/Verification/Transactions/SAS/Sas+Stub.swift
- changelog.d/6443.feature
Resolves https://github.com/vector-im/element-ios/issues/6443
Implement (outgoing) verification flow using SAS / emojis, incl sending initial request, responding via SAS methods, accepting or rejecting matching emojis and displaying the verification status of user after verification is complete.
- Add `MXKeyVerificationManagerV2` which uses Rust-based crypto machine under the hood
- Expose `OlmMachine` verification methods under `MXCryptoVerification`
- Hide some of the [previously exposed](https://github.com/matrix-org/matrix-ios-sdk/pull/1528) protocol methods inside legacy implementations, as they are not / shoud not be needed by every verification implementation
- Implement Rust-based verification request and sas transactions that can be used with existing views and view models
- Some …
> Outgoing SAS User Verification Flow

- MatrixSDK/MXSession.m
- changelog.d/6614.bugfix
Potential fix for https://github.com/vector-im/element-ios/issues/6614
Allows the MXSession to be paused if app is already in background when the preventPauseCount reaches 0.
> Fix incoming calls sometimes ringing after being answered on another client

- MatrixSDK/Contrib/Swift/MXSession.swift
- changelog.d/pr-1559.change
This simply allows to set a room alias on room creation regardless of join rule.
> Allow setting room alias regardless of join rule

- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDKTests/Utils/MXSessionTracker.swift
Remove encrypted event from being tracked to analytics via Sentry, only track the eventId.
> Remove event from tracking

- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- MatrixSDKTests/MXAes256KeyBackupTests.m
- changelog.d/pr-1567.change
Add build flag for symmetric backup, when dynamically constructing backup algoritm class, based on incomming algorithm.
Unrelated: remove event from event tracking, see https://github.com/matrix-org/matrix-ios-sdk/pull/1563
> Add build flag for symmetric backup

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- MatrixSDK/MatrixSDKVersion.m
- MatrixSDKTests/MXAes256KeyBackupTests.m
- changelog.d/pr-1567.change
This PR prepares the release of MatrixSDK v0.23.17.
Notes:
- This PR targets `release/0.23.17/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.23.17/master` into `master` to tag the release.
--- …
> Release 0.23.17

- README.rst
- changelog.d/pr-1569.doc
More importantly, fix the coverage one to make it open the codevoc.io URL correctly.
The new header looks like that now:
> README: Update the badge header

- MatrixSDK/Crypto/MXCrypto.m
- changelog.d/pr-1570.change
The existing `[MXCrypto getRoomEncryptor]` method is used by a variety of codepaths, incl. re-sharing room keys etc. It returns a cached / in-memory value of `MXMegolmEncryptor`, but only if it was previously set to memory, typically by `ensureEncryptionInRoom` method (which performs a bunch of other actions). This method is typically called when a user starts typing in a given room.
When a user launches the app the `roomEncryptors` dictionary will be empty for all rooms, and encryptors will only be created if a user types a message in that room, or some message arrives to this device. It is not however created when the user receives a `m.room_key_request` for this room, and thus silently fails in re-sharing a given key, leaving the requester with UISIs.
To solve this, this PR ensures …
> Create lazy in-memory room encryptors

- MatrixSDK/Background/MXBackgroundStore.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/Store/MXFileStore/MXFileRoomStore.m
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.h
- MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
- MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
- MatrixSDK/Data/Store/MXStore.h
- changelog.d/6670.change
Removes the support for MXRoom's partialTextMessage as it has been deprecated for a few months now and since it's usage was the root cause of issue https://github.com/vector-im/element-ios/issues/6670
Part of https://github.com/vector-im/element-ios/pull/6671
> Remove partialTextMessage support

- MatrixSDK/Utils/MXUIKitApplicationStateService.swift
- changelog.d/6754.misc
The main thread assertion can be triggered when running or debugging the NSE extension (which can run in parallel and on varying threads). However, app extensions can't access `UIApplication.shared` anyway so we can delay the assertion to the point where `UIApplication.applicationState` is actually accessed.
Fixes: https://github.com/vector-im/element-ios/issues/6754
> Avoid main thread assertion if we can't get the application

- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- MatrixSDKTests/MXCryptoTests.m
- changelog.d/pr-1575.change
After running a store / cache megolm decryption A/B test for a few weeks we gathered that cache decryption is aprox 10x faster and no new issues have been reported. As a result we can switch to cache variant exclusively, but leave the build flag in for a bit longer as a safety measure.
> Enable group session cache by default

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/KeyBackup/Engine/MXKeyBackupEngine.h
- MatrixSDK/Crypto/KeyBackup/Engine/MXKeyBackupPayload.swift
- MatrixSDK/Crypto/KeyBackup/Engine/MXNativeKeyBackupEngine.h
- MatrixSDK/Crypto/KeyBackup/Engine/MXNativeKeyBackupEngine.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup_Private.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDKTests/MXBaseKeyBackupTests.m
- changelog.d/pr-1578.change
As part of implementing key backups with Rust-based CryptoSDK I need to separate out shared and distinct backup functionality in the existing codebase. In the past I have simply duplicated a class (`MXCrypto`, `MXKeyVerificationManager`) and overriden all of its methods, but this approach is not suitable for backups, because a lot more code ends up being shared (state management, enabling/disabling backups, restoring, sending http requests etc).
The approach I have chosen instead is to identify all of the code specific to native / legacy implementation and refactor it as new `MXKeyBackupEngine` protocol. At the moment only `Native` implementation exists, but in a future PR I will add the rust-based variant. It is absent from this PR to make the refactor cleaner and easier to review.
As …
> Extract key backup engine

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/JSONModels/MXDevice.h
- MatrixSDK/JSONModels/MXDevice.m
- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MatrixSDK.h
- changelog.d/pr-1583.change
Implements https://github.com/matrix-org/matrix-spec-proposals/pull/3852
> Expose user agent information on `MXDevice`

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoRequests.swift
- MatrixSDK/Crypto/KeyBackup/Engine/MXCryptoKeyBackupEngine.swift
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup_Private.h
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/SecretStorage/MXCryptoSecretStoreV2.swift
- MatrixSDK/Crypto/SecretStorage/MXSecretStorage.h
- MatrixSDK/Crypto/SecretStorage/MXSecretStorage_Private.h
- MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
- MatrixSDK/MatrixSDK.h
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoRequestsUnitTests.swift
- MatrixSDKTests/Crypto/KeyBackup/Data/MXKeyBackupVersion+Stub.swift
- MatrixSDKTests/Crypto/KeyBackup/Engine/MXCryptoKeyBackupEngineUnitTests.swift
- MatrixSDKTests/TestPlans/UnitTests.xctestplan
- MatrixSDKTests/TestPlans/UnitTestsWithSanitizers.xctestplan
- changelog.d/6769.change
Resolves https://github.com/vector-im/element-ios/issues/6768 and https://github.com/vector-im/element-ios/issues/6769
This PR adds key backup functionality using rust-based crypto machine. The changes include:
- Implement backup-related functionality from rust-based `OlmMachine`, hidden behind `MXCryptoBackup` protocol
- Implement new backup engine, similar to the one introduced [previously](https://github.com/matrix-org/matrix-ios-sdk/pull/1578)
- Initialize backup and cross signing upon first keys upload via crypto machine
- Allow discarding room keys via `/discardsession` slash command
> Key backups with Crypto V2

- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- changelog.d/6773.change
Resolves https://github.com/vector-im/element-ios/issues/6773 and https://github.com/vector-im/element-ios/issues/6774
Expose specific decryptionError when room keys are missing (which is displayed as "re-request keys" message on iOS), and implement `requestRoomKey` which will send out `m.room_key_request` message to other verified devices of the same user. Once recieved by the other device, its OlmMachine will automatically send out `m.forwarded_room_key` if necessary.
> Key gossiping with Crypto V2

- MatrixSDK/Contrib/Swift/JSONModels/MXJSONModels.swift
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/JSONModels/MXMatrixVersions.h
- MatrixSDK/JSONModels/MXMatrixVersions.m
- MatrixSDK/JSONModels/Push/MXPusher.h
- MatrixSDK/JSONModels/Push/MXPusher.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- changelog.d/6787.change
needed for [#6787](https://github.com/vector-im/element-ios/issues/6787)
> Added support for MSC3881

- MatrixSDK/Contrib/Swift/Data/MXRoom.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- changelog.d/pr-1595.change
Voice broadcast feature is based on voice message. We need to add some parameters in the content to distinguish them.  
> Support additional content in voice message

- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/Data/Store/MXCryptoSecretStore.h
- MatrixSDK/Crypto/Devices/Data/MXCryptoDeviceWrapper.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/Recovery/MXRecoveryService.h
- MatrixSDK/Crypto/SecretStorage/MXCryptoSecretStoreV2.swift
- MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
- MatrixSDKTests/Crypto/CryptoMachine/Device+Stub.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/Crypto/Devices/Data/MXDeviceInfoUnitTests.swift
- changelog.d/6781.change
Resolved https://github.com/vector-im/element-ios/issues/6781
- implement functionality to manually verify a device (and upload its signatures)
- reflect trust status when a device is blocked
- return cross signing keys as secrets when available
> Manual device verification with Crypto V2

- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequestV2.swift
- MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransactionV2.swift
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXOutgoingSASTransaction.m
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction.m
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransactionV2.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/Crypto/Verification/Transactions/SAS/MXSASTransactionV2UnitTests.swift
- changelog.d/pr-1605.change
The last few changes (for a while) in verification for Crypto V2:
- process unencrypted verification events manually (they obviously cannot be handled automatically when calling `decryptRoomEvent`)
- add support for SAS decimals
- restore pending verification requests after app relaunch
> Unencrypted verification events in Crypto V2

- MatrixSDK/Crypto/MXOlmDevice.m
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- MatrixSDK/MXSession.m
- changelog.d/pr-1606.change
After a brief stabilization period with the cache variant set to YES, we can now remove the flag altogether
> Remove megolm decrypt cache build flag

- MatrixSDK/Data/MXRoomMembers.h
- MatrixSDK/Data/MXRoomMembers.m
- MatrixSDK/Data/MXRoomState.m
- changelog.d/6850.bugfix
Ticket -> https://element-io.atlassian.net/browse/PSB-201?atlOrigin=eyJpIjoiY2YwNjNiMjU3M2IxNGQyNmFjOGVhZTM1Mzc0NTYxZDUiLCJwIjoiaiJ9
GitHub issue -> https://github.com/vector-im/element-ios/issues/6850
**Description**
This PR fixes the user's display name for messages sent before the user changed his display name.
> Fix user display name (PSB-201)

- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.h
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/CrossSigning/MXCrossSigningInfoSource.swift
- MatrixSDK/Crypto/CrossSigning/MXCrossSigningV2.swift
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction.m
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/MXSession.h
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXTaskQueue.swift
- MatrixSDKTests/Crypto/CrossSigning/MXCrossSigningInfoSourceUnitTests.swift
- MatrixSDKTests/MXCrossSigningTests.m
- MatrixSDKTests/MXCryptoRecoveryServiceTests.m
- MatrixSDKTests/MXCryptoSecretShareTests.m
- MatrixSDKTests/MXCryptoSecretStorageTests.m
- MatrixSDKTests/MXCryptoShareTests.m
- MatrixSDKTests/MXCryptoTests.m
- changelog.d/pr-1618.change
A number of related changes to the `MXCrypto` protocol:
- cleanup `MXCrypto` protocol by moving a number of methods and properties into `MXLegacyCrypto`, because they are used only with the legacy implementation of the crypto module, and thus do not need to be implemented by `MXCryptoV2`
- consolidate similar methods `trustLevelSummary` into one
- deprecate legacy synchronous `decryptEvent` method
- track duration of encrypting an event with Crypto V2
Note that in the future PR the remaining unimplemented methods in CryptoV2 will be dealt with
> Curate MXCrypto protocol methods

- MatrixSDK.podspec
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/CrossSigning/MXCrossSigningV2.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/CryptoMachine/MXEventDecryptionResult+DecryptedEvent.swift
- MatrixSDK/Crypto/Devices/Data/MXCryptoDeviceWrapper.swift
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/SecretStorage/MXCryptoSecretStoreV2.swift
- MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
- MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequestV2.swift
- MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransactionV2.swift
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MXSession.m
- MatrixSDK/MatrixSDK.h
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoMachineUnitTests.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/Crypto/Verification/Transactions/SAS/MXSASTransactionV2UnitTests.swift
- MatrixSDKTests/Mocks/MXRestClientStub.m
- Podfile
- Podfile.lock
A number of changes to [rust-based Crypto V2](https://github.com/matrix-org/matrix-ios-sdk/pull/1620) after extensive testing with polyjuice:
- expose `VerificationState` on decryption result to display trusted / untrusted sessions
- ensure CryptoV2 gets initialized on the main queue
- move event observers from key verification manager to crypto v2 to gain access to downloading user keys and processing outgoing requests
- always download keys for new senders before processing to-device events
- restore room keys from backup after recieving recovery key
> CryptoV2 changes

- MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventDecryption.swift
- MatrixSDK/Crypto/CrossSigning/MXCrossSigningV2.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/CryptoMachine/MXEventDecryptionResult+DecryptedEvent.swift
- MatrixSDK/Crypto/Data/MXMegolmSessionData.m
- MatrixSDK/Crypto/KeyBackup/Engine/MXCryptoKeyBackupEngine.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/MXSession.m
- MatrixSDKTests/Crypto/Algorithms/RoomEvents/MXRoomEventDecryptionUnitTests.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoMachineUnitTests.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/Crypto/Data/MXMegolmSessionDataUnitTests.swift
- MatrixSDKTests/Crypto/KeyBackup/Engine/MXCryptoKeyBackupEngineUnitTests.swift
- changelog.d/pr-1630.change
A number of changes / fixes for Crypto V2:
- re-decrypt events by specific sessionId after importing keys
- ensure we send room keys to our other devices
- better location for mac-specific crypto store (useful in integration tests)
- enable `isUntrusted` state for events
- fix a few nullability crashes
> Crypto V2 fixes

- MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventDecryption.swift
- MatrixSDK/Utils/Logs/MXAnalyticsDestination.swift
- changelog.d/pr-1632.change
Log separate errors based on the type of `DecryptionError` so that it is easier to distinguish and monitor unrelated failure reasons in sentry
> Log decryption errors separately with Crypto V2

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Data/Filters/MXFilterJSONModel.m
- MatrixSDK/JSONModels/MXMatrixVersions.h
- MatrixSDK/JSONModels/MXMatrixVersions.m
- MatrixSDKTests/MXMatrixVersionsUnitTests.swift
- MatrixSDKTests/MXRoomEventFilterUnitTests.swift
- changelog.d/7066.bugfix
Needed for https://github.com/vector-im/element-ios/issues/7066
> Threads: removed "unread_thread_notifications" from sync filters

- MatrixSDK/Crypto/KeyBackup/Engine/MXCryptoKeyBackupEngine.swift
- MatrixSDK/Crypto/KeyBackup/Engine/MXKeyBackupEngine.h
- MatrixSDK/Crypto/KeyBackup/Engine/MXNativeKeyBackupEngine.m
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
- MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
- changelog.d/pr-1637.change
Split up room keys into batches of 1000 when importing, and ensure to decrypt + import within `autoreleasepool`. This ensures we do not run out of memory when importing large key backups.
Additionally expose `importProgress` property, analogous to existing `backupProgress`, that can be used by any UI.
Tested by importing 1,000,000 keys on a device, which does grow the memory footprint considerably, but still slower than without the `autoreleasepool` and batching. The initial spike seen below is the http request, roughly 800MB for all the keys.
> Import progress for room keys with Crypto V2

- MatrixSDK/Crypto/KeyBackup/Engine/MXCryptoKeyBackupEngine.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- changelog.d/pr-1639.change
- Run all crypto `Task`s with default priority rather than assigning `medium`
- Make sure `CryptoV2` does not get initialized more than once (which can happen during failing initial syncs)
- Remove unnecessary processing of outgoing requests
> Run all Crypto tasks with default priority

- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Space/MXSpaceService.swift
- changelog.d/pr-1641.change
The check to see whether we have any keys to backup relies on getting the actual count of total vs backed-up keys. For large accounts this rust method is very compute intensive and blocks the main thread. This has to be improved on the rust side, but for the time being we will return a cached count synchronously and then compute the actual count on a separate thread asynchronously. This will free up the main thread.
Additionally and unrelatedly I noticed that space graph computation during sync also blocks the main thread (once again for large accounts). This is due to an innocent looking `MXRoom.isDirect` method that actually has O(n) performance. Instead of being a state property, it is a computed property that iterates through all direct rooms to determine if itself is direct or not. …
> Fix backup performance with Crypto V2

- MatrixSDK/Space/MXSpaceNotificationCounter.swift
- changelog.d/pr-1645.change
This PR refactor the count logic for invites making it coherent with unread messages and mentions count.
Currently for mentions the same event is counted both in:
- `*count`
- `*HighlightedCount`
Conversely Invites are counted just in:
- `*HighlightedCount`
This break the invariant:
`*count >= *HighlightedCount` 
bringing inconsistencies in the client.
After this PR invites are counted **both as highlighted and in the general count as well**.
https://github.com/vector-im/element-ios/pull/7088
> Fix invites count

- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/MXSession.m
- changelog.d/pr-1646.change
Fail sync / session init when `crypto` module is required but unavailable. This can happen for instance when we fail to open the underlying database.
Previously this would just silently fail and continue syncing forever, now we propagate the error upwards and can display an error.
> Fail launch when unavailable crypto

- MatrixSDK/Data/MXRoomState.m
During a bug investigation, we found that the FileStore may be corrupted with peeking feature (when previewing a room), but not joining the room after previewing it.
In result, we had a « ghost » room in the room list, with some content, but not all the content of this room (ie: no room summary, but messages were visible, and we can pickup the previous messages when scrolling), instead of having nothing.
So I added a condition on Unknown membership rooms to avoid to add them to the file store.
> Fix room state for peeking

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoRequests.swift
- MatrixSDK/Crypto/KeySharing/MXOutgoingRoomKeyRequestManager.m
- MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- MatrixSDK/MXSession.m
- MatrixSDK/Utils/MXToDevicePayload.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoRequestsUnitTests.swift
- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/MXSessionTests.m
- MatrixSDKTests/MXToDevicePayloadUnitTests.swift
- MatrixSDKTests/TestPlans/UnitTests.xctestplan
- MatrixSDKTests/TestPlans/UnitTestsWithSanitizers.xctestplan
- changelog.d/pr-1652.change
Add automatically generated `org.matrix.msgid` to each to-device message (i.e. per user / device) as described in https://github.com/vector-im/element-meta/issues/558
For context see [Android](https://github.com/vector-im/element-android/pull/7713) and [web](https://github.com/matrix-org/matrix-js-sdk/pull/2938) implementation.
When sending to-device messages (e.g. room keys) the logs will look like this:
```log
[MXMegolmEncryption] shareKey: Actually share with 2 users and 2 devices
[MXToDevicePayload] Created to-device payload with txnId m2054895014.1, message ids: [@charlie:x.y.z/IYYFXFKAIG 5A07D00E-CB64-4133-A1BB-F9CE1AFD38AA, @bob:x.y.z/CSCLHKJCVN 11C0E404-B0CC-433C-86EA-C883727C4CA7]
[MXHTTPClient] #105 - PUT _matrix/client/r0/sendToDevice/m.room.encrypted/m2054895014.1 …
```
> Add message id for to-device events

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/Crypto/MXDummyBackgroundCrypto.swift
- MatrixSDK/Background/MXBackgroundSyncService.swift
- MatrixSDK/Crypto/CryptoMachine/MXEventDecryptionResult+DecryptedEvent.swift
- MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
- changelog.d/pr-1662.change
Rust-based crypto uses a database which is not multi-process safe and cannot be used from foreground and background process simultaneously. This will be addressed in a future PR, but before we have multi-process safe database, we are simply not going to be decrypting notifications, only displaying their arrival.
Some other changes include:
- temporarily comment out `isUntrusted` property of events until rust adds an "undecided" state for trust
- do not post new transaction notifications for SAS as we do not support modal prompts for crypto V2
> Disable notification decryption for Crypto V2

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Utils/Logs/MXAnalyticsDestination.swift
- MatrixSDK/Utils/Logs/MXLog.swift
- MatrixSDKTests/TestPlans/UnitTests.xctestplan
- MatrixSDKTests/TestPlans/UnitTestsWithSanitizers.xctestplan
- MatrixSDKTests/Utils/Logs/MXAnalyticsDestinationUnitTests.swift
- changelog.d/pr-1664.change
We log errors in a lot of places across the codebase via `MXLog.error(... error)` passing in any error that was returned from some api, incl rest clients that may return cancellation errors. These are not userful to track in analytics as they occur due to some user action. Instead of filtering them out in the many many places where we log errors, we will filter them out all at once in `MXAnalyticsDestination`
> Do not track cancellation errors

- README.rst
This PR updates the documentation for installing a local synapse instance on Mac OS machines.
> Update synapse installation doc

- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
- changelog.d/pr-1677.change
It's an un-specced property and will be removed per https://github.com/matrix-org/synapse/issues/12482
> Remove commented device property from push rules.

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Room/Polls/PollAggregator.swift
- changelog.d/pr-1674.change
This PR:
- Adds a new init for the `PollAggregator` so that it will be able to aggregate a poll starting from a `m.poll.end` event
- Enable replies for a `m.poll.end` event
> Render m.poll.end event (PSG-196)

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/CrossSigning/MXCrossSigningV2.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoRequests.swift
- MatrixSDK/Crypto/CryptoMachine/MXKeysQueryScheduler.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXKeysQuerySchedulerUnitTests.swift
- MatrixSDKTests/TestPlans/UnitTests.xctestplan
- MatrixSDKTests/TestPlans/UnitTestsWithSanitizers.xctestplan
- changelog.d/pr-1676.change
Fixes https://github.com/matrix-org/matrix-ios-sdk/issues/1668 and partially resolves https://github.com/matrix-org/matrix-ios-sdk/issues/1670
Add `MXKeysQueryScheduler` used with crypto V2, which serves similar purpose as `MXDeviceList` serves in legacy crypto, albeit only focusing on optimizing `keys/query` requests.
Specifically it will:
- ensure that only one keys/query request is in-flight at any given time
- all further requests are aggregated, and if they contain any new users, will be executed right after the first one finishes
These optimizations should ensure that the application does not make unnecessary amout of queries, as we currently call the `downloadKeys` from far too many places. Note that I have [previously](https://github.com/matrix-org/matrix-ios-sdk/pull/1675) tried …
> Add keys query scheduler

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/MXBackgroundCryptoStore.m
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachineLogger.swift
- MatrixSDK/Crypto/Data/MXOlmSession.h
- MatrixSDK/Crypto/Data/MXOlmSession.m
- MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/MXOlmDevice.m
- MatrixSDK/Crypto/Migration/Data/MXCryptoMigrationStore.swift
- MatrixSDK/Crypto/Migration/MXCryptoMigrationV2.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXKeysQuerySchedulerUnitTests.swift
- MatrixSDKTests/Crypto/Data/Store/MXMemoryCryptoStore.swift
- MatrixSDKTests/Crypto/Migration/Data/MXCryptoMigrationStoreUnitTests.swift
- MatrixSDKTests/Crypto/Migration/MXCryptoMigrationV2Tests.swift
- MatrixSDKTests/MXCryptoTests.m
- MatrixSDKTests/TestPlans/CryptoTests.xctestplan
- MatrixSDKTests/TestPlans/UnitTests.xctestplan
- MatrixSDKTests/TestPlans/UnitTestsWithSanitizers.xctestplan
- changelog.d/pr-1681.change
Create `MigrationData` object defined in rust-crypto-sdk, which is populated with existing data (account, sessions, cross signing ...), and used to migrate into the rust-based `OlmMachine`. Note that this PR only adds the creation and migration of this object, but no codepath will currently trigger the migration itself. This will be done in a future PR.
Main changes in this PR:
- add `MXCryptoMigrationStore` which will use legacy crypto store (`MXCryptoStore`) to construct rust-based `MigrationData`
- add `MXCryptoMigrationV2` which will actually perform the migration from legacy store to rust-based crypto
- change `MXOlmSession` and `MXCryptoStore` API to include `deviceKey` on the session itself rather than just stored internally in realm
To be done in future PR:
- More integration …
> Create Crypto V2 Migration Data

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXSendReplyEventDefaultStringLocalizer.m
- MatrixSDK/Data/MXSendReplyEventStringLocalizerProtocol.h
- changelog.d/pr-1685.bugfix
This PR ensure that placeholders in reply events are always sent in the English version.
Matrix client receiving events containing this placeholder may chose to localize them or not.
It doesn't make sense localizing placeholders on the sender side since the receivers could prefer a different language.
Affected placeholders are:
- "In reply to"
- "Ended poll" (new one, it's used when replying to `m.poll.end` events)
> Reply to ended polls events (PSG-1131)

- MatrixSDK/Data/MXRoom.h
- MatrixSDK/Data/MXRoom.m
- MatrixSDK/JSONModels/MXMatrixVersions.h
- MatrixSDK/JSONModels/MXMatrixVersions.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
- changelog.d/pr-1688.feature
SDK support for [MSC3912](https://github.com/matrix-org/matrix-spec-proposals/pull/3912)
> Implement MSC3912: redaction with relations

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/Crypto/MXBackgroundCrypto.swift
- MatrixSDK/Background/Crypto/MXBackgroundCryptoV2.swift
- MatrixSDK/Background/MXBackgroundSyncService.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/Migration/MXCryptoMigrationV2.swift
- MatrixSDK/MXSession.m
- MatrixSDK/MXSessionStartupProgress.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoMachineUnitTests.swift
- MatrixSDKTests/Crypto/MXCryptoV2FactoryTests.swift
- MatrixSDKTests/MXSessionStartupProgressUnitTests.swift
- MatrixSDKTests/TestPlans/CryptoTests.xctestplan
- changelog.d/pr-1692.change
A set of unrelated improvements when testing crypto v2 migrations:
- ensure sync response is handled on the main thread for now (not entirely thread safe in rust atm)
- add integration tests for migration to ensure only existing users are migrated and only once
- do not force download keys when computing trust summary
- change the weight ratio of olm to megolm to be calculated dynamically from total amount of sessions
- ensure we report startup progress only during initial syncs
> Migration improvements in Crypto V2

- MatrixSDK/Background/Crypto/MXBackgroundCrypto.swift
- MatrixSDK/Background/MXBackgroundCryptoStore.m
- MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventDecryption.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/Data/Store/MXCryptoSecretStore.h
- MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/KeyBackup/Engine/MXCryptoKeyBackupEngine.swift
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/MXCryptoV2Factory.swift
- MatrixSDK/Crypto/MXOlmDevice.m
- MatrixSDK/Crypto/Recovery/MXRecoveryService.m
- MatrixSDK/Crypto/SecretStorage/MXCryptoSecretStoreV2.swift
- MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
- MatrixSDK/MXSessionStartupProgress.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/Crypto/Data/Store/MXMemoryCryptoStore.swift
Some further changes when testing account migration from libolm to rust:
- remove `open` method from `MXCryptoStore` that is empty in all implementations of this protocol. This was probably used in the past but is clearly not doing anything, and removing it reduces objc callback nesting by one level
- add `hasSecretWithSecretId` on the `MXCryptoStore` protocol. For legacy store this is just a convenience API, but for crypto V2 it calls a different (and faster) rust API
- some changes in key verification management, where we only `processOutgoingRequests` and `downloadKeysIfNecessary` from within the manager, rather than `MXCryptoV2`, which makes for a better logic encapsuation
> More migration fixes for Crypto V2

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/Crypto/MXBackgroundCryptoV2.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoRequests.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoSDKLogger.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/Migration/MXCryptoMigrationV2.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoRequestsUnitTests.swift
- changelog.d/pr-1697.change
Upload fallback keys via `keys/upload` whenever present in the body of `UploadKeysRequest`.
Additionally:
- move `MXKeysQueryScheduler` into `MXCryptoRequests` (rather than the other way around), which hides away the details of making `keys/query` requests
- rename `MXCryptoSDKLogger`
- additional log messages
> Upload fallback keys with Crypto V2

- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachineStore.swift
- MatrixSDK/Crypto/Data/MXCryptoConstants.h
- MatrixSDK/Crypto/Data/MXCryptoConstants.m
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/Migration/MXCryptoMigrationV2.swift
- MatrixSDK/Crypto/Trust/MXTrustLevelSource.swift
- MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
- MatrixSDKTests/Crypto/Migration/MXCryptoMigrationV2Tests.swift
- MatrixSDKTests/Crypto/Trust/MXTrustLevelSourceUnitTests.swift
- changelog.d/pr-1699.change
Use existing `MXKeyProvider` mechanism to get a new key that is used as base64-encoded passphrase when migrating or creating `OlmMachine` in crypto V2. This means all data stored in the underlying sqlite db will be encrypted.
Additionally:
- listen to room membership changes and track new users
- listen to room encryption events and set encryption if necessary
> Set passphrase for the crypto store

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoSDKLogger.swift
- MatrixSDK/Crypto/Data/MXCryptoConstants.h
- MatrixSDK/Crypto/KeyBackup/Engine/MXCryptoKeyBackupEngine.swift
- MatrixSDK/Crypto/KeyBackup/Engine/MXEncryptedKeyBackup.swift
- MatrixSDK/Crypto/KeyBackup/Engine/MXNativeKeyBackupEngine.m
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDKTests/Crypto/Algorithms/RoomEvents/MXRoomEventEncryptionUnitTests.swift
- changelog.d/pr-1701.change
Import room backups in batches and report progress continuously.
Note that even with this change memory growns linearly during import (albeit with a smaller slope), which means we are either leaking some memory or filling up in-memory cache somewhere in the crypto layer. Either way this should make imports slightly less memory hungry, and compute the progress regardless.
This PR also contains some small fixes for crypto v2 (logs + tracked users optimization)
> Import legacy backup in batches with progress

- MatrixSDK/NotificationCenter/MXNotificationCenter.h
- MatrixSDK/NotificationCenter/MXNotificationCenter.m
- changelog.d/pr-1702.change
This PR add completion blocks for updating push rules.
Completion blocks have been added for:
- Enabling/disabling a push rule
- Updated actions of a push rule
> Sync polls rules (PSG-77, PSG-1097)

- MatrixSDK/Background/Crypto/MXBackgroundCryptoV2.swift
- MatrixSDK/Background/MXBackgroundSyncService.swift
- changelog.d/pr-1704.change
The background crypto process (used to decrypt notifications) relies on several rust-crypto-sdk methods that are not multiprocess safe. In particular, since the background's `MXCryptoMachine` may live in memory for days, whereas foreground's will be recreated on each app launch, we may end up in a situation where foreground has written changes to disk that the background machine does not pick up. For more details see https://github.com/matrix-org/matrix-rust-sdk/issues/1415
This will be fixed in the future in the rust-sdk via a `proc_lock` or similar multiprocess lock, but in a meanwhile a relatively quick solution is to recreate `MXCryptoMachine` on each operation (recieve sync, decrypt event), ensuring that each time we have relatively fresh data taken straight from disk.
We could …
> New CryptoMachine on each background operation

- MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
A recently introduced [protocol change](https://github.com/matrix-org/matrix-ios-sdk/pull/1696/files#diff-b475ca0411f0b9bc774120fba6703e2efe8a6cf1d71c982c7baa8b450501def0R179-R198) was not correctly implemented on all classes, leading to some integration tests to fail.
> Fix protocol conformance

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Categories/MXRestClient+Extensions.swift
- MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventEncryption.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/Devices/Data/MXDeviceInfo.m
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDKTests/JSONModels/MXKeysQueryResponseUnitTests.swift
- MatrixSDKTests/TestPlans/UnitTests.xctestplan
- MatrixSDKTests/TestPlans/UnitTestsWithSanitizers.xctestplan
- changelog.d/pr-1707.change
When downloading user keys via `keys/query` we sometimes use `downloadByChunks` method that makes several HTTP requests and combines the result into a single `MXKeysQueryResponse`. The Crypto V2 relies on getting the value of this response via `JSONDictionary` property, however this property was previously just returning whatever initial value was used to create it, and is nil when combining multiple responses together.
To solve this we cannot rely on stored property but rather have to compute the `JSONDictionary` out of the current values of the response. Additionally there was a minor bug in `downloadByChunks` that would trigger this problem even if we are downloading exactly chunk-sized number of users
> Fix JSONDictionary of keys query responses

- MatrixSDK/VoIP/MXCall.m
- changelog.d/pr-1710.bugfix
This PR fixes some scenarios where a call continues to ring, even after being answered (or declined) elsewhere.
Related issues:
[iOS: Call answered elsewhere continues to ring](https://gitlab.matrix.org/ps/aarenet/issue-tracker/-/issues/450)
[App continues to ring #2](https://element-io.atlassian.net/browse/PSC-203)
The main issue here is that the expiration timer may be fired after 1 minute for a call that is already ended (because it has been answered elsewhere). In this case, setting its state to ended can pause the MXSession and prevents the current ringing call to receive any further events.
Here is the list of changes made to fix this issue:
- Invalidate the expiration timer once the call has been answered or declined elsewhere
- Avoid updating the state of an ended call:
> Fixed some scenarios where an answered call keeps ringing.

- MatrixSDK/Data/MXRoom.m
- MatrixSDK/Data/MXSendReplyEventDefaultStringLocalizer.m
- MatrixSDK/Data/MXSendReplyEventStringLocalizerProtocol.h
- MatrixSDKTests/MXPollRelationTests.m
- changelog.d/pr-1713.change
This PR adds a fallback text for `m.poll.end` events.
These fallbacks are useful for receivers when the associated `m.poll.start` event is unavailable.
> Add fallback text for m.poll.end events (PSG-1156)

- MatrixSDK/Background/MXBackgroundPushRulesManager.swift
- MatrixSDK/Background/MXBackgroundSyncService.swift
- changelog.d/pr-1714.change
push rules for an event was broken because it was reading the encrypted one.
Now if present the clear event, the proper rule id is matching properly.
It was also missing the pushRulesManager's handle account data in the updateBackgroundServiceStoresIfNeeded, that way it was not synchronised and a reboot of the app was needed in order to fetch the proper push rules
> 🟢 Apply (polls) push rules client side for encrypted rooms

- MatrixSDK/Contrib/Swift/MXResponse.swift
- changelog.d/pr-1715.change
This PR typealias `MXReponse` to `Swift.Result`.
This have a couple of benefit:
- `MXReponse` gets the `Swift.Result` api for free
- We may use an `MXResponse` wherever a `Swift.Result` is required without additional boilerplate (for example [here](https://developer.apple.com/documentation/swift/checkedcontinuation/resume(with:)-3gh60)).
> Typealias MXResponse to Swift.Result

- MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventDecryption.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoMachineUnitTests.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/Crypto/Migration/MXCryptoMigrationV2Tests.swift
- changelog.d/pr-1717.change
Previously the `CryptoSDK` would automatically handle encrypted verification events in rooms as soon as they are decrypted via `decryptRoomEvent` methods. Whilst this sounds convenient, there are a number of issues with this approach:
- we still need to manually pass in unencrypted verification events, not otherwise known to the crypto machine
- upon decrypting a verification event, we may have some new requests to sent out out of a sync loop
An improved approach is to prevent the machine from automatically processing verification events via a parameter, and then reuse existing event observers to pass in both encrypted and unencrypted verification events.
> Unify verification event processing in Crypto V2

- MatrixSDK/Crypto/KeyBackup/Engine/MXNativeKeyBackupEngine.m
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
- changelog.d/pr-1716.bugfix
This PR fixes:
- a crash in DEBUG when the app tries to send a cancel verification request while the session is closed.
- 2 retain cycles preventing MXCrypto from being properly released
> Fix: don’t send a verification cancel request if the session is closed

- MatrixSDK/Utils/Media/MXMediaLoader.m
- changelog.d/pr-1721.bugfix
This PR fixes an issue with the back pagination where images would not download until the end of the scroll.
> Fix an issue where the media download would not start until the end of the scroll

- MatrixSDK/Data/MXRoomLastMessage.h
- MatrixSDK/Data/MXRoomLastMessage.m
- MatrixSDK/Data/RoomSummaryStore/CoreData/MXCoreDataRoomSummaryStore.xcdatamodeld/MXRoomSummaryCoreDataStore2.xcdatamodel/contents
- MatrixSDK/Data/RoomSummaryStore/CoreData/Models/MXRoomLastMessageMO.swift
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- changelog.d/pr-1718.change
This PR adds the AES encryption for rooms' last messages before they get stored into Core Data.
Fixes: https://github.com/vector-im/element-ios/issues/7358
| Before | After | 
| --- | ---|
| ![b](https://user-images.githubusercontent.com/19324622/220079479-af2d2137-251c-42e4-81dc-41e9063278a7.png)|![a](https://user-images.githubusercontent.com/19324622/220079527-e0b96897-c24f-4c00-aa26-59da76533f0f.png)|
> Encrypt rooms' last messages

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/MXBackgroundSyncService.swift
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCryptoV2Factory.swift
- MatrixSDK/Crypto/MXCryptoV2Feature.swift
- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- changelog.d/pr-1719.change
Create `MXCryptoV2Feature` protocol, implemented in the main app, which controls whether rust-based crypto sdk is enabled or not.
This allows more nuanced approach to enabling the feature (incl. at runtime), for instance by combining manual opt-in and remote feature flags.
> Control CryptoSDK via feature flag

- MatrixSDK/Data/MXRoomSummary.m
- changelog.d/pr-1723.bugfix
Fixes https://github.com/vector-im/element-ios/issues/7090
> Fix unread filter logics

- MatrixSDK/Data/MXRoomSummaryUpdater.m
- MatrixSDK/MXSession.m
- changelog.d/pr-1727.change
This PR fixes part of [element-ios #6612](https://github.com/vector-im/element-ios/issues/6612)
When creating a direct chat with a 3rd party, use their email as the direct room id.
When updating the room summary, use the third party display name, if available, rather than empty room.
> Direct room with a third party

- MatrixSDK/Crypto/CryptoMachine/MXKeysQueryScheduler.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXKeysQuerySchedulerUnitTests.swift
- changelog.d/pr-1726.change
Fix a minor bug where starting the next pending `keys/query` would use the wrong list of users used to deduplicate requests. The consequence of this bug is that we may be executing slightly more requests than necessary
> Use correct next users with keys query

- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDKTests/MXRoomTests.m
- changelog.d/pr-1730.bugfix
It was previously stored alongside rooms:
```
├── rooms
│   ├── !TDpKIKrKaCXyncpKsH:localhost:8480
│   │   ├── messages
│   │   ├── state
│   │   └── threadedReadReceipts
│   └── unreadRooms
````
This created an unexpected behavior because the method `MXFileStore.countOfRooms()` is based on number of items in the `rooms` folder. The result was the app recomputing room summaries on each startup if there were unread rooms: https://github.com/matrix-org/matrix-ios-sdk/blob/v0.25.2/MatrixSDK/MXSession.m#L470
The file is not at an upper level.
> Unread rooms: Move the storage file to a better location

- MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventEncryption.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDKTests/Crypto/Algorithms/RoomEvents/MXRoomEventEncryptionUnitTests.swift
- changelog.d/pr-1733.change
Resolves https://github.com/matrix-org/element-web-rageshakes/issues/19974
There are some rare cases when room members are not correctly tracked in `OlmMachine` (investigating separately), which is typically triggered by `m.room.membership` events. To solve the consequence (rather than the root cause), ensure that we always update tracked users when sharing keys, even if this does not trigger keys query for the current event, but will do so before the next one. In other words if we do indeed have users that are not yet tracked, they will be unable to decrypt at most the current message, but should recieve the key for the next message.
> Always update tracked users when sharing keys

- MatrixSDK/MXSDKOptions.h
- MatrixSDK/MXSDKOptions.m
- MatrixSDK/MXSession.m
- MatrixSDK/MXSessionStartupProgress.swift
- MatrixSDKTests/MXSessionStartupProgressUnitTests.swift
- changelog.d/7417.change
Relates to https://github.com/vector-im/element-ios/issues/7417
Refactor `MXSessionStartupProgress` to align with current use case requirements, where we do not display sync attempts or copy for individual stages but rather calculate an overall progress.
> Improved session startup progress

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/Data/MXRoomSummary.m
- MatrixSDK/MatrixSDKVersion.m
- changelog.d/pr-1736.bugfix
This PR prepares the release of MatrixSDK v0.26.1.
Notes:
- This PR targets `release/0.26.1/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.26.1/master` into `master` to tag the release.
--- …
> Release 0.26.1

- MatrixSDK/VoIP/MXCallManager.m
- changelog.d/pr-1739.bugfix
Make sure we made requests one by one to avoid to create weird scenarii.
> MXCallManager: Make call transfer requests sequential

- MatrixSDK.podspec
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventEncryption.swift
- MatrixSDK/Crypto/CryptoMachine/Extensions/EventEncryptionAlgorithm+String.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/Data/MXRoomSettings.swift
- MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
- MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/MXCryptoV2Factory.swift
- MatrixSDK/Crypto/Migration/Data/MXCryptoMigrationStore.swift
- MatrixSDK/Crypto/Migration/MXCryptoMigrationV2.swift
- MatrixSDK/Crypto/Migration/MXCryptoVersion.h
- MatrixSDKTests/Crypto/Algorithms/RoomEvents/MXRoomEventEncryptionUnitTests.swift
- MatrixSDKTests/Crypto/CryptoMachine/Extensions/EventEncryptionAlgorithmUnitTests.swift
- MatrixSDKTests/Crypto/Data/Store/MXMemoryCryptoStore.swift
- MatrixSDKTests/Crypto/MXCryptoV2FactoryTests.swift
- MatrixSDKTests/Crypto/Migration/Data/MXCryptoMigrationStoreUnitTests.swift
- MatrixSDKTests/Crypto/Migration/MXCryptoMigrationV2Tests.swift
- MatrixSDKTests/TestPlans/UnitTests.xctestplan
- MatrixSDKTests/TestPlans/UnitTestsWithSanitizers.xctestplan
- Podfile
- Podfile.lock
- changelog.d/pr-1735.change
Resolves https://github.com/vector-im/element-ios/issues/7419
Related rust-sdk change: https://github.com/matrix-org/matrix-rust-sdk/pull/1460
Until now the rust-based Crypto V2 still required access to the legacy Realm crypto database to store the following data:
- room algorithms
- whether to block untrusted devices per room
- whether to block untrusted devices globally
The rust-sdk can now store this data as well (after the above PR is merged) so we can fully deprecate the `MXCryptoStore` in the ios sdk.
Because there are already clients in production that have migrated from legacy to rust crypto we need to consider several use cases for migration of settings:
- new login => no realm store, so nothing to migrate
- user in legacy crypto => we can migrate settings via the existing …
> Fully deprecate MXCryptoStore

- MatrixSDK.podspec
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/Background/Crypto/MXLegacyBackgroundCrypto.swift
- MatrixSDK/Crypto/Algorithms/MXDecryptionResult.h
- MatrixSDK/Crypto/Algorithms/MXEventDecryptionDecoration.swift
- MatrixSDK/Crypto/Algorithms/MXEventDecryptionResult.h
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventDecryption.swift
- MatrixSDK/Crypto/CryptoMachine/Extensions/MXEventDecryptionResult+DecryptedEvent.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDKTests/Crypto/Algorithms/Megolm/MXMegolmDecryptionUnitTests.swift
- MatrixSDKTests/Crypto/CryptoMachine/DecryptedEvent+Stub.swift
- MatrixSDKTests/JSONModels/MXEventFixtures.swift
- Podfile
- Podfile.lock
- changelog.d/pr-1743.api
Previously the legacy SDK would expose `untrusted` property to mark events that were decrypted using an untrusted key (e.g. one downloaded from asymmetrical backup). On the app side, this untrusted property would be combined with other encryption properties, namely the trust of the sender and their device. Only then the combine result gets turned into a visual decoration (e.g. red or grey shield).
To improve this, and align with rust-sdk, expose the decoration color directly from the crypto SDK, alongside an explanation message if necessary. This moves some of the trust computation down to the crypto module and leaves the app with fewer decisions to make.
> Add event decryption decoration

- MatrixSDK/Crypto/CrossSigning/MXCrossSigningV2.swift
- MatrixSDK/Crypto/MXCryptoV2Factory.swift
- MatrixSDK/Crypto/MXCryptoV2Feature.swift
- MatrixSDK/Crypto/Migration/MXCryptoVersion.h
- MatrixSDKTests/Crypto/MXCryptoV2FactoryTests.swift
- MatrixSDKTests/Crypto/Migration/MXCryptoMigrationV2Tests.swift
- changelog.d/pr-1751.change
Set `needsVerificationUpgrade` property when migrating from legacy to rust crypto, which will be used to display altered UX for "verify your session" modal. This is because sessions considered as verified in the legacy crypto should not always be considered as verified in rust crypto, as the latter imposes stricter rules on session verification. In case the rust *does* consider the session as verified the property is reset.
Note that this is not meant to be 100% reliable way to detect verification state change. For instance if legacy crypto was already unverified, migrating to rust would still display the "upgrade verification" dialoge. This is acceptable, given that the "upgrade verification" prompt will only be shown until either successful verification or ignoring of the alert. …
> Upgrade verification if necessary

- MatrixSDK.podspec
- changelog.d/pr-1754.build
I picked the Lite version as it excludes a dependency on Giphy which appears to be a 22MB binary for iOS and I'm not sure we really need that.
Closes https://github.com/vector-im/customer-retainer/issues/28 although discussed with @benparsons that this on its own isn't enough to enable screensharing. Extra info should be in Jira.
> Upgrade to Jitsi pod to 7.0.1-lite

- MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventDecryption.swift
Convert an error log into a warning (which is not tracked to Sentry). This is an aggregate log that prints the number of undecrypted vs total events, after we have already logged (incl to Sentry) individual undecryptable events.
> Remove unnecessary error log

- MatrixSDK/Crypto/Algorithms/MXEventDecryptionDecoration.swift
- MatrixSDK/Crypto/CryptoMachine/Extensions/MXEventDecryptionResult+DecryptedEvent.swift
- MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
- MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransactionV2.swift
- MatrixSDKTests/Crypto/Verification/Transactions/QRCode/MXQRCodeTransactionV2UnitTests.swift
Resolves https://github.com/vector-im/element-ios/issues/7470
We log several errors to Sentry regarding QR codes which should not really be errors, namely the inability to generate QR code data when the other side cannot scan (but we can scan theirs).
Improve this by creating a dedicated enum to capture these two variants as opposed to an optional that is more ambiguous
> Resolve QR warnings

- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoMachineUnitTests.swift
- changelog.d/pr-1763.bugfix
Resolves https://github.com/vector-im/element-ios/issues/7488
When we recieve a "Mismatched account" error (meaning we have existing data for the current user but under a different device) we need to delete the previous data first before we can try to create the machine.
Note that this behaviour should not be happening as we delete data on logouts, but there are clearly edge-cases where this still occurs. In those cases we will log the error.
> Delete data for mismatched accounts

- MatrixSDK.podspec
- MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
- MatrixSDKTests/Crypto/Algorithms/Megolm/MXMegolmDecryptionUnitTests.swift
- Podfile
- Podfile.lock
- changelog.d/pr-1765.change
When fetching device info, ensure that we retrieve it via its sender key, which may not be set on an event yet, but is a part of the decryption result.
Additionally upgrade crypto sdk version
> Fetch device info by sender key

- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.h
- MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
- MatrixSDK/Crypto/CrossSigning/MXCrossSigningV2.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/Recovery/MXRecoveryService.m
- MatrixSDKTests/Crypto/CrossSigning/MXCrossSigningV2UnitTests.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/MXCrossSigningTests.m
- changelog.d/pr-1768.change
`MXRecoveryService` responsible for restoring services after the import of cross-signing keys (e.g. when passphrase is entered) should verify the current user and device and upload relevant signature. However an early exit only checking current user trust and not the device trust will prevent this from happening ("canCrossSign" does not imply "device is signed").
To resolve this, remove the early exit in `MXRecoveryService` and always call `setUserVerification` and `crossSignDeviceWithDeviceId`. To avoid duplicate verifications of an already trusted device, add an early exit into `crossSignDeviceWithDeviceId` instead.
> Ensure device signed after restoring cross-signing keys

- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/Crypto/MXCryptoV2Factory.swift
- MatrixSDKTests/Crypto/MXCryptoV2FactoryTests.swift
- changelog.d/pr-1769.change
Now that rust crypto is fully rolled out, and all relevant data from realm database migrated, there is no need to keep it around. The database will be deleted after successfull migration
> Remove legacy crypto store after migration

- MatrixSDK/Crypto/CrossSigning/MXCrossSigningV2.swift
- MatrixSDKTests/Crypto/CrossSigning/MXCrossSigningV2UnitTests.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- changelog.d/pr-1774.bugfix
Calling `[MXRestClient authSessionForRequestWithMethod]` is supposed to return an auth session which is then passed to crypto machine to setup cross-singing keys. It is however valid for the auth session to be empty, which is already accounted for in `MXLegacyCrossSigning`, but not in `MXCrossSigningV2`. This PR fixes that issue by behaving in the same way as legacy cross-signing, namely returning empty auth session instead of throwing an error.
> Setup cross-signing even without auth session

- MatrixSDK/JSONModels/Aggregations/MXAggregationPaginatedResponse.m
- changelog.d/7551.bugfix
Fixes https://github.com/vector-im/element-ios/issues/7551
> Fix threads empty state: Allow empty array for chunk in MXAggregationPaginatedResponse

- MatrixSDK/Background/MXBackgroundPushRulesManager.swift
- MatrixSDK/MXRestClient.m
- MatrixSDK/NotificationCenter/MXNotificationCenter.m
- MatrixSDK/Space/MXSpaceNotificationCounter.swift
- changelog.d/7576.change
This PR add support for [MSC3987](https://github.com/matrix-org/matrix-spec-proposals/pull/3987) which deprecates the `dont_notify` action for a `push_rule`.  (linked to [Element-iOS #7576](https://github.com/vector-im/element-ios/issues/))
> Implement MSC3987: Push actions clean-up

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK/MatrixSDKVersion.m
- changelog.d/7601.bugfix
This PR prepares the release of MatrixSDK v0.26.12.
Notes:
- This PR targets `release/0.26.12/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.26.12/master` into `master` to tag the release.
--- …
> Release 0.26.12

- MatrixSDK.podspec
- MatrixSDK/Crypto/CrossSigning/Data/MXCryptoUserIdentityWrapper.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/Migration/Data/MXCryptoMigrationStore.swift
- MatrixSDKTests/Crypto/CrossSigning/Data/MXCrossSigningInfoUnitTests.swift
- MatrixSDKTests/Crypto/CrossSigning/MXCrossSigningInfoSourceUnitTests.swift
- MatrixSDKTests/Crypto/CrossSigning/MXCrossSigningV2UnitTests.swift
- MatrixSDKTests/Crypto/CryptoMachine/Device+Stub.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoMachineUnitTests.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/Crypto/Verification/Requests/MXKeyVerificationRequestV2UnitTests.swift
- MatrixSDKTests/Crypto/Verification/Transactions/QRCode/MXQRCodeTransactionV2UnitTests.swift
- MatrixSDKTests/Crypto/Verification/Transactions/SAS/MXSASTransactionV2UnitTests.swift
- MatrixSDKTests/JSONModels/MXKeysQueryResponseUnitTests.swift
- Podfile
- Podfile.lock
This PR bumps the Matrix Crypto SDK version to 0.3.11 and fixes newly introduced problems:
* breaking api changes following uniffi udl->macro replacement
* toDevice sync response event processing after JSON format change + improved rust side API to avoid it in the future
* broken secret recovery following USK and SSK enum associtated value order change
Successful integration test run here https://github.com/matrix-org/matrix-ios-sdk/actions/runs/5609719049/jobs/10263800231
> Matrix sdk crypto update

- MatrixSDK/Background/MXBackgroundPushRulesManager.swift
- MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
- MatrixSDK/Space/MXSpace.swift
- changelog.d/1810.bugfix
- changelog.d/7636.bugfix
- changelog.d/pr-1809.bugfix
* fixes power level events force unwrap crash
* Fixes #1810
* Fixed vector-im/element-ios/issues/7636
> Various bug fixes

- MatrixSDK/JSONModels/Login/MXLoginSSOFlow.h
- MatrixSDK/JSONModels/Login/MXLoginSSOFlow.m
- changelog.d/pr-1811.feature
Now the `MXSSOSessionFlow` is able to parse the delegate OIDC compatibility flag.
> delegate OIDC compatibility flag added

- MatrixSDK.podspec
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- Podfile
- Podfile.lock
Fixes https://github.com/vector-im/customer-retainer/issues/113
Depends on https://github.com/matrix-org/matrix-rust-sdk/pull/2641
> Fix QR login support with cryptoV2

- MatrixSDK/Data/MXRoomState.m
- changelog.d/pr-1833.bugfix
This fixes an issue in contexts such as a Notification Service where there might not be a session.
In the instance of Element, if an invite was sent and the app was in the background, it would send `[matrixSession.matrixRestClient stateOfRoom:success:failure:]` after calling this method with a nil session, so the notification would stall and then timeout.
> Fix unhandled callback when the session is nil.

- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCrypto.m
- MatrixSDK/Crypto/MXCryptoV2.swift
Preliminary work for https://github.com/element-hq/element-ios/issues/7767
Exposes the user current device creation local timestamp.
> Add own device creation ts in crypto API

- MatrixSDK/Data/RoomList/Common/MXRoomListDataSortable.swift
- MatrixSDK/Data/RoomList/CoreData/MXCoreDataRoomListDataFetcher.swift
- changelog.d/pr-1851.change
- changelog.d/sort-room-list-alphabetically-case-insensitive.change
When sorting room list alphabetically, sort it case-insensitive.
> Sorting room list alphabetically case-insensitive.

- MatrixSDK.podspec
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/Dehydration/DehydrationService.swift
- MatrixSDK/Crypto/Migration/Data/MXCryptoMigrationStore.swift
- MatrixSDKTests/Crypto/CryptoMachine/Device+Stub.swift
- MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
- MatrixSDKTests/Crypto/Migration/Data/MXCryptoMigrationStoreUnitTests.swift
- MatrixSDKTests/Crypto/Verification/Transactions/QRCode/QrCodeStub.swift
- MatrixSDKTests/Crypto/Verification/Transactions/SAS/SasStub.swift
- Podfile
- Podfile.lock
- build.sh
- changelog.d/pr-1853.change
Updates crypto sdk version to [0.4.1](https://github.com/matrix-org/matrix-rust-sdk/releases/tag/matrix-sdk-crypto-ffi-0.4.1)
Some breaking changes:
- some key data can directly be passed as Data instead of UInt8 array. 
- Other changes on pickle format.
- `bootstrapCrossSigning` now returning an optional device key upload
**Updated the minimum ios version to 13, was previously 11.0 (to match the new pod min)**
**Updated the minimum osx version to 10.15, was previously 10.10**
> Bump rust crypto sdk version 0.4.1

- MatrixSDK.podspec
- MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventDecryption.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
- MatrixSDK/Crypto/Dehydration/DehydrationService.swift
- MatrixSDK/Crypto/MXCrypto.h
- MatrixSDK/Crypto/MXCryptoV2.swift
- MatrixSDK/MXSession.m
- Podfile
- Podfile.lock
depends on https://github.com/matrix-org/matrix-rust-sdk/pull/3462
Partial fix for the NSE process causing olm session wedging.
See element-x related issue https://github.com/matrix-org/matrix-rust-sdk/issues/3110.
The crypto store is keeping a cache of olm sessions for a given device. When using multiprocess this cache will get outdated and causing session wedging.
If the main app is inactive and the NSE do process a sync new olm sessions might be created (or mutated, like when replying to a key request). If the main process is then resumed it will use it's outdated cache instead of reloading from store.
The improvement here is that we will invalidate the cache when the main app enters foreground to limit the possible occurences of outdated caches.
> Invalidate crypto store cache when entering foreground

- MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m
- changelog.d/pr-1866.bugfix
Fix a bug in Element iOS : when the user answer a VoIP call from the "Answer" button in Element room timeline, very often, his correspondant can't hear him.
It's because the Audio Session is initialized too late. See https://developer.apple.com/forums/thread/64544 (7th post from Apple Engineer)
See this issue in Element Github: https://github.com/element-hq/element-ios/issues/7721
See this issue in Tchap: https://github.com/tchapgouv/tchap-ios/issues/1047
> Fix CallKit audio session late init

- MatrixSDK/Categories/MXKeysQueryResponse+Extensions.swift
- MatrixSDK/Categories/MXRestClient+Extensions.swift
- MatrixSDK/Contrib/Swift/MXRestClient.swift
- MatrixSDK/Crypto/CryptoMachine/MXCryptoRequests.swift
- MatrixSDK/JSONModels/MXJSONModels.h
- MatrixSDK/JSONModels/MXJSONModels.m
- MatrixSDK/MXRestClient.h
- MatrixSDK/MXRestClient.m
Fixes https://github.com/element-hq/element-ios/issues/7795
The new [MSC3814](https://github.com/matrix-org/matrix-spec-proposals/pull/3814)https://github.com/matrix-org/matrix-spec-proposals/pull/3814 is introducing a new format for dehydrated devices (to get messages even if all your sessions are logged out). 
As per the new format, the DeviceKey payload from a keys/query call now contains a new boolean field `dehydrated`, that is used when computing the signature.
The problem is that the SDK converts the http response to a JSON Model `MXKeysQueryResponse` and this model was not aware of that field. As a consequence when passing back the response to rust via `markRequestAsSent` using `model.jsonString()`, the `dehydrated` field was dropped, thus the rust layer was refusing the device …
> Fix | Share room keys with dehydrated devices with rust stack

- MatrixSDK/Contrib/Swift/JSONModels/MXRoomPowerLevels.swift
- changelog.d/pr-1869.change
Expose 2 methods from extension MXRoomPowerLevels to be available to client (like Element or Tchap).
Needed to check user room power level when live sharing location in room.
> Expose MXRroomPowerLevels Swift wrappers to Element

- CONTRIBUTING.md
- changelog.d/pr-1875.doc
The Matrix.org Foundation is rolling out an updated DCO across all public repositories in its namespace. Of note, this DCO does not require the use of "real" or "legally identifiable" names.
(Meta: will add required changelog file as instructed in the next commit to this, opening PR first to get a reference number.)
Signed-off-by: Josh Simmons <git@josh.tel>
> bring in line with foundation DCO

- .github/workflows/ci-integration-tests.yml
- .github/workflows/ci-unit-tests.yml
<del>The actions are now failing without it I believe.</del>
It was the v3 action, updated to v4 (which needs the token anyway)
> Use the codecov token.

- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/JSONModels/Call/MatrixRTC/MXCallNotify.h
- MatrixSDK/JSONModels/Call/MatrixRTC/MXCallNotify.m
- MatrixSDK/JSONModels/Event/MXMentions.h
- MatrixSDK/JSONModels/Event/MXMentions.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/Utils/MXTools.m
This PR adds support for [MSC4075](https://github.com/matrix-org/matrix-spec-proposals/pull/4075) to detect call ringing for MatrixRTC calls (not supported in any other way in this SDK).
Part of https://github.com/element-hq/element-ios/issues/7861
> Add support for MatrixRTC m.call.notify events.

- CHANGES.md
- MatrixSDK.podspec
- MatrixSDK.xcodeproj/project.pbxproj
- MatrixSDK/JSONModels/Call/MatrixRTC/MXCallNotify.h
- MatrixSDK/JSONModels/Call/MatrixRTC/MXCallNotify.m
- MatrixSDK/JSONModels/Event/MXMentions.h
- MatrixSDK/JSONModels/Event/MXMentions.m
- MatrixSDK/JSONModels/MXEvent.h
- MatrixSDK/JSONModels/MXEvent.m
- MatrixSDK/MatrixSDKVersion.m
- MatrixSDK/Utils/MXTools.m
This PR prepares the release of MatrixSDK v0.27.16.
Notes:
- This PR targets `release/0.27.16/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.27.16/master` into `master` to tag the release.
--- …
> Release 0.27.16

- Gemfile.lock
- MatrixSDK/MXRestClient.m
As requested by @turt2live, Synapse and matrix.org support the stable endpoint now. I haven't added a fallback to the unstable endpoint for this as it doesn't seem worthwhile to me.
> Use the stable endpoint when reporting rooms.
