matrix-org/matrix-ios-sdk

sdk/MatrixSDK/Data/MXRoom.m

Handle only once the state event during live events processing.

---

MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

Implement joinRoom action in case of server sync v2 use.

MXSession: V2 sync joining.

---

MatrixSDK/Data/MXRoom.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXSession.m
MatrixSDKTests/MXRestClientTests.m

We add some improvements in response handling during server sync v2.

BugFix SYIOS-169: Improve MXEvent conversion.

---

MatrixSDK/Data/MXRoomState.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.h
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m

Did some refactoring according to Xcode profiler.
Tested when doing a big app resuming.

Performance profiling

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/MXRoomAccountData.h
MatrixSDK/Data/MXRoomAccountData.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXStore.h
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m
MatrixSDK/Utils/MXTools.m
MatrixSDKTests/MXRestClientTests.m
MatrixSDKTests/MXRoomTests.m
MatrixSDKTests/MXSessionTests.m
MatrixSDKTests/MXStoreFileStoreTests.m
MatrixSDKTests/MXStoreTests.h
MatrixSDKTests/MXStoreTests.m

Added room tag support and some helper methods in MXSession to get ordered list of tagged rooms

Room tag support

---

MatrixSDK/MXSession.m

Fix a race conditions in the room invite arrays

room_invite_race_conditions.

---

MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m

Exclude the current user from the read receipts list.

MXRoom read receipts handling.

---

MatrixSDK/MXSession.m

Improve the invite management 
-> when the user joins a room on his own device, the room is removed from invited list as soon as the join request succeeds.
-> to delete a room from the invited ones list, we also check by roomId.
Indeed, during the room initial sync, the room object is replaced by a new one so the search by object is corrupted.

room_invite_race_condition_3

---

MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m

Update with the last spec changes.

MXPublicRoom spec update: Added worldReadable, guestCanJoin & avatarURL

---

MatrixSDK/Data/MXRoom.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXSession.m

SPEC 254: V2 sync: return state corresponding to the *start* of the timeline.

Update syncv2 implementation

---

MatrixSDK/JSONModels/MXJSONModel.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/Utils/MXHTTPClient.m
MatrixSDKTests/MXRestClientTests.m

The Client-Server API documentation is not clear in some advanced parameters description.
I marked them with TODO_SEARCH.
These parameters are not used for doing basic search. I will come back to them later.

Search api support

---

MatrixSDK/MXSession.m

Load push rules from server before loading store data in order to highlight the bing events.

MXSession: Bug Fix - Push rules refresh

---

MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/MXRoomState.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/JSONModels/MXJSONModel.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/JSONModels/MXRoomPowerLevels.m
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.m
MatrixSDK/NotificationCenter/Checker/MXPushRuleRoomMemberCountConditionChecker.m

Added helpers methods in MXJSONModel.h to help validating data before storing them in objects.
All data coming from hs should be handled by these methods,
This PR relates to SYIOS-203 iOS crashes on non numeric power levels (https://matrix.org/jira/browse/SYIOS-203)

Json validation

---

MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m

[MXRoom paginateBackMessages]: added an argument to load only available messages from the store

Room page loading improvement

---

MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

Take into account pending Pause (if any) at the end of resume.

Bug Fix: App crashes on resume

---

MatrixSDK/MXRestClient.m

BugFix vector-ios #75

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/MXEventTimeline.h
MatrixSDK/Data/MXEventTimeline.m
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDKTests/MXEventTests.m
MatrixSDKTests/MXEventTimelineTests.m
MatrixSDKTests/MXRestClientTests.m

This is then possible to paginate backwards and forwards.
The implementation makes use of /context and /messages in forwards mode.

Create a timeline from a past event

---

MatrixSDK/Data/MXEventTimeline.m

User profile: user settings may be modified during pagination in past timeline

Fixed https://github.com/vector-im/vector-ios/issues/176

---

MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m

MXRestClient - Add API to check user id availability.

Registration support

---

MatrixSDK/Utils/MXHTTPClient.m

It was not possible to cancel an operation for which the app was waiting for the connection.

BugFix: Cancel correctly pending operation

---

MatrixSDK/Data/Store/MXCoreDataStore/MXCoreDataStore.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
MatrixSDK/Data/Store/MXStore.h

Bug Fix:Cannot paginate to the origin of the room

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.m

Bug Fix: Store - Detect and remove corrupted room data.

---

MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

This allows to join a room where the user has been invited by a 3PID invitation

MXSession/MXRestClient: Added [self join:withSignUrl:]

---

MatrixSDK/MXRestClient.m

- Remove internal getRegisterOrLoginFlow method

MXRestClient: Fix registration from multi devices

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXMemoryStore/MXReceiptData.m

Loading is around 30% faster than before. 
Yeah, decoding dictionary consumes time.

MXFileStore: Improved storage and loading of read receipts

---

MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/Store/MXCoreDataStore/MXCoreDataStore.m
MatrixSDK/Data/Store/MXFileStore/MXFileRoomStore.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.h
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
MatrixSDK/Data/Store/MXStore.h

https://github.com/vector-im/vector-ios/issues/254

BugFix: Wrong application icon badge number

---

MatrixSDK/Data/MXUser.h
MatrixSDK/Data/MXUser.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/Utils/MXTools.m

No more spec-ed presence types have been removed too.

Presence: Manage the currently_active parameter

---

MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXFileStore/MXFileStoreMetaData.h
MatrixSDK/Data/Store/MXFileStore/MXFileStoreMetaData.m
MatrixSDK/Data/Store/MXStore.h
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

to fix https://github.com/vector-im/vector-ios/issues/295
Note this PR introduced the support of top-level account data. The support is light and limited to the ignore users list.

Report abuse and ignore user

---

MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

https://github.com/vector-im/vector-ios/issues/311

Bug Fix: all blank after upgrade; no spinner

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/MXAccountData.h
MatrixSDK/Data/MXAccountData.m
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.m
MatrixSDK/NotificationCenter/MXNotificationCenter.h
MatrixSDK/NotificationCenter/MXNotificationCenter.m
MatrixSDKTests/MXAccountDataTests.m

https://github.com/matrix-org/matrix-ios-sdk/issues/106: Use account_data in /sync to get update of push rules

Account data and pushrules

---

MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m

Add API to set canonical alias too.
https://github.com/vector-im/vector-ios/issues/412
TODO: Add unitary tests

MXRestClient: Add API to add/remove a room alias.

---

MatrixSDK/Data/MXRoomState.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m

https://github.com/vector-im/vector-ios/issues/528
Note: the file version has been increased to refresh rooms aliases storage.

Bug Fix - Room Settings: some addresses are missing

---

MatrixSDK/Utils/MXTools.h
MatrixSDK/Utils/MXTools.m

SDK part to fix https://github.com/vector-im/vector-ios/issues/442

Vector 442

---

MatrixSDK/MXEnumConstants.h
MatrixSDK/MXEnumConstants.m
MatrixSDK/Utils/MXTools.h
MatrixSDK/Utils/MXTools.m

https://github.com/vector-im/vector-ios/issues/547

MXTools: Add methods to create permalinks to room or event

---

MatrixSDK/Data/MXEventTimeline.m
MatrixSDK/Data/MXMyUser.h
MatrixSDK/Data/MXMyUser.m
MatrixSDK/Data/MXUser.h
MatrixSDK/Data/MXUser.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.h
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXFileStore/MXFileStoreMetaData.h
MatrixSDK/Data/Store/MXFileStore/MXFileStoreMetaData.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.h
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
MatrixSDK/Data/Store/MXStore.h
MatrixSDK/MXSession.m
MatrixSDKTests/MXStoreFileStoreTests.m
MatrixSDKTests/MXStoreTests.h
MatrixSDKTests/MXStoreTests.m

This PR fixes "Room members: a member is displayed offline by mistake" https://github.com/vector-im/vector-ios/issues/406

Store MXUsers

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.m

We were tracking the ID of "the current background task" in a member field on MXFileStore.
However, there's nothing to stop parallel background tasks from happening, at which point
we lose track of the background task in flight and so cannot terminate it; so it leaks.
Also adds a shedload of debug logging for commit operations to the filestore.

Stop leaking background tasks, which kill the app after 180s of bg.

---

MatrixSDK/VoIP/MXCall.m

https://github.com/vector-im/vector-ios/issues/577

MXCall: Add a timeout for outgoing calls

---

MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

https://github.com/vector-im/vector-ios/issues/529

MXSession: Expose the list of user ids for whom a 1:1 room exists.

---

MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/Utils/MXTools.m

https://github.com/vector-im/vector-ios/issues/559

MXEvent: Add MXEventTypeRoomEncrypted Matrix event type

---

MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

Move MXRoom.acknowledgableEventTypes into MXSession

---

MatrixSDK/Crypto/Data/MXKey.h
MatrixSDK/Crypto/Data/MXKey.m
MatrixSDK/Crypto/MXCrypto.m

This branch was an attempt to merge 4 e2e features available on vector web.
But only 2 features were implemented before the weekend, which are:
- Consistency checks for E2E device downloads
- Sign one-time keys and check their signatures
The last one allows to be able to talk to https://riot.im/app & develop again.

Update e2e 2/4

---

MatrixSDK/MXSession.m

move the *to device* events management before the room ones.

fix_to_device_events_management_order

---

MatrixSDK/Crypto/MXEncryptedAttachments.h
MatrixSDK/Crypto/MXEncryptedAttachments.m

Adds class for taking a file, encrypting it, uploading it to the media repo and returning the object that goes in the message body.
Support for reading encrypted attachment coming soon.

Support for encrypting attachments

---

MatrixSDK/Crypto/MXCrypto.m

Add format param to MXDecryptingErrorUnableToDecryptReason
(Without extyra changes this time)

Don't crash on undecryptable events, take 2

---

MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m

Like the web app, rotation are based on default values defined by the spec. The code does not handle parameters that can come with the m.room.encryption event.

Crypto: Rotate megolm outbound session

---

MatrixSDK/Crypto/MXEncryptedAttachments.m

Add padding to base64 or iOS won't decode it

---

MatrixSDK/MXRestClient.m

https://github.com/vector-im/vector-ios/issues/799 
Kind of patch to match what synapse expects.

[Register flow] Register with a mail address fails

---

MatrixSDK/Crypto/Algorithms/MXDecrypting.h
MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Crypto/MXOlmDevice.h
MatrixSDK/Crypto/MXOlmDevice.m
MatrixSDK/Data/MXEventTimeline.h
MatrixSDK/Data/MXEventTimeline.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m
MatrixSDKTests/MXCryptoTests.m

Crypto: Mitigate replay attack

---

MatrixSDK/Crypto/MXOlmDevice.h
MatrixSDK/Crypto/MXOlmDevice.m
MatrixSDKTests/MXCryptoTests.m

Port of https://github.com/matrix-org/matrix-js-sdk/pull/276/

Crypto: Ignore reshares of known megolm sessions

---

MatrixSDK/Crypto/Algorithms/MXDecrypting.h
MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
MatrixSDK/Crypto/Data/Store/MXFileCryptoStore/MXFileCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXFileCryptoStore/MXFileCryptoStore.m
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Crypto/MXOlmDevice.m
MatrixSDK/Data/MXRoom.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/MXSession.m
MatrixSDKTests/MXCryptoTests.m

Port of https://github.com/matrix-org/matrix-js-sdk/pull/288 (check comment there)

Decrypt after keys arrive

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/MatrixSDK.h
MatrixSDK/Utils/MXLRUCache.h
MatrixSDK/Utils/MXLRUCache.m
MatrixSDK/Utils/MXTools.h
MatrixSDK/Utils/MXTools.m
MatrixSDK/Utils/Media/MXMediaLoader.h
MatrixSDK/Utils/Media/MXMediaLoader.m
MatrixSDK/Utils/Media/MXMediaManager.h
MatrixSDK/Utils/Media/MXMediaManager.m

Move MXKLRUCache at SDK level.
- Add MXMediaManager, MXMediaLoader and MXLRUCache classes.
- Move the file management methods from MXKTools to MXTools.

Move MXKMediaManager and MXKMediaLoader at SDK level.

---

MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDKTests/MXCryptoTests.m

Port of https://github.com/matrix-org/matrix-js-sdk/pull/294

Crypto: distinguish unknown users from deviceless users

---

MatrixSDK/Crypto/Data/MXUsersDevicesMap.h
MatrixSDK/Crypto/Data/MXUsersDevicesMap.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDKTests/MXCryptoTests.m

Port of https://github.com/matrix-org/matrix-js-sdk/pull/297

Crypto: Avoid a packetstorm of device queries on startup

---

MatrixSDK/Crypto/Algorithms/MXEncrypting.h
MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
MatrixSDK/Crypto/Algorithms/Olm/MXOlmEncryption.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDKTests/MXCryptoTests.m

Crypto: Fix block device

---

MatrixSDK/Crypto/MXCrypto.m

This fixes https://github.com/vector-im/riot-web/issues/2676 on iOS.
Little refactoring inside

Get user own devices keys

---

MatrixSDK/Crypto/MXCrypto.m

The scenario is given here: https://github.com/matrix-org/matrix-ios-sdk/pull/197#discussion_r91102977

Crypto: Fix race when getting 2 new device events from the same user.

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Data/MXOlmInboundGroupSession.m
MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXFileCryptoStore/MXFileCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/MXSession.m
MatrixSDKTests/MXCryptoTests.m

https://realm.io
It is not yet enabled. The code still uses MXFileCryptoStore while I continue to test this new implementation.

Implementation of MXCryptoStore using Realm

---

MatrixSDK/Crypto/Data/Store/MXFileCryptoStore/MXFileCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXFileCryptoStore/MXFileCryptoStore.m
MatrixSDK/Crypto/MXCrypto.m

Crypto: Do a script to migrate from MXFileCryptoStore to MXRealmCryptoStore

---

MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

(kMXSessionCryptoDidCorruptDataNotification)

Crypto: Add a notification for corrupted crypto stor

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Data/MXEncryptedAttachments.m
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryRoomStore.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/MatrixSDK.h
MatrixSDK/Utils/Categories/NSData+MatrixSDK.h
MatrixSDK/Utils/Categories/NSData+MatrixSDK.m
MatrixSDK/Utils/MXTools.h
MatrixSDK/Utils/MXTools.m
MatrixSDK/VoIP/MXCall.m

- The event encryption is now handled directly by the sending methods of the `MXRoom` class.
- The local echo is handled by these methods too.

Outgoing Messages Refactoring:

---

MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m

Fix PR#210 comments.

---

MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/MXOlmDevice.m
MatrixSDKTests/MXCryptoTests.m

https://github.com/vector-im/riot-ios/issues/913.
It particularly fixes the bad behavior reported in the comment https://github.com/vector-im/riot-ios/issues/913#issuecomment-271944333.
Note there is a test for the reported issue.

Crypto: Fix "Failure to decrypt megolm event despite receiving the keys"

---

MatrixSDK/MXRestClient.m

see https://github.com/matrix-org/sydent/pull/35

MXRestClient: Move the bulk lookup API to /bulk_lookup

---

MatrixSDK/Data/MXRoom.m

https://github.com/vector-im/riot-ios/issues/970
MXRoom: Update the current outgoing messages by removing the sent messages and tagging as failed the others during the MXRoom instance initialization.

Bug Fix - Duplicated msg when going into room details

---

MatrixSDK/MXRestClient.m

https://github.com/vector-im/riot-ios/issues/965

App crashes a few seconds after a successful login

---

MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m

#227 
This PR fixes the root issue of the duplicates and fixes the db content by removing all duplicates.

Realm crypto store: Fix duplicates of olm and inbound megolm sessions

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.m

https://github.com/vector-im/riot-ios/issues/1008

Bug Fix: Got stuck syncing forever

---

MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m

https://github.com/vector-im/riot-ios/issues/1007

Bug Fix - Local echoes for typed messages stay (far) longer in grey.

---

MatrixSDK/Data/MXMyUser.m

Let the store be updated once at the end of the sync.

MXMyUser: do not force store update in case of user profile change.

---

MatrixSDK/Crypto/Algorithms/Olm/MXOlmEncryption.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDKTests/MXCryptoTests.m

iOS equivalent of https://github.com/matrix-org/matrix-js-sdk/pull/359

Room enable crypto invalidate devices

---

MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXFileCryptoStore/MXFileCryptoStore.m
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDKTests/MXCryptoTests.m

iOS equivalent to https://github.com/matrix-org/matrix-js-sdk/pull/336

Blacklist unverified devices

---

MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

This is the obj-c counterpart of changes made in https://github.com/matrix-org/matrix-js-sdk/pull/370.

Add Mxsession.catchingup

---

MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m

Else the 2nd and next decryption attempts will fail.
It fixes https://github.com/vector-im/riot-ios/issues/1028

Avoid to redecrypt the same event several times

---

MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/MXSession.m

The room comparator was missing

Bug Fix: App crashes if there are more than one invited room.

---

MatrixSDK.podspec
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/MatrixSDK.h
MatrixSDK/Utils/MXBugReportRestClient.h
MatrixSDK/Utils/MXBugReportRestClient.m
Podfile

https://github.com/vector-im/riot-ios/issues/1140

Add bug report API

---

MatrixSDK/Data/MXRoomSummary.m

The server may provide a not null count whereas we know locally the user has read all room messages
(see for example this issue https://github.com/matrix-org/synapse/issues/2193).
Patch: Ignore the server information when the user has read all messages.

Bug Fix: Wrong missed conversations.

---

MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/MXRoomSummary.h
MatrixSDK/Data/MXRoomSummary.m
MatrixSDK/Data/MXRoomSummaryUpdater.m
MatrixSDK/MXSession.m

Bug Fix: [MXSession resetRoomsSummariesLastMessage] freezes the app

---

MatrixSDK/VoIP/MXCall.h
MatrixSDK/VoIP/MXCall.m

These improvements help to fix issue [1101](https://github.com/vector-im/riot-ios/issues/1101). Also information about reason of call end is necessary for correct handling via CallKit. 

MXCall improvements

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/MXBackgroundModeHandler.h
MatrixSDK/MXDefaultBackgroundModeHandler.h
MatrixSDK/MXDefaultBackgroundModeHandler.m
MatrixSDK/MXSDKOptions.h
MatrixSDK/MXSession.m
MatrixSDK/Utils/MXHTTPClient.m

Otherwise, the pod does not build for app extension

Extract background mode handling outside of the pod

---

MatrixSDK/VoIP/CallStack/Jingle/MXJingleCallStackCall.m
MatrixSDK/VoIP/CallStack/MXCallStackCall.h
MatrixSDK/VoIP/MXCall.h
MatrixSDK/VoIP/MXCall.m
MatrixSDK/VoIP/MXCallManager.m

Calls improvements

---

MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m

Despite of the property name, for outcoming calls we need to provide the name of the callee

Update value that is setted to localizedCallerName for outgoing calls

---

MatrixSDK/VoIP/MXCall.m

More details at:
https://github.com/vector-im/riot-ios/issues/1326

VoIP: Fix outgoing call stays in "Call connecting..." whereas it is established

---

MatrixSDK/VoIP/CallKit/MXCallKitAdapter.h
MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m

Add notification about AVAudioSession activation

---

MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/JSONModels/MXJSONModel.h

https://github.com/matrix-org/riot-ios-rageshakes/issues/107
Add type checking.

Crypto: Fix crash when encountering a badly formatted olm message

---

MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/MXRoomAccountData.m
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/NotificationCenter/Checker/MXPushRuleDisplayNameCondtionChecker.m

Add type checking when retrieving data

Do not trust data sent by the homeserver

---

MatrixSDK/Utils/MXUIKitBackgroundModeHandler.m

We access the UIApplication shared instance by using the following code "[UIApplication performSelector:@selector(sharedApplication)]"

App Extension support: wrap access to UIApplication shared instance.

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Contrib/Swift/Data/MXSessionEventListener.swift
MatrixSDK/Contrib/Swift/MXSession.swift
MatrixSDK/Data/MXSessionEventListener.h
MatrixSDK/MXSession.h

Signed-off-by: Avery Pierce <aapierce0@gmail.com>

SwiftMatrixSDK: Add swift refinements to MXSession event listeners.

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Contrib/Swift/Data/MXRoom.swift
MatrixSDK/Contrib/Swift/MXImage.swift
MatrixSDK/Contrib/Swift/MXRestClient.swift
MatrixSDK/Data/MXRoom.h

Adds swift refinements to the MXRoom class.

SwiftMatrixSDK: Add Swift refinements to MXRoom class

---

MatrixSDK/Data/MXRoomSummary.h
MatrixSDK/Data/MXRoomSummary.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.h
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/MXSDKOptions.h
MatrixSDK/MXSDKOptions.m

Changes that we discussed yesterday

Improvements in MXFileStore

---

MatrixSDK/VoIP/MXCallManager.m

Add possibility to place an outgoing call for unprepared MXSession

---

MatrixSDK/Utils/MXHTTPClient.m

The major purpose of this PR is removing retain cycles

Fixes in MXHTTPClient

---

MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m

@giomfo I need this for the keys file to be sent preserving the filename

Added an option to send a file and keep it's filename

---

MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m

Passing roomID is more appropriate rather than userID. Connected with [#1463](https://github.com/vector-im/riot-ios/pull/1463)

Change value that is passed to CXHandle instance

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.h
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m

Add new async method for loading users with particular userIds

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.h
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m

Load only one room data and do it on the right thread

MXFileStore: Improve asyncStateEventsOfRoom & asyncAccountOfRoom 

---

MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m

(and the corresponding MXOpenIdToken object)

MXRestClient: Add the openIdToken method 

---

MatrixSDK/MXRestClient.m

As per https://github.com/matrix-org/synapse/issues/1860, this should be fixed on the iOS SDK as well.
Signed-off-by: Thibault Farnier <thibault.farnier@applidium.com>

Fix API for unbanning and kicking

---

MatrixSDK/Crypto/Data/MXDeviceList.h
MatrixSDK/Crypto/Data/MXDeviceList.m
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.m
MatrixSDKTests/MXCryptoTests.m

#340
This is a port of https://github.com/matrix-org/matrix-js-sdk/pull/535.

BF: Stale device lists when users re-join e2e rooms

---

MatrixSDK/Utils/MXHTTPClient.m
MatrixSDK/Utils/MXUIKitBackgroundModeHandler.m

2 bug fixes for background task leaks which may lead to https://github.com/vector-im/riot-ios/issues/1522

Background task release race condition

---

MatrixSDK/Data/MXRoomSummary.h
MatrixSDK/Data/MXRoomSummary.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m

MXRoomSummary: Add the server timestamp

---

MatrixSDK/Data/MXEventTimeline.m

to avoid crash. 
One case of crash is when the user changes the language in the Riot iOS app.

MXEventTimeline: BF: Add weak self check

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/MXRoomOperation.h
MatrixSDK/Data/MXRoomOperation.m

https://github.com/vector-im/riot-ios/issues/307

Preserve message order

---

MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/MXRoomSummary.h

https://github.com/vector-im/riot-ios/issues/1425

Bug Fix - Mark all messages as read does not work well

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/JSONModels/MXRoomPowerLevels.h
MatrixSDK/JSONModels/MXRoomPowerLevels.m
MatrixSDK/NotificationCenter/Checker/MXPushRuleSenderNotificationPermissionConditionChecker.h
MatrixSDK/NotificationCenter/Checker/MXPushRuleSenderNotificationPermissionConditionChecker.m
MatrixSDK/NotificationCenter/MXNotificationCenter.m

https://github.com/vector-im/riot-meta/issues/119

Notifications: implement @room notifications

---

MatrixSDK/Data/MXRoom.m

The room id was listed several times in the direct chats dictionary of the account data.

Handle correctly invite for direct chat.

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
MatrixSDK/Contrib/Swift/MXRestClient.swift
MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/KeySharing/Data/MXOutgoingRoomKeyRequest.h
MatrixSDK/Crypto/KeySharing/Data/MXOutgoingRoomKeyRequest.m
MatrixSDK/Crypto/KeySharing/MXOutgoingRoomKeyRequestManager.h
MatrixSDK/Crypto/KeySharing/MXOutgoingRoomKeyRequestManager.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Crypto/MXCrypto_Private.h
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/Utils/MXTools.h
MatrixSDK/Utils/MXTools.m
MatrixSDKTests/MXSessionTests.m

Port of https://github.com/matrix-org/matrix-js-sdk/pull/448

Send m.room_key_request events when we fail to decrypt an event

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Algorithms/MXDecrypting.h
MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
MatrixSDK/Crypto/KeySharing/Data/MXIncomingRoomKeyRequest.h
MatrixSDK/Crypto/KeySharing/Data/MXIncomingRoomKeyRequest.m
MatrixSDK/Crypto/KeySharing/Data/MXIncomingRoomKeyRequestCancellation.h
MatrixSDK/Crypto/KeySharing/Data/MXIncomingRoomKeyRequestCancellation.m
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m

Port of https://github.com/matrix-org/matrix-js-sdk/pull/449

Crypto: Process received room key requests

---

MatrixSDK/Crypto/Algorithms/MXDecrypting.h
MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
MatrixSDK/Crypto/Data/MXDeviceList.h
MatrixSDK/Crypto/Data/MXDeviceList.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Crypto/MXOlmDevice.h
MatrixSDK/Crypto/MXOlmDevice.m

Port of https://github.com/matrix-org/matrix-js-sdk/pull/454

Crypto: Implement sharing of megolm keys

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Data/MXDeviceInfo.m
MatrixSDK/Crypto/Data/MXDeviceList.h
MatrixSDK/Crypto/Data/MXDeviceList.m
MatrixSDK/Crypto/Data/MXUsersDevicesMap.h
MatrixSDK/Crypto/Data/MXUsersDevicesMap.m
MatrixSDK/Crypto/KeySharing/Data/MXIncomingRoomKeyRequest.h
MatrixSDK/Crypto/KeySharing/Data/MXIncomingRoomKeyRequest.m
MatrixSDK/Crypto/KeySharing/MXIncomingRoomKeyRequestManager.h
MatrixSDK/Crypto/KeySharing/MXIncomingRoomKeyRequestManager.m
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Crypto/MXCrypto_Private.h
MatrixSDK/MXSession.m
MatrixSDKTests/MXCryptoTests.m
MatrixSDKTests/MatrixSDKTestsData.h
MatrixSDKTests/MatrixSDKTestsData.m

This is the equivalent to the existing MXOutgoingRoomKeyRequestManager but for the other side.
Note that js does not have this class. Such management is made outside the sdk, in the react-sdk.

Add MXIncomingRoomKeyRequestManager to manage room key requests

---

MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Crypto/MXOlmDevice.m

The last commit in this PR is bug fixes not related to this new method.

MXCrypto: add deviceWithDeviceId

---

MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/KeySharing/Data/MXIncomingRoomKeyRequest.h
MatrixSDK/Crypto/KeySharing/MXIncomingRoomKeyRequestManager.m
MatrixSDKTests/MXCryptoTests.m

https://github.com/vector-im/riot-meta/issues/121

Crypto: key share: Store permanently incoming room key requests

---

MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/Utils/MXTools.m
MatrixSDKTests/MXCryptoTests.m
MatrixSDKTests/MXSessionTests.m

https://github.com/matrix-org/matrix-js-sdk/pull/483
I still need to upload one-time keys on [MXCrypto start] to make test happy. I will fix it in a coming PR.

Remove new device support

---

MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXSession.m

Port of https://github.com/matrix-org/matrix-js-sdk/pull/493

Crypto: use device_one_time_keys_count transmitted by /sync

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.m

and skip useless executions
We thus use far less bg tasks. M's iphone crashed with groups because we started to use all of available bg task slots.
We also save useless thread switches.

MXFileStore: Run only one background task for [MXFileStore commit]

---

MatrixSDK/MXSession.m

- MXSession: Speed up the process to leave a group.
vector-im/riot-meta#114

Groups: self-management of membership of groups

---

MatrixSDK/Crypto/MXCrypto.m

https://github.com/matrix-org/riot-ios-rageshakes/issues/863

Crypto: Fix crash when we try to generate a negative number of one time keys

---

MatrixSDK/Crypto/Data/MXDeviceList.m

This makes the code more robust if we face the same issue as on Android (https://github.com/vector-im/riot-android/issues/1799).

Crypto: Make sure we request keys for only valid matrix user ids.

---

MatrixSDK/Data/MXRoomMember.m
MatrixSDKTests/MXCryptoTests.m
MatrixSDKTests/MXMyUserTests.m
MatrixSDKTests/MXNotificationCenterTests.m
MatrixSDKTests/MXRestClientNoAuthAPITests.m
MatrixSDKTests/MXRestClientTests.m
MatrixSDKTests/MXRoomStateTests.m
MatrixSDKTests/MXRoomTests.m
MatrixSDKTests/MXStoreTests.m
MatrixSDKTests/MXUserTests.m

Various commits to make tests suite pass again. It may be easier for the reviewer to check commits one by one.

Fix Matrix SDK tests

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.m

Detected by the test checkRoomAccountDataTags

MXFileStore: Make sure data is flushed to files on [MXFileStore close]

---

MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m
MatrixSDK/Utils/MXTools.m

- Add the new event type: `m.sticker`
https://github.com/vector-im/riot-ios/issues/1819

Render sticker events in the timeline

---

MatrixSDK/MXSession.m

https://github.com/vector-im/riot-ios/issues/1839

Bug Fix - App fails to logout on unknown token

---

MatrixSDK.podspec
Podfile
SwiftMatrixSDK.podspec

Pod: Update realm version

---

MatrixSDK/Utils/Media/MXMediaManager.m

https://github.com/vector-im/riot-ios/issues/1673

Bug Fix - All rooms showing the same avatar

---

MatrixSDK/Utils/Media/MXMediaManager.m

https://github.com/matrix-org/riot-ios-rageshakes/issues/1123

Bug Fix - Sending a photo from the photo library causes a crash

---

MatrixSDK/Data/MXAccountData.h
MatrixSDK/Data/MXAccountData.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

Required for https://github.com/vector-im/riot-ios/issues/1860

MXSession: Make MXAccountData member public

---

MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

https://github.com/vector-im/riot-ios/issues/1860
and create a const for "m.widgets" account data

MXSession: add setAccountData

---

MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/MXRestClient.h
MatrixSDK/Utils/MXBugReportRestClient.m
MatrixSDK/Utils/MXTools.h
MatrixSDK/VoIP/MXCall.m
MatrixSDK/VoIP/MXCallManager.m

I have introduced `MXWeakify` & `MXStrongifyAndReturnIfNil` to make weakSelf management easier.
Part of https://github.com/vector-im/riot-ios/issues/1859
TBC...

Kill warnings

---

MatrixSDK/Contrib/Swift/MXRestClient.swift
MatrixSDK/Contrib/Swift/MXSession.swift
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

https://github.com/vector-im/riot-ios/issues/1870
Add account deactivation API.

Add deactivate account

---

MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m

The issue has been detected while reading the code.
Do the same thing as android and web do.

MXMegolmDecryption: Fix unused overridden var

---

MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/KeySharing/MXIncomingRoomKeyRequestManager.m
MatrixSDK/Crypto/KeySharing/MXOutgoingRoomKeyRequestManager.m
MatrixSDK/Data/MXEventTimeline.m
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.m
MatrixSDK/Utils/MXBugReportRestClient.m
MatrixSDK/Utils/MXHTTPClient.m
MatrixSDK/VoIP/MXCallManager.m

by `MXWeakify / MXStrongifyAndReturnIfNil`.
And get the logging power of `MXStrongifyAndReturnIfNil`.

Replace all current `__weak typeof(self) weakSelf = self;...` dances

---

MatrixSDK/Data/MXRoomSummary.m

The introduction of `CFRelease` in PR #511 has allowed to see the problem.

MXRoomSummary: Fix a crash introduced by CFRelease

---

CHANGES.rst
MatrixSDK/Data/MXEventTimeline.m
MatrixSDK/Data/MXRoom.m

MXRoom: A message (or a media) can be sent whereas the user cancelled it

---

MatrixSDK/Data/MXRoom.m

Add JSON validation and, eventually, improve fast enumeration on dictionaries

MXRoom: modernise handleReceiptEvent

---

MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m

For parity and to fix a race condition (crash at https://github.com/matrix-org/riot-ios-rageshakes/issues/1312)

MXMemoryStore: Make `getEventReceipts` thread safe as `storeReceipt` is

---

CHANGES.rst
MatrixSDK/MXEnumConstants.h
MatrixSDK/MXEnumConstants.m
MatrixSDK/Utils/MXAnalyticsDelegate.h
MatrixSDKExtensions/MXAnalyticsDelegate/GoogleAnalytics/MXGoogleAnalytics.m

as we are not more tied to a single implementation with GA.

Analytics: Rename all kMXGoogleAnalyticsXxx constant values to kMXAnalyticsXxx

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/Filters/MXFilterJSONModel.h
MatrixSDK/Data/Filters/MXFilterJSONModel.m
MatrixSDK/Data/Filters/MXFilterObject.h
MatrixSDK/Data/Filters/MXFilterObject.m
MatrixSDK/Data/Filters/MXRoomFilter.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDKTests/MXRestClientTests.m

Required for https://github.com/vector-im/riot-ios/issues/1931

 MXRestClient: Add Matrix filter API

---

MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Crypto/MXCrypto_Private.h
MatrixSDK/Data/MXEventTimeline.h
MatrixSDK/Data/MXEventTimeline.m
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/MXRoomMembers.h
MatrixSDK/Data/MXRoomMembers.m
MatrixSDK/Data/MXRoomState.h
MatrixSDK/Data/MXRoomState.m
MatrixSDK/Data/MXRoomSummary.m
MatrixSDK/MXSession.m
MatrixSDK/NotificationCenter/Checker/MXPushRuleRoomMemberCountConditionChecker.m

Decouple even more.
vector-im/riot-ios#1931

MXRoomState: Decouple room members from room state #2

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Data/MXEventTimeline.m
MatrixSDK/Data/MXPeekingRoom.m
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/MXRoomMembersCount.h
MatrixSDK/Data/MXRoomMembersCount.m
MatrixSDK/Data/MXRoomState.h
MatrixSDK/Data/MXRoomState.m
MatrixSDK/Data/MXRoomSummary.h
MatrixSDK/Data/MXRoomSummary.m
MatrixSDK/Data/MXRoomSummaryUpdater.m
MatrixSDK/Data/MXSessionEventListener.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXStore.h
MatrixSDK/MXSession.m
MatrixSDK/NotificationCenter/Checker/MXPushRuleRoomMemberCountConditionChecker.m
MatrixSDK/VoIP/MXCall.m
MatrixSDK/VoIP/MXCallManager.m
MatrixSDKTests/MXPeekingRoomTests.m
MatrixSDKTests/MXRoomStateDynamicTests.m
MatrixSDKTests/MXRoomStateTests.m
MatrixSDKTests/MXRoomSummaryTests.m
MatrixSDKTests/MXRoomTests.m
MatrixSDKTests/MXSessionTests.m
MatrixSDKTests/MXStoreTests.m

Its access is going to be async.
https://github.com/vector-im/riot-ios/issues/1931

Reduce dependency to room.state

---

CHANGES.rst
MatrixSDK/Contrib/Swift/MXSession.swift
MatrixSDK/Data/Filters/MXFilterJSONModel.h
MatrixSDK/Data/Filters/MXFilterJSONModel.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.h
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXFileStore/MXFileStoreMetaData.h
MatrixSDK/Data/Store/MXFileStore/MXFileStoreMetaData.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.h
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
MatrixSDK/Data/Store/MXStore.h
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m
MatrixSDKTests/MXFilterTests.m
MatrixSDKTests/MXRoomSummaryTests.m
MatrixSDKTests/MXRoomTests.m
MatrixSDKTests/MXSessionTests.m
MatrixSDKTests/MXStoreTests.m

and add all mechanics to manage Matrix filters.
Part of https://github.com/vector-im/riot-ios/issues/1931.

MXSession: Create [MXSession startWithSyncFilter:]

---

CHANGES.rst
MatrixSDK/MXError.h
MatrixSDK/MXError.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/Utils/MXHTTPClient.m

Point 1 of https://github.com/vector-im/riot-ios/issues/1937

Show a "Resource Limit Exceeded" popup

---

CHANGES.rst
MatrixSDK.podspec
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/MXPeekingRoom.m
MatrixSDK/Data/MXPeekingRoomSummary.h
MatrixSDK/Data/MXPeekingRoomSummary.m
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/MXRoomSummary.h
MatrixSDK/Data/MXRoomSummary.m
MatrixSDKTests/MXLazyLoadingTests.m
MatrixSDKTests/MXPeekingRoomTests.m
Podfile
Podfile.lock
SwiftMatrixSDK.podspec

specially a fix for https://github.com/vector-im/riot-ios/issues/2035

Some improvements for LL 

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/MXRoomNameDefaultStringLocalizations.h
MatrixSDK/Data/MXRoomNameDefaultStringLocalizations.m
MatrixSDK/Data/MXRoomNameStringsLocalizable.h
MatrixSDK/Data/MXRoomSummaryUpdater.h
MatrixSDK/Data/MXRoomSummaryUpdater.m

for rooms with no name
https://github.com/vector-im/riot-ios/issues/1931

Matrix room summaries: internationalise the room name computation

---

CHANGES.rst
MatrixSDK/Utils/MXTools.m

vector-im/riot-ios/issues/1977

MXTools: Allow '@' in room alias

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/MXRoomState.h
MatrixSDK/Data/MXRoomState.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/JSONModels/MXServerNoticeContent.h
MatrixSDK/JSONModels/MXServerNoticeContent.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m
MatrixSDK/MatrixSDK.h
MatrixSDK/Utils/MXServerNotices.h
MatrixSDK/Utils/MXServerNotices.m
MatrixSDK/Utils/MXTools.m

https://github.com/vector-im/riot-ios/issues/1937

Add MXServerNotices to get message warnings from the homeserver

---

CHANGES.rst
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Data/MXRoomMembers.h
MatrixSDK/Data/MXRoomMembers.m
MatrixSDKTests/MXCryptoTests.m
MatrixSDKTests/MXRoomMemberTests.m
MatrixSDKTests/MatrixSDKTestsE2EData.h
MatrixSDKTests/MatrixSDKTestsE2EData.m

Encrypt for invited users if history visibility allows

---

CHANGES.rst
MatrixSDK/Data/MXRoom.m

Fixes vector-im/riot-ios/issues/2086

BF: Reply of reply with unexpected newlines renders badly

---

MatrixSDK/MXRestClient.m

Signed-off-by: Anton Sydorov <anton.sydorov@gmail.com>

Fix avatarUrlForUser:success:failure: method

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/JSONModels/Authentication/MXLoginPolicy.h
MatrixSDK/JSONModels/Authentication/MXLoginPolicy.m
MatrixSDK/JSONModels/Authentication/MXLoginPolicyData.h
MatrixSDK/JSONModels/Authentication/MXLoginPolicyData.m
MatrixSDK/JSONModels/Authentication/MXLoginTerms.h
MatrixSDK/JSONModels/Authentication/MXLoginTerms.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m

https://github.com/vector-im/riot-ios/issues/1939
As specified by https://github.com/matrix-org/matrix-doc/blob/travis/msc/terms-api/proposals/1692-terms-api.md

MXJSONModels: Add data models for Terms of service / privacy policy API

---

MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m

to avoid crash if we cannot decrypt a session because of a wrong recovery key

Keys backup: Add sanity check

---

CHANGES.rst
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m

That should fix some crashes reported by the app store

MXRealmCryptoStore: Make queries inside transactionWithBlock.

---

CHANGES.rst
MatrixSDK/ContentScan/Data/MXContentScanEncryptedBody.h
MatrixSDK/ContentScan/Data/MXContentScanEncryptedBody.m
MatrixSDK/ContentScan/MXScanManager.h
MatrixSDK/ContentScan/MXScanManager.m
MatrixSDK/MXSession.m
MatrixSDK/Utils/Media/MXMediaManager.h
MatrixSDK/Utils/Media/MXMediaManager.m

 MXScanManager/MXMediaManager: Support the encrypted body.

---

CHANGES.rst
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m

Fixes vector-im/riot-ios/issues/2132.

MXCryptoStore: Stop duplicating devices in the store

---

MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m

MXRealmCryptoStore: Fix crash in migration

---

CHANGES.rst
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m

Fixes https://github.com/vector-im/riot-ios/issues/2167.

Crypto: Device deduplication method sometimes crashes

---

CHANGES.rst
MatrixSDK/Crypto/KeyBackup/Data/MXKeyBackupVersionTrust.h
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
MatrixSDKTests/MXCryptoBackupTests.m

To let the app manage this case.

Key backup: Add MXKeyBackupStateNotTrusted state

---

CHANGES.rst
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
MatrixSDK/Crypto/KeyBackup/MXKeyBackup_Private.h
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m

in order to make easier the state change follow-up - to implement https://github.com/vector-im/riot-ios/issues/2193 and app banners.
Read each commit message for details.

MXKeyBackup: Improvements

---

CHANGES.rst
MatrixSDK/MXSession.m

Handle correctly a new invite to a direct chat that the user has left

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
MatrixSDK/Crypto/MXOlmDevice.m
MatrixSDK/Crypto/Utils/MXCryptoTools.h
MatrixSDK/Crypto/Utils/MXCryptoTools.m
MatrixSDKTests/MXCryptoBackupTests.m

Fixes vector-im/riot-ios/issues/#2232 plus other bugs found while testing the feature.

Crypto: Cancel share request on restore/import

---

CHANGES.rst
MatrixSDK/Crypto/Data/MXCryptoConstants.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/KeyBackup/Data/MXKeyBackupVersion.h
MatrixSDK/Crypto/KeyBackup/Data/MXKeyBackupVersion.m
MatrixSDK/Crypto/KeyBackup/Data/MXMegolmBackupAuthData.h
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDKTests/MXCryptoBackupTests.m

vector-im/riot-ios#2223 
Declare backup trust using new `PUT /room_keys/version/{version}` API

Key backup: Trust on decrypt

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/AutoDiscovery/MXAutoDiscovery.h
MatrixSDK/Data/AutoDiscovery/MXAutoDiscovery.m
MatrixSDK/Data/AutoDiscovery/MXDiscoveredClientConfig.h
MatrixSDK/Data/AutoDiscovery/MXDiscoveredClientConfig.m
MatrixSDK/JSONModels/AutoDiscovery/MXWellKnown.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/MatrixSDK.h
MatrixSDK/Utils/MXHTTPClient.h
MatrixSDK/Utils/MXHTTPClient.m
MatrixSDK/Utils/MXHTTPOperation.h
MatrixSDK/Utils/MXHTTPOperation.m
MatrixSDKTests/MXAutoDiscoveryTests.m
Podfile
Podfile.lock

Part of vector-im/riot-ios/issues/2117.
Doc: https://matrix.org/docs/spec/client_server/latest.html#server-discovery
Translated from https://github.com/matrix-org/matrix-android-sdk/pull/436.

Add .well-known support 

---

CHANGES.rst
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

MXSession: add a global notification posted when the account data are updated from the homeserver

---

MatrixSDK/MXSession.m

Signed-off-by: Anton Sydorov anton.sydorov@gmail.com

Fix issue #646: MXFileStore not loaded with 0 rooms

---

CHANGES.rst
MatrixSDK/Utils/MXHTTPClient.h
MatrixSDK/Utils/MXHTTPClient.m

MXHTTPClient: support multiple SSL pinning modes (none/public key/certificate)

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Aggregations/Data/MXAggregatedReactions.h
MatrixSDK/Aggregations/Data/MXAggregatedReactions.m
MatrixSDK/Aggregations/MXAggregations.h
MatrixSDK/Aggregations/MXAggregations.m
MatrixSDKTests/MXReactionTests.m

Aggregations: Introduce MXAggregatedReactions data model

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Aggregations/Data/MXReactionRelation.h
MatrixSDK/Aggregations/Data/MXReactionRelation.m
MatrixSDK/Aggregations/Data/Store/MXAggregationsStore.h
MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsMapper.h
MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsMapper.m
MatrixSDK/Aggregations/Data/Store/Realm/MXRealmAggregationsStore.m
MatrixSDK/Aggregations/Data/Store/Realm/MXRealmReactionRelation.h
MatrixSDK/Aggregations/Data/Store/Realm/MXRealmReactionRelation.m
MatrixSDK/Aggregations/MXAggregations.h
MatrixSDK/Aggregations/MXAggregations.m
MatrixSDKTests/MXReactionTests.m

https://github.com/vector-im/riot-ios/issues/2398

Aggregations: Support unreaction

---

CHANGES.rst
MatrixSDK/MXError.h
MatrixSDK/MXError.m

Add the Matrix errors related to the password policy

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Aggregations/Data/MXEventEditsListener.h
MatrixSDK/Aggregations/Data/MXEventEditsListener.m
MatrixSDK/Aggregations/MXAggregatedEditsUpdater.h
MatrixSDK/Aggregations/MXAggregatedEditsUpdater.m
MatrixSDK/Aggregations/MXAggregations.h
MatrixSDK/Aggregations/MXAggregations.m
MatrixSDK/JSONModels/Event/MXEventRelations.h
MatrixSDK/JSONModels/Event/MXEventRelations.m
MatrixSDK/JSONModels/Event/MXEventReplace.h
MatrixSDK/JSONModels/Event/MXEventReplace.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDKTests/MXAggregatedEditsTests.m
MatrixSDKTests/MXAggregatedReactionTests.m

vector-im/riot-ios/issues/2450

Message Editing: Handle clear text message edition

---

MatrixSDK/Aggregations/MXAggregations.h
MatrixSDK/Aggregations/MXAggregations.m
MatrixSDK/JSONModels/MXEvent.m
MatrixSDKTests/MXAggregatedEditsTests.m

vector-im/riot-ios/issues/2404

Message Editing: Support formatted text

---

MatrixSDK/Aggregations/MXAggregatedReactionsUpdater.m

for phase:1.
This will be reenabled when synapse will fully support aggregation API.

Reactions: Use only the "hack" to send reactions

---

CHANGES.rst
MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction.m

vector-im/riot-ios/issues/2526

Crypto: Device Verification: Name for 🔒 is "Lock"

---

CHANGES.rst
MatrixSDK/VoIP/MXCall.m
MatrixSDK/VoIP/MXCallManager.m
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m

Fixes vector-im/riot-ios/issues/2532.

VoIP: Stop falling back to Google for STUN

---

MatrixSDK/Aggregations/MXAggregatedEditsUpdater.m

Handle vector-im/riot-ios/issues/2512

Message Editing: Support emote edition

---

MatrixSDK/Aggregations/MXAggregations.h
MatrixSDK/Aggregations/MXAggregations.m
MatrixSDK/JSONModels/Aggregations/MXAggregationPaginatedResponse.h
MatrixSDK/JSONModels/Aggregations/MXAggregationPaginatedResponse.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDKTests/MXAggregatedEditsTests.m

part of https://github.com/vector-im/riot-ios/issues/2401
There was some changes in the existing code after testing against the server.

 Edits history: Expose the API in MXAggregation

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Aggregations/MXAggregatedEditsUpdater.m
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/ReplyEvent/Parser/MXReplyEventBodyParts.h
MatrixSDK/Data/ReplyEvent/Parser/MXReplyEventBodyParts.m
MatrixSDK/Data/ReplyEvent/Parser/MXReplyEventFormattedBodyParts.h
MatrixSDK/Data/ReplyEvent/Parser/MXReplyEventFormattedBodyParts.m
MatrixSDK/Data/ReplyEvent/Parser/MXReplyEventParser.h
MatrixSDK/Data/ReplyEvent/Parser/MXReplyEventParser.m
MatrixSDK/Data/ReplyEvent/Parser/MXReplyEventParts.h
MatrixSDK/Data/ReplyEvent/Parser/MXReplyEventParts.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/MatrixSDK.h
MatrixSDKTests/MXReplyEventParserTests.m

vector-im/riot-ios/issues/2492

Message Editing: Handle reply edition

---

MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmEncryption.m
MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
MatrixSDK/Crypto/Data/MXDeviceList.m
MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.m
MatrixSDK/Crypto/Data/MXEncryptedAttachments.m
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Crypto/MXOlmDevice.m
MatrixSDK/Data/MXRoom.m

Add some missing logs. Add some missing log tag.
Make a NSLog usable on a single line when we filter logs based on tags
Then, we can extract useful information about crypto from our verbose console.log files:

MXCrypto: Improve logging

---

CHANGES.rst
MatrixSDK/Data/MXRoomSummary.m
MatrixSDK/Data/MXRoomSummaryUpdater.m
MatrixSDKTests/MXAggregatedEditsTests.m

Closes vector-im/riot-ios/issues/2583

MXRoomSummary: Manage edits

---

CHANGES.rst
MatrixSDK/MXError.h
MatrixSDK/MXError.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m
MatrixSDK/Utils/MXHTTPClient.m
MatrixSDKTests/MXHTTPClientTests.m

Closes vector-im/riot-ios/issues/2584.

 Soft logout: Handle new CS API error code

---

CHANGES.rst
MatrixSDK/Crypto/Data/MXDeviceList.m
MatrixSDK/Crypto/Data/MXDeviceListOperation.m
MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.m
MatrixSDK/Data/MXRoom.m
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDKTests/MXCryptoTests.m

Closes vector-im/riot-ios/issues/2541
The full description of the race is given at https://github.com/vector-im/riot-ios/issues/2541#issuecomment-513848365.
This PR also :
-  adds more logs for tracking device keys download
- fixes a crash
- makes logs a bit less verbose

 Crypto: Fix a race condition that prevented message from being sent

---

CHANGES.rst
MatrixSDK/Aggregations/MXAggregations.h
MatrixSDK/Aggregations/MXAggregations.m

vector-im/riot-ios/issues/2591

Aggregations: Expose reaction history API

---

CHANGES.rst
MatrixSDK/Utils/MXHTTPClient.m

Do not wait to try again if the mentioned delay is too long.

MXHTTPClient: Improve M_LIMIT_EXCEEDED error handling

---

CHANGES.rst
MatrixSDK/IdentityServer/MXIdentityServerRestClient.h
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m

https://github.com/vector-im/riot-ios/issues/2665
MSC: https://github.com/matrix-org/matrix-doc/pull/2230

Privacy: Store Identity Server in Account Data (MSC2230)

---

MatrixSDK/Contrib/Swift/MXIdentityService.swift
MatrixSDK/Contrib/Swift/MXRestClient.swift
MatrixSDK/IdentityServer/MXIdentityService.h
MatrixSDK/NotificationCenter/ServiceTerms/MXServiceTerms.h
MatrixSDK/NotificationCenter/ServiceTerms/MXServiceTerms.m

Small updates and fixes for https://github.com/vector-im/riot-ios/issues/2604.

Small updates to make IS settings work

---

CHANGES.rst
MatrixSDK/Data/MXEventTimeline.m

Bug Fix: Room members who left are listed with the actual members #2737

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Aggregations/MXAggregatedReferencesUpdater.h
MatrixSDK/Aggregations/MXAggregatedReferencesUpdater.m
MatrixSDK/Aggregations/MXAggregations.h
MatrixSDK/Aggregations/MXAggregations.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/JSONModels/Event/MXEventReference.h
MatrixSDK/JSONModels/Event/MXEventReference.m
MatrixSDK/JSONModels/Event/MXEventReferenceChunk.h
MatrixSDK/JSONModels/Event/MXEventReferenceChunk.m
MatrixSDK/JSONModels/Event/MXEventRelations.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/MatrixSDK.h
MatrixSDKTests/MXAggregatedReferenceTests.m
MatrixSDKTests/MXEventReferenceTests.swift

as per [MSC1849](https://github.com/matrix-org/matrix-doc/blob/matthew/msc1849/proposals/1849-aggregations.md).

Aggregations: Implement m.reference aggregations, aka thread

---

MatrixSDK/Crypto/Verification/MXDeviceVericationManager.m
MatrixSDK/Crypto/Verification/MXDeviceVerificationManager.h
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m
MatrixSDKTests/MXCryptoDeviceVerificationTests.m
README.rst

Closes https://github.com/vector-im/riot-ios/issues/2954

Verification in DM: Create the DM if it does not exist

---

MatrixSDK/Crypto/Data/Trust/MXUsersTrustLevelSummary.h
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m

Commits can be read separately.
Fixes https://github.com/vector-im/riot-ios/issues/2957
Fixes https://github.com/vector-im/riot-ios/issues/2956

Fix shields

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Data/Trust/MXUsersTrustLevelSummary.h
MatrixSDK/Crypto/Data/Trust/MXUsersTrustLevelSummary.m
MatrixSDK/Data/MXRoomSummary.h
MatrixSDK/Data/MXRoomSummary.m
MatrixSDK/MXSDKOptions.h
MatrixSDKTests/MXCryptoDeviceVerificationTests.m
MatrixSDKTests/MXRoomSummaryTrustTests.m

and devices in the room
SDK part of vector-im/riot-ios/issues/2906

MXRoomSummary: Add the trust property to indicate trust in other users 

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Verification/JSONModels/MXKeyVerificationReady.h
MatrixSDK/Crypto/Verification/JSONModels/MXKeyVerificationReady.m
MatrixSDK/Crypto/Verification/MXKeyVerificationManager.h
MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
MatrixSDK/Crypto/Verification/MXKeyVerificationManager_Private.h
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationByDMRequest.h
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationByDMRequest.m
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest.h
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest.m
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest_Private.h
MatrixSDK/Crypto/Verification/Status/MXKeyVerificationStatusResolver.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/Utils/MXTools.m
MatrixSDKTests/MXCrossSigningVerificationTests.m
MatrixSDKTests/MXCryptoKeyVerificationTests.m

[MSC2366](https://github.com/uhoreg/matrix-doc/blob/key_verification_accept/proposals/2366-key-verification-accept.md)
Closes https://github.com/vector-im/riot-ios/issues/2870.

Key Verification: "m.key.verification.ready" support

---

MatrixSDK/Crypto/MXCrypto.m

This PR contains 3 bug fixes described in each commit.

Olm unwedging fix

---

.gitignore
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Verification/JSONModels/MXKeyVerificationRequestByDMJSONModel.h
MatrixSDK/Crypto/Verification/JSONModels/MXKeyVerificationRequestByDMJSONModel.m
MatrixSDK/Crypto/Verification/JSONModels/MXKeyVerificationRequestByToDeviceJSONModel.h
MatrixSDK/Crypto/Verification/JSONModels/MXKeyVerificationRequestByToDeviceJSONModel.m
MatrixSDK/Crypto/Verification/MXKeyVerificationManager.h
MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
MatrixSDK/Crypto/Verification/MXKeyVerificationManager_Private.h
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationByDMRequest.h
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationByDMRequest.m
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationByToDeviceRequest.h
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationByToDeviceRequest.m
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest.h
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest.m
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest_Private.h
MatrixSDK/Crypto/Verification/Status/MXKeyVerificationStatusResolver.h
MatrixSDK/Crypto/Verification/Status/MXKeyVerificationStatusResolver.m
MatrixSDK/Crypto/Verification/Transactions/MXKeyVerificationTransaction.h
MatrixSDK/Crypto/Verification/Transactions/MXKeyVerificationTransaction.m
MatrixSDK/Crypto/Verification/Transactions/MXKeyVerificationTransaction_Private.h
MatrixSDK/Crypto/Verification/Transactions/SAS/MXOutgoingSASTransaction.m
MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransaction.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/Utils/MXTools.m
MatrixSDKTests/MXCrossSigningVerificationTests.m
MatrixSDKTests/MXCryptoKeyVerificationTests.m

Part of https://github.com/vector-im/riot-ios/issues/2871

Key Verification: Request by to_device events

---

MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Utils/MXTools.h
MatrixSDK/Utils/MXTools.m

This only affects XCode targets for unit testing, not release build.

MXRealmCryptoStore: Support running a user with several devices in unit tests

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/KeySharing/Secret/Data/MXPendingSecretShareRequest.h
MatrixSDK/Crypto/KeySharing/Secret/Data/MXPendingSecretShareRequest.m
MatrixSDK/Crypto/KeySharing/Secret/JSONModels/MXSecretShareRequest.h
MatrixSDK/Crypto/KeySharing/Secret/JSONModels/MXSecretShareRequest.m
MatrixSDK/Crypto/KeySharing/Secret/JSONModels/MXSecretShareSend.h
MatrixSDK/Crypto/KeySharing/Secret/JSONModels/MXSecretShareSend.m
MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.h
MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.m
MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager_Private.h
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/Utils/MXTools.m
MatrixSDKTests/MXCryptoSecretShareTests.m
MatrixSDKTests/MatrixSDKTestsE2EData.h
MatrixSDKTests/MatrixSDKTestsE2EData.m

Part of https://github.com/vector-im/riot-ios/issues/3000.
Implement https://github.com/uhoreg/matrix-doc/blob/ssss/proposals/1946-secure_server-side_storage.md#sharing.

Secret Sharing

---

MatrixSDK/Crypto/CrossSigning/MXCrossSigning.h
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/Crypto/CrossSigning/MXCrossSigning_Private.h
MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.h
MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDKTests/MXCrossSigningTests.m
MatrixSDKTests/MXCrossSigningVerificationTests.m

https://github.com/vector-im/riot-ios/issues/3024
MSK, USK & SSK are now stored in the crypto store and we can gossip them.

Cross-Signing: Get USK and SSK from gossiping

---

CHANGES.rst
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/Crypto/Data/MXDeviceList.m
MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.h
MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.m
MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequest.m
MatrixSDKTests/MXCryptoKeyVerificationTests.m

Fix https://github.com/vector-im/riot-ios/issues/3040
The 2 first commits fix other bugs I discovered while debugging this bug.

BF: Self verification is broken 

---

CHANGES.rst
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDKTests/MXCrossSigningTests.m

Fix https://github.com/vector-im/riot-ios/issues/3044 by checking existing cross-signing before trusting it

BF: A new signin can trust existing cross-signing without any verification

---

CHANGES.rst
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/Crypto/CrossSigning/MXCrossSigning_Private.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDKTests/MXCrossSigningTests.m

Made on top of https://github.com/matrix-org/matrix-ios-sdk/pull/800 that must be merged before.
Final fix https://github.com/vector-im/riot-ios/issues/3024

Cross-signing: Make automatic gossip request

---

MatrixSDK/Crypto/CrossSigning/Data/MXCrossSigningInfo.h
MatrixSDK/Crypto/CrossSigning/Data/MXCrossSigningInfo.m
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDKTests/MXCrossSigningTests.m

Part of  https://github.com/vector-im/riot-ios/issues/3043

Cross-signing: Reset all trust we had on cross-signing reset detection

---

MatrixSDK/Crypto/CrossSigning/MXCrossSigning.h
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/Crypto/Data/MXDeviceInfo.m
MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDKTests/MXCrossSigningTests.m
MatrixSDKTests/MXCryptoTests.m

Fix https://github.com/vector-im/riot-ios/issues/3058

Cross-signing: Fix New-signin detection that popped up too much

---

MatrixSDK/Crypto/Data/MXCryptoConstants.h
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
MatrixSDK/Crypto/KeyBackup/MXKeyBackup_Private.h
MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.h
MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.m
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Data/MXRoom.m
MatrixSDKTests/MXCryptoBackupTests.m

Part of https://github.com/vector-im/riot-ios/issues/3053

Request the key backup private key

---

MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m

but only on verification event types. This saves thread context switches and logs

KeyVerification: Do not react on every to_device events

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Algorithms/Megolm/MXMegolmDecryption.m
MatrixSDK/Crypto/KeySharing/MXOutgoingRoomKeyRequestManager.m
MatrixSDK/Crypto/MXOlmDevice.m
MatrixSDK/MatrixSDK.h
MatrixSDK/Utils/MXThrottler.h
MatrixSDK/Utils/MXThrottler.m

Sorry for this PR with various things in it.
Commits can be reviewed one by one.
Part of the work for https://github.com/vector-im/riot-ios/issues/3105.

Crypto: Improve logs, small improvement and add  MXThrottler

---

MatrixSDK/Data/MXRoomSummary.h
MatrixSDK/Data/MXRoomSummary.m
MatrixSDKTests/MXCrossSigningTests.m
MatrixSDKTests/MXRoomSummaryTrustTests.m
MatrixSDKTests/MatrixSDKTestsE2EData.h
MatrixSDKTests/MatrixSDKTestsE2EData.m

Fixes https://github.com/vector-im/riot-ios/issues/3104
The fix is actually in the last commit.

BF: Room badge does not update when the other user self-signed a device

---

CHANGES.rst
MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.m
MatrixSDK/Utils/MXHTTPClient.m

Fixes vector-im/riot-ios/issues/3123

Fix race condition in MXSecretShareManager

---

CHANGES.rst
MatrixSDK/IdentityServer/MXIdentityServerRestClient.m

MXIdentityService: Fix registration by email and all IS services 

---

CHANGES.rst
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/Crypto/CrossSigning/MXCrossSigning_Private.h
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
MatrixSDK/Crypto/KeyBackup/MXKeyBackup_Private.h
MatrixSDK/Crypto/MXCrypto.h
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m

Fix vector-im/riot-ios/issues/3163
Commits can be reviewed separately.

Cross-signing: Make key gossip requests when the other device sent m.key.verification.done

---

CHANGES.rst
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.h
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
MatrixSDK/Crypto/KeySharing/Secret/Data/MXPendingSecretShareRequest.h
MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.h
MatrixSDK/Crypto/KeySharing/Secret/MXSecretShareManager.m
MatrixSDKTests/MXCryptoSecretShareTests.m

fix vector-im/riot-ios/issues/3201.

Secrets: Validate received private keys for cross-signing and key backup before using them

---

CHANGES.rst
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.h
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m

Part of https://github.com/vector-im/riot-ios/issues/3292

MXCrossSigning: Add the bootstrapWithAuthParams method

---

CHANGES.rst
MatrixSDK/Data/MXRoomState.m
MatrixSDK/Data/MXRoomSummaryUpdater.m
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/Utils/Categories/NSArray+MatrixSDK.h
MatrixSDK/Utils/Categories/NSArray+MatrixSDK.m
MatrixSDKTests/MXSessionTests.m
MatrixSDKTests/MatrixSDKTestsData.m

Fix https://github.com/vector-im/riot-ios/issues/3300

Remove `roomAlias` from `MXCreateRoomResponse`

---

CHANGES.rst
MatrixSDK/Crypto/Data/MXDeviceList.m

Fix https://github.com/vector-im/riot-ios/issues/3118

Fix Crash in MXDeviceList

---

CHANGES.rst
MatrixSDK/NotificationCenter/Checker/MXPushRuleRoomMemberCountConditionChecker.m
MatrixSDK/NotificationCenter/Checker/MXPushRuleSenderNotificationPermissionConditionChecker.m

Fix https://github.com/vector-im/riot-ios/issues/3354

Remove Redundant `room` Checks from Some Checkers

---

CHANGES.rst
MatrixSDK/JSONModels/AutoDiscovery/MXWellKnown.m
MatrixSDKTests/MXAutoDiscoveryTests.m

MXWellKnown: Add JSONDictionary implementation to return original

---

CHANGES.rst
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.h
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/MXRestClient.h
MatrixSDKTests/MXCrossSigningTests.m
MatrixSDKTests/MXCrossSigningVerificationTests.m
MatrixSDKTests/MXCryptoRecoveryServiceTests.m
MatrixSDKTests/MXRoomSummaryTrustTests.m
MatrixSDKTests/MatrixSDKTestsE2EData.m

MXRestClient: Add authSessionForRequestWithMethod to get an auth session for any requests

---

CHANGES.rst

Reset the changelog for the next version

Reset Changelog for new version

---

CHANGES.rst

Fix the release that failed because I was hacking the script

Prepare for new sprint

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/PushGateway/MXPushGatewayRestClient.h
MatrixSDK/PushGateway/MXPushGatewayRestClient.m
MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m
MatrixSDK/VoIP/MXCall.m

SDK part of vector-im/element-ios#3452

Introduce `MXPushGatewayRestClient`

---

fastlane/Fastfile

Add SonarCloud fastlane target

---

CHANGES.rst
MatrixSDK/VoIP/MXCallManager.h
MatrixSDK/VoIP/MXCallManager.m

Part of vector-im/element-ios#3452

Introduce `handleCallEvent` on `MXCallManager`

---

CHANGES.rst
MatrixSDK/Data/MXCredentials.m

Fixes vector-im/element-ios#3448

Try to guess HS when not provided in wellknown

---

CHANGES.rst
MatrixSDK/JSONModels/Push/MXPusherData.m

vector-im/riot-ios/issues/3577

MXPushData: Implement JSONDictionary

---

CHANGES.rst
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.h
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/Crypto/Data/MXDeviceListOperationsPool.m
MatrixSDK/Crypto/Data/Trust/MXUserTrustLevel.m
MatrixSDKTests/MXCrossSigningTests.m
MatrixSDKTests/MXCryptoTests.m

and send MXCrossSigningDidChangeCrossSigningKeysNotification

MXCrossSigning: Detect when cross-signing keys have been reset 

---

CHANGES.rst
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/MXSession.m
MatrixSDK/Utils/MXAnalyticsDelegate.h

so that we will be able to add more things to track without changing the protocol and the implementation.

MXAnalyticsDelegate: Make it fully agnostic on tracked data

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Utils/MXAes.h
MatrixSDK/Crypto/Utils/MXAes.m
MatrixSDK/Crypto/Utils/MXAesHmacSha2.m
MatrixSDK/MatrixSDK.h
MatrixSDKTests/MXAesTests.m

Part of issue https://github.com/vector-im/element-ios/issues/3833

Add AES encryption helper class

---

CHANGES.rst
MatrixSDK/MXEnumConstants.h
MatrixSDK/MXEnumConstants.m
MatrixSDK/VoIP/MXCall.m

Fix vector-im/element-ios#3855
Inspired from https://github.com/matrix-org/matrix-react-sdk/pull/5340.

Voip Analytics

---

CHANGES.rst
MatrixSDK/Background/MXBackgroundSyncService.swift

Fix vector-im/element-ios#3889

MXBackgroundSyncService: Fix `m.buddy` to-device Event Crashes

---

CHANGES.rst
MatrixSDK/VoIP/CallStack/MXCallStackCall.h
MatrixSDK/VoIP/MXCall.h
MatrixSDK/VoIP/MXCall.m
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m

Part of vector-im/element-ios#3929

VoIP: DTMF Support

---

CHANGES.rst
MatrixSDK/Background/MXBackgroundCryptoStore.m
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m

This PR offers 2 improvements on realm DB compaction. The 2 commits can be reviewed separately.

Improve realm DB compaction

---

CHANGES.rst
MatrixSDK/Utils/MXLogger.h
MatrixSDK/Utils/MXLogger.m

Part of vector-im/element-ios/issues/#3903.
This PR contains 2 improvements. Commits can be reviewed separately.

MXLogger: Reduce log size

---

CHANGES.rst
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStack.m

Fix vector-im/element-ios#4026

VoIP: Add VP8/VP9 Codec Support

---

CHANGES.rst
MatrixSDK/VoIP/MXCall.m

Fix vector-im/element-ios#4030

VoIP: Handle call rejects from other devices

---

CHANGES.rst
MatrixSDK/VoIP/MXCallManager.m

Fix vector-im/element-ios#4031

VoIP: Fix calls from my own users

---

CHANGES.rst
README.rst

Fixes a couple of typos (<del>you</del> your), adds a period where it improves consistency, and fixes an instance of incorrect capitalization (<del>cocoapods</del> CocoaPods)
Signed-off by: Chris Hanson chha1083@colorado.edu

README: Fix a couple of typos and improve consistency

---

MatrixSDK/VoIP/MXCall.m

Fix vector-im/element-ios#4028

VoIP: Handle Offer After User Answer

---

CHANGES.rst
MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m
MatrixSDK/VoIP/MXCall.m
MatrixSDK/VoIP/MXCallManager.h
MatrixSDK/VoIP/MXCallManager.m
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStack.m
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m

Fix vector-im/element-ios#4039

VoIP: Improve call connection state & Fix Ice Failures

---

CHANGES.rst
MatrixSDK/VoIP/MXCall.m

Fix vector-im/element-ios#4109

VoIP: Fix a Call Answering Issue

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/MXRoomSummary.h
MatrixSDK/Data/MXRoomSummary.m
MatrixSDK/Data/MXRoomSummaryUpdater.h
MatrixSDK/Data/MXRoomSummaryUpdater.m
MatrixSDK/Data/MXRoomType.h
MatrixSDK/Data/MXRoomTypeMapper.swift
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/JSONModels/MXRoomCreateContent.h
MatrixSDK/JSONModels/MXRoomCreateContent.m

Handle https://github.com/vector-im/element-ios/issues/4050

Support room type (MSC1840)

---

CHANGES.rst
MatrixSDK.podspec
Podfile
Podfile.lock

vector-im/element-ios/issues/4120

Pods: Update JitsiMeetSDK, OHHTTPStubs, Realm.

---

CHANGES.rst
MatrixSDK/Crypto/Recovery/MXRecoveryService.h
MatrixSDK/Crypto/Recovery/MXRecoveryService.m
MatrixSDK/Crypto/SecretStorage/MXSecretStorage.h
MatrixSDK/Crypto/SecretStorage/MXSecretStorage.m

fix https://github.com/vector-im/element-ios/issues/4189

Create secret storage with a given private key

---

CHANGES.rst
MatrixSDK/Contrib/Swift/MXRestClient.swift
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m

fix https://github.com/vector-im/element-ios/issues/4194

Enhance SDK to get the dehydrated device data

---

CHANGES.rst
MatrixSDK/Background/MXBackgroundSyncService.swift

Part of https://github.com/vector-im/element-ios/issues/4222

Notifications: Fix sender display name that can miss

---

MatrixSDK/Data/MXRoom.m

Fixes issue #1070
Signed-off-by: `Frantisek Hetes f.hetes@gmail.com`

Fix video duration value to work in Room Version 6

---

CHANGES.rst
MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m

Part of https://github.com/vector-im/element-ios/pull/4042

Update Incoming Calls if Answered from Application UI

---

CHANGES.rst
MatrixSDK/VoIP/MXCall.m

Disable call transfer for regular calls, fix transfer feature check to include right parties.

Call Transfers Fixes

---

CHANGES.rst
MatrixSDK.podspec
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/MXSession.m
MatrixSDKTests/MXFilterUnitTests.m
MatrixSDKTests/MXStoreFileStoreTests.m
Podfile
Podfile.lock

Add tests for filter cases for vector-im/element-ios#3921. Update outdated pods.

Tests for Store Filters

---

CHANGES.rst
MatrixSDK/Background/MXBackgroundCryptoStore.m
MatrixSDK/Background/MXStopwatch.swift
MatrixSDK/Crypto/Data/Store/MXCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.h
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Crypto/MXCrypto.m

Part of vector-im/element-ios#4352

MXRealmCryptoStore: ReadOnly Realms

---

CHANGES.rst
MatrixSDK/Data/MXEventTimeline.m
MatrixSDK/Data/MXRoomLastMessage.h
MatrixSDK/Data/MXRoomLastMessage.m
MatrixSDK/MXSession.m

Additional improvements for vector-im/element-ios#4360

Use `MXKeyProvider` for Room Last Message Encryption Key

---

CHANGES.rst
MatrixSDK/Contrib/Swift/Data/MXRoom.swift
MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m

Added voice message event type, implemented and exposed method for seding voice message.

Send voice messages

---

CHANGES.rst
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m

iOS part of https://github.com/matrix-org/matrix-js-sdk/pull/1728

VoIP: Change Hold Direction

---

CHANGES.rst
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m

Fix vector-im/element-ios#4418

Fix Crash in `MXRealmCryptoStore`

---

CHANGES.rst
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStack.m
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m
MatrixSDKExtensions/VoIP/Jingle/MXJingleCameraCaptureController.m

Fix vector-im/element-ios#4421

VoIP: Handle Offers when Peer Connection is Stable

---

CHANGES.rst
MatrixSDK/Crypto/Data/MXEncryptedAttachments.h
MatrixSDK/Crypto/Data/MXEncryptedAttachments.m
MatrixSDK/Crypto/Data/MXEncryptedContentFile.h
MatrixSDK/Crypto/Data/MXEncryptedContentFile.m
MatrixSDK/Data/MXRoom.m
MatrixSDK/Utils/Media/MXMediaManager.h
MatrixSDK/Utils/Media/MXMediaManager.m

Fix vector-im/element-ios#4303

Remove Redundant `mimetype` Fields

---

CHANGES.rst
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallAudioSessionConfigurator.m
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m

Use headphones and Bluetooth devices when available.

VoIP: Change Audio Output Routes

---

CHANGES.rst
MatrixSDK/Background/MXBackgroundSyncService.swift
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/MXSDKOptions.h
MatrixSDK/MXSDKOptions.m
MatrixSDK/MXSession.m

Introduces `autoAcceptRoomInvites` flag on `MXSDKOptions` which is false by default.

Auto Accept Room Invites

---

MatrixSDK/MXSession.m

only use rest client home server for wellknown request

---

MatrixSDK/Background/MXBackgroundCryptoStore.h
MatrixSDK/Crypto/KeyProvider/MXKeyProvider.h
MatrixSDK/Crypto/KeySharing/MXIncomingRoomKeyRequestManager.m
MatrixSDK/Crypto/MXOlmDevice.h
MatrixSDK/Crypto/Utils/MXAes.h
MatrixSDK/Crypto/Utils/MXAes.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/MXSession.h
MatrixSDK/Space/MXSpaceService.swift
MatrixSDK/Utils/Media/MXMediaManager.m

Xcode is reporting 34 warnings in MatrixSDK for me now, down from 45.

Fix some documentation and deprecation warnings

---

CHANGES.rst
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m

Related to https://github.com/vector-im/element-ios/issues/4094

Added all known voice message types.

---

CHANGES.rst
MatrixSDK/VoIP/MXCallManager.m

Do virtual user check on call transfers.

VoIP: Fix Call Transfer

---

CHANGES.rst
MatrixSDK/Background/MXBackgroundCryptoStore.m

Fix vector-im/element-ios#4534

Remove read-only Realm and try again if Olm account not found in crypto store

---

CHANGES.rst
MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/MXRoomLastMessage.h

1 nullability warning.
3 header warnings (possibly only seen when building from Xcode, rather than as a pod).

Fix a nullability and header warnings

---

CHANGES.rst
MatrixSDK/Data/MXRoomSummary.h
MatrixSDK/Data/MXRoomSummary.m
MatrixSDK/Data/MXRoomSummaryUpdater.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m

Fix https://github.com/vector-im/element-ios/issues/4585

MXRoomSummary: Cache local unread event count 

---

CHANGES.rst
MatrixSDK/VoIP/MXCall.m

Fix vector-im/element-ios#4612

VoIP: Prevent Session Pause until Reject/Hangup Event is Sent

---

CHANGES.rst
MatrixSDK/VoIP/MXCall.h
MatrixSDK/VoIP/MXiOSAudioOutputRoute.swift
MatrixSDK/VoIP/MXiOSAudioOutputRouteType.swift
MatrixSDK/VoIP/MXiOSAudioOutputRouter.swift
MatrixSDK/VoIP/MXiOSAudioOutputRouterDelegate.swift

Fix vector-im/element-ios#4622

VoIP: Fix Audio Routing Issues for Bluetooth Devices

---

CHANGES.rst
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
MatrixSDK/MXSession.m

Add missing maxUploadSize methods to MXNoStore and MXMemoryStore.

---

CONTRIBUTING.md

Inner-PR for https://github.com/matrix-org/matrix-ios-sdk/pull/1181

Fixes for CONTRIBUTING.md

---

CHANGES.rst
MatrixSDK/Data/MXRoomSummary.h
MatrixSDK/Data/MXRoomSummary.m
MatrixSDK/MXSession.m
changelog.d/4440.bugfix

Fix vector-im/element-ios#4440

MXSession: Improve and fix fixRoomsSummariesLastMessage

---

MatrixSDK/VoIP/MXCallManager.m
changelog.d/4664.bugfix

Fix vector-im/element-ios#4664

VoIP: Fix Dial pad Calling

---

MatrixSDK/VoIP/MXCallManager.m

Only adds logs for vector-im/element-ios#4687. That's why i didn't add a changelog.

VoIP: Add Logs for Recurring Calls

---

MatrixSDK/Contrib/Swift/MXRestClient.swift
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/Space/MXSpace.swift
MatrixSDK/Space/MXSpaceService.swift
MatrixSDKTests/MXSpaceServiceTest.swift

Fixes https://github.com/vector-im/element-ios/issues/4500

[Spaces] M10.5 SDK: Support suggested rooms #4500

---

MatrixSDK/Background/MXBackgroundStore.swift
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.h
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.h
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
MatrixSDK/Data/Store/MXStore.h
changelog.d/4383.api
changelog.d/4383.change

Part of vector-im/element-ios#4383

Lazy load Room Receipts

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
changelog.d/4788.change

Synchronizes creations for room messages, room outgoing messages and room receipts data.
Part of vector-im/element-ios#4788

Improvements for Timeline Regression

---

MatrixSDK/MXSession.m
changelog.d/4021.bugfix

Fix vector-im/element-ios#4021

Fix continue sync after receiving a call

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.h
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
changelog.d/4796.bugfix

Fix vector-im/element-ios#4796
The essential fix is at https://github.com/matrix-org/matrix-ios-sdk/pull/1219/commits/aac3398a63c8837af6b0b25b8bab029e8638d277. Other commits are naming changes.

Fix unread count regression

---

MatrixSDK/Data/MXUser.m
changelog.d/1207.bugfix
changelog.d/1207.change

Fix issue - Updating Profile Picture/Display Name doesn't work sometimes. #1207 

---

MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/Space/MXSpaceChildInfo.swift
MatrixSDK/Space/MXSpaceService.swift

Needed for https://github.com/vector-im/element-ios/issues/4571

 [Spaces] M10.7 Explore rooms #4571

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Space/MXSpaceNotificationCounter.swift
MatrixSDK/Space/MXSpaceNotificationState.swift
MatrixSDK/Space/MXSpaceService.swift

- Added `MXSpaceNotificationCounter`

[Spaces] pre release fixes

---

MatrixSDK/Contrib/Swift/MXRestClient.swift
MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/JSONModels/MXJSONModels.m
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m

- Implemented [GET] room summary request

[Spaces] M10.6.1 Handle space link #4498

---

MatrixSDK/MXSession.m
MatrixSDK/Space/MXSpaceService.swift

Avoid reentrance in space graph builder

avoid reentrance

---

MatrixSDK/Space/MXSpaceNotificationCounter.swift
MatrixSDK/Space/MXSpaceService.swift
changelog.d/4910.bugfix
changelog.d/4912.bugfix
changelog.d/4913.bugfix

fix https://github.com/vector-im/element-ios/issues/4910, fix https://github.com/vector-im/element-ios/issues/4912, fix https://github.com/vector-im/element-ios/issues/4913

Crash in MXSpaceService.prepareData

---

MatrixSDK/MXSession.m
MatrixSDK/Space/MXSpaceNotificationCounter.swift
MatrixSDK/Space/MXSpaceService.swift
changelog.d/4916.bugfix

Needed for https://github.com/vector-im/element-ios/issues/4916

Spaces still visible after logging in with another account #4916

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Contrib/Swift/MXEnumConstants.swift
MatrixSDK/MXSession.m
MatrixSDK/Utils/MXTools.swift
changelog.d/4915.bugfix

Fix vector-im/element-ios#4915

`MXSession` Pause Preventing Fix

---

MatrixSDK/MXSession.h
MatrixSDK/MXSession.m
MatrixSDK/Space/MXSpace.swift
MatrixSDK/Space/MXSpaceService.swift
changelog.d/4919.bugfix

Needed for https://github.com/vector-im/element-ios/issues/4919

App may not start in 1.6.0

---

MatrixSDK/Space/MXSpaceService.swift
changelog.d/4919.bugfix

Fix https://github.com/vector-im/element-ios/issues/4919.

MXSpaceService: Fix a crash due to recursion depth limit

---

MatrixSDK/Space/MXSpaceService.swift
changelog.d/4979.bugfix

fix https://github.com/vector-im/element-ios/issues/4979

Crash in MXSpaceService.prepareData() #4979

---

MatrixSDK/Space/MXSpaceService.swift

needed for https://github.com/vector-im/element-ios/issues/4570

[Spaces] M10.4.1 Home space data filtering #4570

---

MatrixSDK/Data/MXRoom.m
MatrixSDK/Data/ReplyEvent/Parser/MXReplyEventParser.m
MatrixSDK/Data/ReplyEvent/Parser/MXReplyEventParts.h
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m

Part of vector-im/element-ios#5007

Threads P0

---

MatrixSDK/MXSDKOptions.h
MatrixSDK/MXSDKOptions.m
MatrixSDK/Utils/MXTools.h
MatrixSDK/Utils/MXTools.m
changelog.d/4981.feature

To accompany https://github.com/vector-im/element-ios/issues/4981 and https://github.com/vector-im/element-ios/pull/5060

Client permalinks

---

MatrixSDK/Data/MXRoomSummaryUpdater.m
changelog.d/5105.bugfix

Part of fix for https://github.com/vector-im/element-ios/issues/5105

Fix room ordering

---

MatrixSDK/Data/MXRoomSummaryUpdater.m
changelog.d/5150.bugfix

Fix https://github.com/vector-im/element-ios/issues/5150

Room ordering: Improve membership event filtering

---

MatrixSDK/Space/MXSpace.swift
MatrixSDK/Space/MXSpaceService.swift
changelog.d/5181.bugfix

fix https://github.com/vector-im/element-ios/issues/5181

#5181 Phone is abnormally warm, and battery is drained faster than usual

---

.github/workflows/ci-lint.yml
.github/workflows/ci-unit-tests.yml
.github/workflows/nightly.yml
Gemfile
Gemfile.lock
changelog.d/5195.build
fastlane/Fastfile

Fix vector-im/element-ios#5195

Update CI to use Xcode 12.5

---

MatrixSDK.podspec
MatrixSDK/Crypto/Data/MXOutboundSessionInfo.h
MatrixSDK/Crypto/Data/MXOutboundSessionInfo.m
MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransaction.h
changelog.d/5194.bugfix

Part of https://github.com/vector-im/element-ios/issues/5194

Podspec: Make "MatrixSDKSwiftHeader.h" and all "*_Private.h" private headers

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/MatrixSDK.h
changelog.d/1308.improvement

Expose missing Jingle headers in umbrella header
Signed-off-by: Frantisek Hetes f.hetes@gmail.com

Expose missing Jingle headers in umbrella header

---

MatrixSDK/Contrib/Swift/MXResponse.swift
changelog.d/pr-1002.change

Replacement PR for #1002. Same code change, updated changelog.

Freeze MXResponse enum

---

MatrixSDK/Data/RoomList/CoreData/MXCoreDataRoomListDataFetcher.swift
changelog.d/5377.bugfix

Fix vector-im/element-ios#5377

Fix duplicated rooms on Home Tab

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Aggregations/MXAggregations.m
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/JSONModels/Event/Content/MXEventContentPollStart.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/MatrixSDK.h
MatrixSDK/Room/Polls/PollAggregator.swift
MatrixSDK/Room/Polls/PollBuilder.swift
MatrixSDK/Room/Polls/PollModels.swift
MatrixSDKTests/MXPollAggregatorTests.swift
changelog.d/5114.feature

Enabled poll start event editing and added `hasBeenEdited` on the PollAggregator.

Poll editing

---

MatrixSDK/Data/RoomSummaryStore/CoreData/MXCoreDataRoomSummaryStore.swift
MatrixSDK/MXSession.m
changelog.d/5412.bugfix
changelog.d/5412.change

Fixes vector-im/element-ios#5412

Fix Room Summaries Storage Crash

---

MatrixSDK/Space/MXSpace.swift
changelog.d/5432.bugfix

fix https://github.com/vector-im/element-ios/issues/5432

Space invites are not displayed in space list #5432

---

MatrixSDK/Data/MXRoomMember.m
changelog.d/2827.bugfix

Fixes https://github.com/vector-im/element-ios/issues/2827

Fix displayname and avatar for users that have left the room.

---

MatrixSDK/Data/RoomSummaryStore/CoreData/MXCoreDataRoomSummaryStore.swift
changelog.d/5462.bugfix

Fix vector-im/element-ios#5462

Fix room list sorting

---

MatrixSDK/Data/RoomList/Common/MXSuggestedRoomListDataFetcher.swift
MatrixSDK/Data/RoomList/CoreData/MXCoreDataRoomListDataFetcher.swift
MatrixSDK/Data/RoomList/MXRoomListDataFetcherDelegate.swift
MatrixSDK/Data/RoomList/MXStore/MXStoreRoomListDataFetcher.swift
MatrixSDKTests/MXCoreDataRoomListDataManagerUnitTests.swift
changelog.d/5448.change

Adds `totalCountsChanged` parameter to the delegate method. Part of vector-im/element-ios#5448

Enhance `MXRoomListDataFetcherDelegate`

---

MatrixSDK/Data/RoomList/MXRoomListData.swift
changelog.d/5537.bugfix

Fixes another case for vector-im/element-ios#5537

MXRoomListData: Fix Comparison

---

MatrixSDK/Data/EventTimeline/Thread/MXThreadEventTimeline.swift
MatrixSDK/Threads/MXThreadingService.swift
changelog.d/5629.change

Part of vector-im/element-ios#5629

Threads: Replace `/context` api

---

MatrixSDK/Data/EventTimeline/Thread/MXThreadEventTimeline.swift
MatrixSDK/Threads/MXThreadingService.swift
MatrixSDK/Utils/MXMulticastDelegate.swift
changelog.d/5675.bugfix

Fix vector-im/element-ios#5675

Thread Safety Updates

---

MatrixSDK/Categories/MXEvent+Extensions.swift
changelog.d/5552.change

Improvement for vector-im/element-ios#5552

Do not highlight events sent by the current user

---

MatrixSDK/Data/RoomList/Common/MXRoomListDataFilterable.swift
MatrixSDK/Data/RoomList/CoreData/MXCoreDataRoomListDataFetcher.swift
MatrixSDK/Data/RoomList/MXRoomListDataFilterOptions.swift
changelog.d/pr-1379.change

Add the possibility to define strict matches for fetcher

Add strict matches to room filters predicate

---

MatrixSDK/Data/RoomList/Common/MXSuggestedRoomListDataFetcher.swift
MatrixSDK/Data/RoomList/CoreData/MXCoreDataRoomListDataManager.swift
MatrixSDK/Data/RoomList/MXStore/MXStoreRoomListDataManager.swift
changelog.d/5276.bugfix

fix https://github.com/vector-im/element-ios/issues/5276

Hide suggested rooms that a user is already part of

---

MatrixSDK/Aggregations/MXAggregatedEditsUpdater.m
MatrixSDK/Aggregations/MXAggregatedReactionsUpdater.m
MatrixSDK/Crypto/Verification/JSONModels/MXKeyVerificationJSONModel.m
MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
MatrixSDK/Data/MXRoom.m
MatrixSDK/JSONModels/Event/Content/MXEventContentRelatesTo.h
MatrixSDK/JSONModels/Event/Content/MXEventContentRelatesTo.m
MatrixSDK/JSONModels/Event/MXEventRelations.m
MatrixSDK/JSONModels/Event/MXInReplyTo.h
MatrixSDK/JSONModels/Event/MXInReplyTo.m
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/MXRestClient.m
MatrixSDKTests/MXAggregatedEditsTests.m
MatrixSDKTests/MXAggregatedEditsUnitTests.m
MatrixSDKTests/MXAggregatedReferenceTests.m
MatrixSDKTests/MXAggregatedReferenceUnitTests.m
MatrixSDKTests/MXCryptoTests.m
MatrixSDKTests/MXEventAnnotationUnitTests.swift
MatrixSDKTests/MXEventReferenceUnitTests.swift
MatrixSDKTests/MXFilterUnitTests.m
MatrixSDKTests/MXPushRuleUnitTests.m
MatrixSDKTests/MXReplyEventParserUnitTests.m
MatrixSDKTests/MXRoomTests.m
MatrixSDKTests/MXThreadingServiceUnitTests.swift
changelog.d/5704.change

Fix vector-im/element-ios#5704

Update property for in-thread replies

---

MatrixSDK/Background/MXBackgroundStore.swift
MatrixSDK/Contrib/Swift/MXSession.swift
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXFileStore/MXFileStoreMetaData.h
MatrixSDK/Data/Store/MXFileStore/MXFileStoreMetaData.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
MatrixSDK/Data/Store/MXStore.h
MatrixSDK/JSONModels/Capabilities/MXCapabilities.h
MatrixSDK/JSONModels/Capabilities/MXCapabilities.m
MatrixSDK/JSONModels/MXMatrixVersions.h
MatrixSDK/JSONModels/MXMatrixVersions.m
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m
MatrixSDK/MatrixSDK.h
MatrixSDK/Threads/MXThreadingService.swift
changelog.d/5744.change

Fix vector-im/element-ios#5744

Threads server support check

---

MatrixSDK/Data/MXRoom.m
MatrixSDK/JSONModels/Event/Content/MXEventContentRelatesTo.h
MatrixSDK/JSONModels/Event/Content/MXEventContentRelatesTo.m
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/Threads/MXThread.swift
changelog.d/5790.change

Fix vector-im/element-ios#5790

Threads: New Reply Fallback

---

MatrixSDK/Contrib/Swift/Data/MXRoom.swift
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDKTests/MXCryptoTests.m
MatrixSDKTests/MXRoomTests.m
MatrixSDKTests/MXThreadingServiceTests.swift
changelog.d/5829.change

Part of vector-im/element-ios#5829

Add threadId parameter for reply method

---

MatrixSDK/Space/MXSpaceService.swift
changelog.d/5401.change

needed for https://github.com/vector-im/element-ios/issues/5401

Instrument metrics for iOS for the IA project #5401

---

MatrixSDK/Threads/MXThreadingService.swift
changelog.d/5843.change

Fixes vector-im/element-ios#5843

Fix thread list dots

---

MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
MatrixSDK/Data/MXRoomAccountData.h
MatrixSDK/Data/MXRoomAccountData.m
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/Space/MXSpace.swift
MatrixSDK/Space/MXSpaceService.swift
changelog.d/5134.bugfix

needed for https://github.com/vector-im/element-ios/issues/5134
Note that we force initial sync by updating the `kMXFileVersion` as room additional account data was not stored.

Sync space order with web #5134

---

MatrixSDK/Threads/MXThread.swift
MatrixSDK/Threads/MXThreadingService.swift
changelog.d/5877.bugfix

Fixes vector-im/element-ios#5877
Fixes vector-im/element-ios#5884

Thread summary fixes

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Data/MXRoom.h
MatrixSDK/Data/MXRoom.m
MatrixSDK/JSONModels/Event/Content/MXEventContentLocation.h
MatrixSDK/JSONModels/Event/Content/MXEventContentLocation.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/MatrixSDK.h
MatrixSDK/Utils/MXEventAssetTypeMapper.swift
changelog.d/5858.api

https://github.com/vector-im/element-ios/issues/5858

[Location Sharing]: Pin drop location sharing

---

MatrixSDK/JSONModels/MXJSONModels.m
changelog.d/5953.change

Needed for https://github.com/vector-im/element-ios/issues/5953

Add support for Apple context menus in matrix items list screens #5953

---

MatrixSDK/Threads/MXThreadModel.swift
MatrixSDK/Threads/MXThreadingService.swift
changelog.d/5845.bugfix

Fixes edited thread root and latest events in a thread list.
Fixes vector-im/element-ios#5845
Fixes vector-im/element-ios#5847

Thread list edits

---

MatrixSDK/Data/RoomList/Common/MXSuggestedRoomListDataFetcher.swift
changelog.d/5978.bugfix

Resolves https://github.com/vector-im/element-ios/issues/5978

Spaces shouldn't be displayed as suggested rooms

---

MatrixSDK/JSONModels/MXJSONModels.h
MatrixSDK/MXSession.h
MatrixSDK/MXSession.m
changelog.d/5995.change

Part of https://github.com/vector-im/element-ios/issues/5995

Add a preferred presence property to MXSession

---

MatrixSDK/Categories/MXEvent+Extensions.swift
MatrixSDK/Crypto/CrossSigning/MXCrossSigning.m
MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
MatrixSDK/Utils/MXUIKitBackgroundModeHandler.m
changelog.d/6023.bugfix

Part of vector-im/element-ios#6023

Fix some crashes

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Aggregations/LocationSharing/MXBeaconAggregations.swift
MatrixSDK/Aggregations/LocationSharing/MXBeaconInfoSummaryListener.swift
MatrixSDK/Aggregations/LocationSharing/MXBeaconInfoSummaryStore.swift
MatrixSDK/Aggregations/LocationSharing/MXBeaconInfoSummaryStoreProtocol.swift
MatrixSDK/Aggregations/MXAggregations.h
MatrixSDK/Aggregations/MXAggregations.m
MatrixSDK/Contrib/Swift/JSONModels/MXEvent.swift
MatrixSDK/JSONModels/Event/Content/MXEventContentLocation.m
MatrixSDK/JSONModels/Location/MXBeacon.h
MatrixSDK/JSONModels/Location/MXBeacon.m
MatrixSDK/JSONModels/Location/MXBeaconInfo.h
MatrixSDK/JSONModels/Location/MXBeaconInfo.m
MatrixSDK/JSONModels/Location/MXGeoURIComponents.swift
MatrixSDK/JSONModels/Location/MXLocation.h
MatrixSDK/JSONModels/Location/MXLocation.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/LocationSharing/MXBeaconInfoSummary.swift
MatrixSDK/LocationSharing/MXBeaconInfoSummaryProtocol.swift
MatrixSDK/LocationSharing/MXLocationService.swift
MatrixSDK/LocationSharing/MXLocationServiceError.swift
MatrixSDK/MatrixSDK.h
MatrixSDK/Utils/MXTools.m
MatrixSDKTests/MXBeaconAggregationsTests.swift
MatrixSDKTests/MXGeoURIComponentsUnitTests.swift
changelog.d/6021.wip

https://github.com/vector-im/element-ios/issues/6021

[Location sharing] Handle live location beacon event 

---

MatrixSDK/Aggregations/LocationSharing/MXBeaconAggregations.swift
MatrixSDK/Aggregations/LocationSharing/MXBeaconInfoSummaryStore.swift
MatrixSDK/Aggregations/LocationSharing/MXBeaconInfoSummaryStoreProtocol.swift
MatrixSDK/JSONModels/Location/MXBeaconInfo.h
MatrixSDK/JSONModels/Location/MXBeaconInfo.m
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/JSONModels/MXEvent.m
MatrixSDK/JSONModels/MXEventAssetType.h
MatrixSDK/LocationSharing/MXBeaconInfoSummary.swift
MatrixSDK/LocationSharing/MXLocationService.swift
MatrixSDK/LocationSharing/MXLocationServiceError.swift
MatrixSDK/Utils/MXEventAssetTypeMapper.swift
MatrixSDKTests/MXBeaconAggregationsTests.swift
MatrixSDKTests/MXBeaconInfoUnitTests.swift
changelog.d/6070.wip

[#6070](https://github.com/vector-im/element-ios/issues/6070)

[Location sharing] Handle m.beacon_info stop

---

1460.misc
MatrixSDK/JSONModels/MXMatrixVersions.m

Citation: https://matrix.to/#/!ewdjhNcPcEmYNKzlWp:t2l.io/$CkPuvKdFZyFL547JCy5J3MfvLaWUo_a1XEdmiop1PKc?via=matrix.org&via=element.io&via=envs.net

Remove spec v1.3 check for threads

---

MatrixSDK/Crypto/Data/MXMegolmSessionData.m
MatrixSDKTests/Crypto/Data/MXMegolmSessionDataUnitTests.swift

Only accept incoming sharedHistory value from backup if build flag is enabled

Shared backups with build flag

---

MatrixSDK/Background/MXBackgroundStore.swift
MatrixSDK/Data/MXRoomSummaryUpdater.m
MatrixSDK/Data/RoomSummaryStore/CoreData/MXCoreDataRoomSummaryStore.swift
MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
MatrixSDK/Data/Store/MXMemoryStore/MXMemoryStore.m
MatrixSDK/Data/Store/MXNoStore/MXNoStore.m
MatrixSDK/Data/Store/MXStore.h
MatrixSDK/MXSession.m
changelog.d/5924.bugfix

Fixes vector-im/element-ios#5924
Also maybe a fix for vector-im/element-ios#6006

Recreate summaries when detected missing

---

6142.misc
MatrixSDK/Crypto/MXCrypto.m
MatrixSDK/VoIP/MXCall.h
MatrixSDK/VoIP/MXCallManager.m
MatrixSDKTests/MXBackgroundSyncServiceTests.swift

Adds tests for vector-im/element-ios#6142

Add tests for gappy and outdated sync response

---

MatrixSDK/Data/RoomSummaryStore/CoreData/MXCoreDataRoomSummaryStore.swift
changelog.d/6218.bugfix

Fixes vector-im/element-ios#6218

Fix Core Data concurrency issue

---

MatrixSDK/MXRestClient.m
MatrixSDK/Utils/MXTools.swift
MatrixSDKTests/MXToolsUnitTests.m
changelog.d/6224.bugfix

fix https://github.com/vector-im/element-ios/issues/6224

Cannot join rooms with large amount of via servers #6224

---

MatrixSDK/Aggregations/LocationSharing/MXBeaconAggregations.swift
MatrixSDK/Aggregations/LocationSharing/Store/MXBeaconInfoSummaryMemoryStore.swift
MatrixSDK/Aggregations/LocationSharing/Store/MXBeaconInfoSummaryStoreProtocol.swift
MatrixSDK/Aggregations/LocationSharing/Store/Realm/MXBeaconInfoSummaryRealmStore.swift
MatrixSDK/LocationSharing/MXLocationService.swift
MatrixSDKTests/MXLocationServiceTests.swift
changelog.d/6100.wip

https://github.com/vector-im/element-ios/issues/6100

Location sharing: Authorize only one live beacon info per member and per room

---

MatrixSDK/Data/RoomSummaryStore/CoreData/Models/MXRoomSummaryMO.swift
changelog.d/pr-1490.bugfix

```
Thread 23 name:
Thread 23 Crashed:
0   MatrixSDK                     	0x00000001038fa544 Swift runtime failure: Not enough bits to represent the passed value + 0 (<compiler-generated>:0)
1   MatrixSDK                     	0x00000001038fa544 $sSZss17FixedWidthIntegerRzrlEyxqd__cSzRd__lufCs5Int16V_SuTg5 + 0 (<compiler-generated>:0)
2   MatrixSDK                     	0x00000001038fa544 MXRoomSummaryMO.update(withRoomSummary:in:) + 4308 (MXRoomSummaryMO.swift:94)
3   MatrixSDK                     	0x00000001038f9abc MXRoomSummaryMO.update(withRoomSummary:in:) + 1612 (MXRoomSummaryMO.swift:94)
4   MatrixSDK                     	0x00000001038ad668 closure #1 in MXCoreDataRoomSummaryStore.saveSummary(_:) + 156 (MXCoreDataRoomSummaryStore.swift:178)
5   MatrixSDK …
```

Fix crash on launch due to an insane number of unread events

---

MatrixSDK/JSONModels/Location/MXGeoURIComponents.swift
MatrixSDKTests/MXGeoURIComponentsUnitTests.swift
changelog.d/6247.bugfix

Fix https://github.com/vector-im/element-ios/issues/6247

Location sharing: Fix geo URI parsing with altitude component

---

.github/workflows/ci-crypto-tests.yml
.github/workflows/ci-lint.yml
.github/workflows/ci-unit-tests.yml
changelog.d/5039.build

Very delayed follow-up to https://github.com/vector-im/element-ios/pull/5101, this PR adds concurrency to the SDK actions.
Closes https://github.com/vector-im/element-ios/issues/5039.

Add concurrency to GitHub Actions.

---

MatrixSDK/VoIP/MXCall.m
MatrixSDKExtensions/VoIP/Jingle/MXJingleCallStackCall.m
changelog.d/6359.bugfix

Resolves https://github.com/vector-im/element-ios/issues/6359

Fix MXCall answer not being sent to server in some cases

---

MatrixSDK/VoIP/MXCall.m
changelog.d/6415.bugfix

Fixes https://github.com/vector-im/element-ios/issues/6415

Fix JingleCallStack UI threading crashes

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Aggregations/LocationSharing/MXBeaconAggregations.swift
MatrixSDK/Aggregations/LocationSharing/MXBeaconInfoSummaryDeletionAllRoomListener.swift
MatrixSDK/Aggregations/LocationSharing/MXBeaconInfoSummaryDeletionPerRoomListener.swift
MatrixSDK/LocationSharing/MXLocationService.swift
changelog.d/6470.change

Part of https://github.com/vector-im/element-ios/issues/6470

Location sharing: Handle live location sharing delete (PSG-487)

---

README.rst
changelog.d/sdk-1552.doc

Update README with correct Swift usage.

---

MatrixSDK/Data/Store/MXFileStore/MXFileStore.m
changelog.d/6616.change

App Layout: force clear cache

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/CrossSigning/JSONModels/MXCrossSigningKey.m
MatrixSDK/Crypto/CrossSigning/MXCrossSigningTools.m
MatrixSDK/Crypto/CrossSigning/MXCrossSigningV2.swift
MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
MatrixSDK/Crypto/Data/MXCryptoConstants.h
MatrixSDK/Crypto/Data/MXCryptoConstants.m
MatrixSDK/Crypto/Data/MXKey.h
MatrixSDK/Crypto/Data/MXKey.m
MatrixSDK/Crypto/MXCryptoV2.swift
MatrixSDK/Crypto/MXOlmDevice.m
MatrixSDK/Crypto/Recovery/MXRecoveryService.h
MatrixSDK/Crypto/Verification/MXKeyVerificationManager.h
MatrixSDK/Crypto/Verification/MXKeyVerificationManager.m
MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequestV2.swift
MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransactionV2.swift
MatrixSDK/MatrixSDK.h
MatrixSDKTests/Crypto/CrossSigning/MXCrossSigningV2UnitTests.swift
MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
MatrixSDKTests/Crypto/Devices/MXDeviceInfoSourceUnitTests.swift
MatrixSDKTests/Crypto/Verification/Requests/MXKeyVerificationRequestV2UnitTests.swift
MatrixSDKTests/Crypto/Verification/Transactions/SAS/MXSASTransactionV2UnitTests.swift
MatrixSDKTests/TestPlans/UnitTests.xctestplan
MatrixSDKTests/TestPlans/UnitTestsWithSanitizers.xctestplan
changelog.d/6589.feature

Resolves https://github.com/vector-im/element-ios/issues/6589
Implement self-verification flow using rust-based OlmMachine. Changes include:
- Split up CryptoMachine verification methods into further, more separated protocols
- handle verification to-device events returned by CryptoMachine
- pass verification handler to requests and transactions

Self-verification flow in Crypto V2

---

MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/MXSession.m
changelog.d/pr-1582.change

Matrix client information on account data

---

MatrixSDK.xcodeproj/project.pbxproj
MatrixSDK/Crypto/Algorithms/Olm/MXOlmDecryption.m
MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
MatrixSDK/Crypto/CryptoMachine/MXCryptoProtocols.swift
MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
MatrixSDK/Crypto/Verification/Requests/MXKeyVerificationRequestV2.swift
MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransaction.h
MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransaction.m
MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransactionV2.swift
MatrixSDK/Crypto/Verification/Transactions/SAS/MXSASTransactionV2.swift
MatrixSDKTests/Crypto/CryptoMachine/MXCryptoProtocolStubs.swift
MatrixSDKTests/Crypto/Verification/Transactions/QRCode/MXQRCodeTransactionV2UnitTests.swift
MatrixSDKTests/Crypto/Verification/Transactions/QRCode/QrCode+Stub.swift
MatrixSDKTests/TestPlans/UnitTests.xctestplan
MatrixSDKTests/TestPlans/UnitTestsWithSanitizers.xctestplan
changelog.d/6859.change

Resolves https://github.com/vector-im/element-ios/issues/6859

QR code verification with Crypto V2

---

MatrixSDK/Contrib/Swift/MXRestClient.swift
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
changelog.d/1619.wip

New endpoint for [multi-signout](https://spec.matrix.org/v1.4/client-server-api/#post_matrixclientv3delete_devices)
Closes #1619

Device Manager: Multi session sign out.

---

README.rst
changelog.d/pr-1625.doc

The doc using virtual env was obsolete.

Doc: Update the synapse installation section with poetry usage

---

MatrixSDK/Threads/MXThreadNotificationsCount.swift
MatrixSDK/Threads/MXThreadingService.swift
changelog.d/7076.bugfix

Needed for https://github.com/vector-im/element-ios/issues/7076

Display number of unread messages above threads button

---

MatrixSDK/Data/MXRoomState.m

This reverts commit a7a278121ede51a8decd2e753dfba459a917d450.

Revert "Fix room state for peeking"

---

MatrixSDK/Contrib/Swift/MXRestClient.swift
MatrixSDK/MXRestClient.h
MatrixSDK/MXRestClient.m
MatrixSDK/Threads/MXThreadingService.swift
MatrixSDKTests/MXFilterTests.m
MatrixSDKTests/MXSpaceServiceTest.swift
changelog.d/6059.feature

Load the thread list using server-side sorting and pagination

---

MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventDecryption.swift
MatrixSDK/Crypto/Algorithms/RoomEvent/MXRoomEventEncryption.swift
MatrixSDK/Crypto/CryptoMachine/MXCryptoMachine.swift
MatrixSDK/Crypto/CryptoMachine/MXCryptoSDKLogger.swift
MatrixSDK/Crypto/KeyBackup/MXKeyBackup.m
MatrixSDK/Crypto/MXCryptoV2.swift

A few changes in crypto logging to make logs less verbose where this isn't necessary

Minor crypto logging changes

---

MatrixSDK/VoIP/CallKit/MXCallKitAdapter.m
MatrixSDK/VoIP/CallKit/MXCallKitConfiguration.h
MatrixSDK/VoIP/CallKit/MXCallKitConfiguration.m
changelog.d/pr-1738.change

This PR supersedes #1085  to cover call transfer about other use cases too.

Make CallKit maximumCallGroups configurable

---

MatrixSDK/Data/RoomList/CoreData/MXCoreDataRoomListDataFetcher.swift
MatrixSDK/Data/RoomSummaryStore/CoreData/MXCoreDataRoomSummaryStore.swift
changelog.d/6871.bugfix

Fixes https://github.com/vector-im/customer-retainer/issues/19
Fixes https://github.com/vector-im/element-ios/issues/6871
**Fix explanation**: https://developer.apple.com/documentation/coredata/nsfetchrequest/1506724-includespendingchanges#1679618

Fix invites badge count

---

MatrixSDK/Crypto/CrossSigning/MXCrossSigningV2.swift
MatrixSDK/Crypto/Verification/MXKeyVerificationManagerV2.swift
MatrixSDK/JSONModels/MXEvent.h
MatrixSDK/Room/Polls/PollAggregator.swift
changelog.d/pr-1746.change

Also expand on logs in cross-signing

Ensure related event nullability

---

MatrixSDK.podspec
MatrixSDK/Crypto/MXCryptoV2.swift
MatrixSDK/Crypto/MXCryptoV2Feature.swift
MatrixSDK/Utils/MXBugReportRestClient.m
Podfile
Podfile.lock
changelog.d/7457.change

Resolves https://github.com/vector-im/element-ios/issues/7457

Display correct version of Crypto SDK

---

MatrixSDK.podspec
Podfile
Podfile.lock
changelog.d/pr-1767.change

Resolves https://github.com/vector-im/element-ios/issues/7496
Latest version containing some deserialization bugfixes

Update Crypto SDK

---

MatrixSDK.podspec
changelog.d/7565.change

JItsi SDK update

---

MatrixSDK/NotificationCenter/MXNotificationCenter.m
changelog.d/7601.bugfix

Fixes: vector-im/element-ios#7601

Ignore push rules with unknown condition kinds

---

MatrixSDK/Crypto/Verification/Transactions/QRCode/MXQRCodeTransactionV2.swift
changelog.d/1816.bugfix

Fixes https://github.com/vector-im/element-ios/issues/7660

Fix passing padded base64 instead of unpadded

---

README.rst

The pod is no longer published, so add instructions for adding the dependency via git.

Update README for latest packaging changes.
